include/seastar/core/abort_source.hh, tests/unit/abort_source_test.cc
Change 19b9e4d2c9b5cc6834b5df928092cd7d820b0700 added an optional
parameter to request_abort, defaulted to nullopt.
Normally, this is backward compatible, but sites using
the no-args method by reference / pointer break since
it is no longer available.
For example: `_abort_sources.invoke_on_all(&abort_source::request_abort)`
This change restores the legacy method with the no-args signature
and renames the additional entry-points that accept an exception
to request_abort_ex to keep the interface backward compatible.
Otherwise, the compiler is not smart enough to derive
the right overload for invoke_on_all. See following error from
scylla/main.c:
```
main.cc:117:35: error: no matching member function for call to 'invoke_on_all'
return …
```
=> abort_source: request_abort: restore legacy no-args method

include/seastar/testing/perf_tests.hh
Currently perf_tests::start_measuring_time (and the corresponding
stop call) doesn't correctly measure the instruction count.
It always reports 0 instructions if any of these methods is used
in a perf test.
To fix this, we capture the linux_perf_event pointer in
the time_measurement class.
=> Fix instruction count for start_measuring_time

include/seastar/core/reactor.hh
=> reactor: Remove some unused friend declarations

src/core/reactor_backend.cc
The existing assert that was introduced in
528762adbaf2c6dde857957b920606378959e8fb
is too harsh.  It will fail on the first retry
failure after `needs_preeempt` returned true.
This lead to the following crash:
```
scylla: ./seastar/src/core/reactor_backend.cc:286: size_t seastar::aio_general_context::flush(): Assertion `retried != begin' failed.
```
Decoded backtrace:
```
seastar::aio_general_context::flush() at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:286
(inlined by) seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:489
seastar::reactor::sleep() at ./build/release/seastar/./seastar/src/core/reactor.cc:3041
(inlined by) seastar::reactor::do_run() at …
```
=> aio_general_context: flush: provide 1 second grace for retries

include/seastar/http/reply.hh
=> HTTP: define formatter for status_type to fix build.

include/seastar/core/shared_ptr.hh
before GCC addresses this issue, we have to disable this warning.
see also https://github.com/scylladb/seastar/issues/1037 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105204.
=> shared_ptr: ignore false alarms from GCC-12

tests/unit/spawn_test.cc
so we can understand the failure better.
=> test: log error when read/write to pipe fails

include/seastar/core/sstring.hh
Reduce bus-factor a little bit
=> sstring: Document why sstring exists at all

demos/http_client_demo.cc
The connection class wraps connected_socket of any "kind", so to make https working one needs to provide the tls one and that's it.
=> demo: Extend http connection demo with https

tests/unit/tls_test.cc
- tls_test: remove duplicated test case
- tls_test: drop duplicated includes
=> tls_test: remove duplicated include and test

cmake/FindLibUring.cmake, pkgconfig/seastar.pc.in
- build: s/URING_LIBARIES/URING_LIBRARIES/
- build: export the full path of uring with URING_LIBRARIES
=> build: export liburing_libs with its fullpath

cmake/Findyaml-cpp.cmake, cooking_recipe.cmake
- build: bump yaml-cpp to 0.7.0 in cooking_recipe
- build: do not use pkg_search_module(IMPORTED_TARGET) for finding yaml-cpp
- build: detect debug build of yaml-cpp also
=> build: bump cooking recipe of yaml-cpp and find debug build of yaml-cpp

include/seastar/core/reactor.hh, include/seastar/util/process.hh, src/core/reactor.cc, src/util/process.cc, tests/unit/spawn_test.cc
so we can terminiate a subprocess
=> reactor: add process::terminate() and process::kill()

tests/unit/loopback_socket.hh
this change should address the regression introduced by 6cd5f9fb1cbbe90acf9f63305c4c412e765e34fa.
before this change, in
`loopback_connection_factory::destroy_all_shards()`, we use the current shard id as the index in `_pending`, and submit `destroy_shard()` to all shards, but there are chances that the Seastar application is configured with more shards than loopback_connection_factory is. in 6cd5f9fb1cbbe90acf9f63305c4c412e765e34fa, we limit the loopback connection factory sharding to 1, but in general, we run the tests with two shards, hence we have the heap-buffer-overflow failure reported by ASan after that commit.
after this change,
* `destroy_all_shards()` only destroys the pending connections on allocated shards.
* and assert() is added to ensure we don't have out-of-bound access …
=> tests: only destroy allocated pending connections

src/core/reactor_backend.cc
before this change, a while loop is used for submitting i/o requests in aio_storage_context. it's not very obvious how the iterator is incremented.
after this change, a for loop is used. and iocbs is used as an iterator to advance in _submission_queue, so the
aio_storage_context::submit_work() can have a better readability.
=> reactor: use a for loop for submitting ios

install-dependencies.sh, src/core/reactor.cc
=> build: install liburing explicitly on ArchLinux.

include/seastar/core/metrics.hh
also reorder includes alphabetically.
for better readability, and less maintenance burden.
=> metrics: replace homebrew is_callable<> with is_invocable_v<>

include/seastar/core/sstring.hh
=> sstring: use fold expression to simplify make_sstring()

include/seastar/core/sstring.hh
as fmtlib claims that it is
> faster than common standard library implementations of (s)printf
and the new implementation is also simpler than the old one.
=> sstring: refactor to_sstring() using fmt::format_to()

src/core/resource.cc
Currently, when hwloc is not available, we still observe a significant amount
of memory leakage when "total_avail_memory / cpu_num" is larger than 64GB. The
reason is quite similar to which led to commit https://github.com/scylladb/seastar/commit/cfec74de07994cdc500040f114243e0024181d00,
which is: when "total_avail_memory / cpu_num" is larger than 64GB, the last cpu
can allocate a piece of memory space outside its 64GB range and no other cpu
can free it.
This should be a complement for commit cfec74de07994cdc500040f114243e0024181d00
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>
=> Limit memory address space per core to 64GB when hwloc is not available

src/core/memory.cc
When seastar is configured to throw on allocation failure, we have a bunch of rules which determine whether a memory diagnosis report is output, to avoid spamming the log in the case of repeated failures. In general this means that most allocation failures are logged at debug log level, with some "critical" failures being logged at error.
However, when --abort-on-seastar-bad-alloc is set, there will be at most one allocation failure in the lifetime of the process, after which will we abort so we'd *really* like the diagnosis to appear before we abort: essentially all allocation failures are "critical".
Enforce this by always logger at error log level when a failure occurs that will cause an abort.
=> Dump memory diagnostics at error level if we are aborting

include/seastar/core/semaphore.hh, tests/unit/semaphore_test.cc
semaphore_units keeps a pointer to the semaphore
soe if the semaphore is moved and/or destroyed
destroying the sempahore_units will caused
use-after-move or use-after-free.
This change adds _outstanding_units counter member to basic_semaphore and manages it in semaphore_units. semaphore move constructor then asserts that
o._outstanding_units == 0 when moved.
Add a unit test to semaphore_test to cover this case.
Refs #1323
=> semaphore: assert no outstanding units when moved

src/core/app-template.cc
=> app-template: remove duplicated includes

include/seastar/core/semaphore.hh
Referring to #1323 and discussion in #1477.
Avi Kivity <avi@scylladb.com> asserted that:
> We have a choice:
> declare that most things can be movable and live with the complication and slowdown
> declare that control structures (like semaphores) have stable addresses (as they typically do anyway)
> There's really no reason to move a sempahore.
Gleb Natapov <gleb@scylladb.com> proposed:
> add an assertion in debug mode if a semaphore is moved after the first use. It can be a simple bool that is set to true on the first wait().
Since we still need to be able to move the semaphore
after it created this patch adds `bool _used` and implements
the move ctor, asserting that the semaphore is moved before used.
Close #1323
=> Simplify semaphore move protection

src/core/reactor.cc
On most distributions and containers the perf-based stall detector will fail because /proc/sys/kernel/perf_event_paranoid is set to 2 or higher, which prevents non-root processes from profiling the kernel.
Instead we log a different message, telling the user what they can do if they want kernel backtraces, at INFO and only on shard 0 (so we don't need to see this advice repeated 128 times on a big box).
=> Downgrade expected stall detector warning to info

tests/perf/perf_tests.cc
so we can just copy-and-paste the output as table with markdown syntax. this should help with developers who want to share the output in their documents or pull requests.
=> tests: perf: add a markdown printer

src/core/file.cc
for better readability. as it would be immediately clear to the developer that we are calling this lambda, not defining a variable holding it, as he/she does not have to parse the last token in this expression to get this information.
=> file: call lambda with std::invoke()

src/net/dns.cc
a std::system_error in udp.channel.send(...) can go unhandled, if the future is not available immediately. For example, ECONNABORTED can go uncaught and be shown in the log as an Error.
This commit adds a handler to log it as a warning, since the protocol already handles the case of lost udp packets
=> dns: handle exception in do_sendv for udp

include/seastar/core/semaphore.hh, tests/unit/semaphore_test.cc
The default move-ctor naively moves the wait list
expiry_handler while the latter keeps a reference
to the moved semaphore.
Using it after the move might cause use-after-free or stack-use-after-return.
Fixes scylladb/seastar#1809
Refs scylladb/scylladb#15253
=> semaphore: initialize wait_list in move ctor

src/core/reactor_backend.cc
Using the epoll backend and having a non-closed socket that got terminated
with either EPOLLHUP|EPOLLERR under the hood but isn't closed yet can lead to
busy spinning in the reactor at 100%.
It's caused by the following scenario:
- epoll_pwait returns an event for a socket with EPOLLIN|EPOLLHUP (or
EPOLLOUT in a different respective case)
- We enter the error branch and set evt.events. This doesn't make much
difference at this point as pfd->events_requested is still equal to
EPOLLIN
- events_to_remove is calculated to 0
- complete_epoll_event is called setting pfd->events_requested to 0
- The loop concludes without removing the socket from the epoll set as
we calculate events_to_remove before changing it. I think this is
intended to avoid unneeded syscalls in the good case (so usually …
=> epoll: Avoid spinning on aborted connections

tests/unit/network_interface_test.cc
to ensure that we adhere to the related RFC. because seastar::inet_address does not have its own test suite, let's colocate it with the tests for network_interfaces() at this moment. we can extract them out once there are more of them.
Refs https://github.com/scylladb/scylladb/issues/16039
=> test: network_interface_test: add tests for format and parse

include/seastar/core/sharded.hh
Currently, the vector of instances is allocated on shard 0, including a promise<> per instance, yet those promises are accessed on each instance shard, which is susceptible to #1563.
To prevent that, move the promise to `async_sharded_service`, as it is used only with this class, and add
sharded::entry::track_deletion() that gets a future from the said promise on the shard it was allocated on if the Service base class is `async_sharded_service<Service>`.
=> sharded: access instance promise only on instance shard

src/core/fair_queue.cc
A fair queue's priority class have two bits -- queued and plugged.
Queued means that the class is on the priority queue and dispatching loop will eventually pick it up from there. When false this means that the class is not on the handles list. The bit protects the class from being enqueued more than once.
Dequeueing (called popping) has a trickery -- it can only happen on the class that's on top of the dispatch queue. That's because the dispatch queue queue is std::priority_queue which doesn't have random access eraser call, but only have the .pop() one.
Plugged bit is controlled by the bandwidth throttler. When the class runs out of its throttling tokens, it's unplugged. When it replenishes the necessary amount of tokens backm, it's plugged back. Currently, unplugging the class also …
=> fair_queue: Do not pop unplugged class immediately

include/seastar/net/tcp.hh
I have fixed an issue in the TCP protocol stack related to the "connect" phase. Now, it will be modified to determine whether to randomly generate a port that can be hashed to the current core based on smp::count. This resolves the TCP connect failure issue occurring in my environment.
=> net/tcp: generate a random src_port hashed to current shard if smp::count > 1

tests/perf/perf_tests.cc
Auto caluclate the maximum needed size of the name column in the perf
tests.
This avoids garbled output like the following:
```
stephan@rp:/build/seastar/build/release$ ./tests/perf/rpc_perf -i 10 --md-output /tmp/seastar.md 2>&1  | grep -v -i -E "reactor stalled|kernel callstack"
INFO  2024-02-21 12:18:01,631 seastar - Reactor backend: io_uring
single run iterations:    10
single run duration:      1.000s
number of runs:           5
number of cores:          32
random seed:              62032321
test                                      iterations      median         mad         min         max      allocs       tasks        inst
lz4.small_random_buffer_compress                  10   151.400ns     0.100ns   150.800ns   151.500ns       1.000       0.000      2198.0 …
```
=> perf: Calculate length of name column in perf tests

scripts/addr2line.py, scripts/stall-analyser.py
this series intends to cleanup stall-analyser by removing more global variables. and cache the results of resolve_address() for better performance.
=> stall-analyser: cleanups and cache the results of resolve_address() 

scripts/perftune.py
Add a long waited support for VLAN interfaces.
Tested manually with:
* bond interface on top of a physical device
* bond interface on top of another bond interface
* VLAN interface on top of a physical device
* VLAN interface on top of a bond interface
=> perftune.py: add support for VLAN interfaces

include/seastar/core/preempt.hh, tests/unit/lowres_clock_test.cc
In [e0d515b6 reactor: poll less frequently in debug mode][1] reactor preemption logic in debug mode was changed to improve performance. It also introduced a problem causing `seastar::lowres_clock` to drift unbounded.
The code doc states that `sestar::lowres_clock` "is a monotonic clock with a granularity of ~task_quota". We want that claim to be respected.
To achieve that we change the `scheduler_need_preempt` to respect the preemption requests which are triggered e.g. when task quota is up.
[1]: https://github.com/scylladb/seastar/commit/e0d515b6cf96129cebdcbb1b031df90eb815e7fa
Closes https://github.com/scylladb/seastar/issues/2238
=> reactor: respect preempt requests in debug mode

include/seastar/http/reply.hh, src/http/reply.cc
Add new http response codes to satisfy scylladb needs for S3 error handling
fixes: #2466
=> Add new http response codes

src/net/dns.cc
c-ares marked `ares_process()` deprecated in 1.28.1
in this change, we use `ares_process_fd()` in favor of the deprecated `ares_process()`.
Refs #2197
=> dns: use undeprecated c-ares API

doc/testing.md
References:
- https://github.com/scylladb/scylladb/commit/4cf4b7d4ef82
- https://github.com/scylladb/scylladb/commit/153279dbfa19
=> doc/testing.md: explain seastar + boost test colocation

src/core/file.cc
make_file_impl is marked noexcept but append_challenged_posix_file_impl constructor can throw and it does. std::terminate occurs. let's catch, then wrap into exceptional future.
=> file: unexpected throw from inside noexcept

demos/tls_echo_server_demo.cc
Replace deprecated at_exit() with the recommended seastar::async + defer() pattern.
This change:
- Upgrades from deprecated app.run_deprecated() to app.run()
- Implements proper shutdown handling with stop_signal
- Uses deferred_stop() for RAII-based service shutdown
- Replaces smart pointer with plain sharded service value
The demo now follows current Seastar best practices for initialization, resource management, and graceful termination.
Ref eefe659521. which deprecated `at_exit()`.
=> demos/tls_echo_server_demo: Modernize with seastar::async

src/core/reactor.cc
There's a bunch of trace log messages in seastar CPU scheduler that are compiled-out all the time, to turn them on one need to patch the sched_debug() method in the code and re-compile seastar. It looks like this debugging hasn't been in use for years already, so just drop it.
=> reactor: Remove sched_debug() related code

tests/unit/httpd_test.cc
In the HTTP parser in the test, `last == '\0'` means "start of header" or "start of chunk". But '\0' can appear in the body, breaking the parser's logic.
One of the tests in httpd_test sends an uninitialized buffer to this parser. Due to a coincidence of implementation details, this buffer usually doesn't contain NUL bytes.
But I recently made a completely unrelated change in the reactor which moved this uninitialized buffer to an allocator slot which does have NUL bytes, and the test started hanging (as I later learned, in this parser) for no reason.
=> tests/unit/httpd_test: fix the handling of NUL bytes in the parser

include/seastar/core/future.hh
These assertions are very much on the hotpath, and in Redpanda, some of
our microbenchmarks had regressions from this change. Here's an example
microbenchmark: https://github.com/redpanda-data/redpanda/blob/dev/src/v/utils/tests/coro_bench.cc
Before this change:
```
[bench-wrapper] running benchmark : coro_rpbench_binary
[bench-wrapper] verbose=0, exec_in_shm=True, redirect_stderr=True
[bench-wrapper] rundir            : /dev/shm/vectorized_io
[bench-wrapper] command           : src/v/utils/tests/coro_rpbench_binary --blocked-reactor-notify-ms 2000000 --abort-on-seastar-bad-alloc -m1GiB -c1
single run iterations:    0
single run duration:      1.000s
number of runs:           5
number of cores:          1
random seed:              3258366462
test                               iterations …
```
=> future: downgrade asserts to debug mode only

apps/io_tester/io_tester.cc
When running jobs with large block size, the io-queue code may try to split requests behind the scenes. It's possible to prevent that, but the caller must at least know it took place.
=> io_tester: Show metrics about requests split

scripts/seastar-json2code.py
Currently the script generates only default constructor and copy constructor (and a helper copy-from-mapper-type constructor). In Scylla there are several places that try to std::move the generated-types objects around, but objects are silently copied anyway.
Add move constructor and copy-assignment operator so that moving takes effect where possible.
Compile-tested with Scylla.
=> json2code: Genrate move constructor and move-assignment operator

src/http/common.cc
When making an http request, the caller may put the body-writer lambda
on the request. Depending whether the content-legnth value is specified,
the client will choose either content_length data sink or chunked one.
The data sink implements two put()-s -- one for net::packet and the
other one for temporary_buffer. The former nowadays falls-back to its
"default" implementation which just translates the packet into temporary
buffer and calls the latter (see https://github.com/scylladb/seastar/commit/52eb05829b271984dd4c79dae940057e70c13c2c commit).
When put() into content-length data sink, the temporary buffer is copied
into the underlying (socket) output_stream by calling its bufferred
.write() method:
return _out.write(buf.get(), size) ...
This patch re-implements the packet overload of …
=> http/client: Zero-copy forward content-length body into the underlying stream

tests/perf/future_util_perf.cc
The test creates two tasks in distinct sched groups and makes them schedule() each other for certain amount of iterations.
It will be useful to measure if anything changed in nested sched groups, as well as it's a nice test on its own.
=> test/perf: Add context-switch measurer

apps/io_tester/io_tester.cc
Yet another useful metrics to have. So far it wasn't reported, because queue length (both disk and io-scheduler) are not counters or some static values. Queue lengths is constantly changing, so there's not one value for it to be reported. Capturing maximum is also not nice, because it will capture a (random) spike giving no idea about how disk was in fact saturated.
Having said all of that -- this patch collects disk queue lengths samples and reports median, p90 and maximum values of the set. Samples are collected 5 times a second not to disturb the jobs too much yet to collect enough samples.
=> io_tester: Collect and report disk queue length samples

src/core/reactor.cc
The do_with() makes it an immediate win, though the real win is readability.
=> reactor: coroutinize spawn()

src/core/reactor.cc
If the reactor is stopping it raises the _stopping flag. Main loop, when sees that, wrap things up and breaks. The "wrap things up" code looks better outside of the loop.
=> reactor: Move stopping activity out of main loop

src/http/response_parser.rl
Add missing `#pragma once` to response_parser.rl
=> Add missing `#pragma once` to response_parser.rl

src/core/file.cc, tests/unit/directory_test.cc
There are two experimental yielding listers in file.cc -- the posix lister [1] that reads directory and co_yield-s entries, and the fallback yielding lister [2] that implements yielding lister on top of existing seastar::stream-based one. Added by respectively 95a7ff9989 (file: Add co_yield-ing list_directory() method) and 087dddf9ce (file: Add fallback generator implementation).
In case caller doesn't co_await for the lister until it EOFs, the generator is freed but fallback's background fibers are left behind causing use-after-free of the on-stack stuff. Despite it was suspected (#2190) that the memory is leaked by the generator code, it's not -- it _is_ destructed freed correctly, but the fiber is not kicked and continues pushing more entries into the queue.
The fix is in arming a …
=> Correctly wrap up abandoned yielding directory lister

src/net/posix-stack.cc
=> net: Use future::then_unpack() helper to unpack tuples
