- include/seastar/http/httpd.hh
- include/seastar/http/request.hh
- src/http/httpd.cc
This series adds https support to the http-server.
to use https, the http-server should use tls credentials before calling its listen method.
The series also changed the protocol name in the request, so that when the server uses https the protocol in the request will be set to https.
> http server: https using tls support

- src/util/log.cc
- tests/unit/exception_logging_test.cc
After multiple attempts nested_exception logging is still not robust.
In particular if std::system_error appears in the middle on the nested
exception chain the logging will break and very important information
(e.g. the object that initiated the exception chain) is going to be lost.
This patch is going to syntactically split the "printing part" of the
operator<<(exception_ptr) and the recursion part where we unroll
the std::nested_exception object.
As a result it's going to become much harder to break this code in the
future.
Signed-off-by: Vlad Zolotarov <vladz@scylladb.com>
> utils/log.cc: fix nested_exception logging (again)

- scripts/seastar-addr2line
- tests/unit/exception_logging_test.cc
Move splitting of the processed line to BacktraceResolver.__call__
so that it can match all the addressed on a single line
(that might be prefixed by non-address text).
Define BacktraceParser to categorize each line
as either None, SEPARATOR, or ADDRESS and return
the parsed results in a dictionary containing
the type, and for ADDRESS: an optional prefix and one or more addresses,
each represented by a dictionary containing optional path, and
an address.
If a line contains multiple addresses, it is considred as a complete
backtrace, hence it first prints the current backtrace (if any)
and prints one immediately after processing the line.
In addition, a self-test was added, that runs the BacktraceParser
and a bunch of possible lines and verifies the expected result.
Fix #892
Signed-off-by: …
> seastar-addr2line: support oneline backtrace in resolve call

- include/seastar/core/metrics.hh
- src/core/metrics.cc
- src/core/prometheus.cc
- src/core/scollectd.cc
prometheus: to_str(metric_value): fix conversion type for COUNTER and DERIVE
It looks like they got reversed.
Be consistent with metrics::impl::data_type documentation:
```
enum class data_type : uint8_t {
COUNTER, // unsigned int 64
GAUGE, // double
DERIVE, // signed int 64
ABSOLUTE, // unsigned int 64
HISTOGRAM,
};
```
Fixes #899 
Test: heat_weighted_load_balancing_test.py:HeatWeightedLB.heat_weighted_load_balancing_cl_TWO_test(debug)
Verified that node logs show no ubsan errors not the added conversion warning.
> metrics: Fix dtest->ulong conversion error

- include/seastar/json/formatter.hh
- src/json/formatter.cc
- tests/unit/json_formatter_test.cc
Background: until now strings in JSON were only quoted, not escaped, as noted by @nyh here: https://github.com/scylladb/seastar/issues/460#issuecomment-1038855017 . This resulted in problems like https://github.com/scylladb/scylla/issues/9061
The code for escaping was based on https://github.com/scylladb/scylla/blob/69fcc053bbb9156b8b88116a8dc8cc976148d86d/cql3/type_json.cc#L31 - just adapted to work on `string_view`s.
Also, the overload `formatter::to_json(const char*)` was marked as deprecated in Doxygen, because it would drop the contents following the first `\0` (and having `\0`s in the middle of a JSON is a valid practice). Scylla is not ready yet for the in-code `[[deprecated]]` attribute.
Fixes #460
> json/formatter: Escape strings

- CONTRIBUTING.md
This is a self-validating change by submitting the update to the guidance itself in a pull request :-)
@psarna mentioned that pull requests are an option for submitting seastar changes (https://github.com/redpanda-data/seastar/pull/18#issuecomment-1085487553), and it looks like quite a few have been accepted recently, so let's update CONTRIBUTING to reflect that.
Signed-off-by: John Spray <jcs@redpanda.com>
> CONTRIBUTING: update to note that pull requests are accepted

- include/seastar/core/abort_source.hh
This series turns undefined-behavior due to dereferencing a disengaged optional _subscriptions list
into terminate() if and when std::bad_optional_access is thrown when accessing that optional member the second time.
Also, it prevents a potential UB in boost::intrusive code in case the abort handler of one subscription happens to unlink the next subscription in the list.
Refs https://github.com/scylladb/scylla/issues/10668
> abort_source: assert request_abort called exactly once

- include/seastar/core/sharded.hh
Currently, func is copied in one of the invoke_on_all overloadeds,
but there does not seem to be any reason this should not be
a move instead. The difference is significant when func has captured
a large, moveable object.
See also redpanda-data/redpanda#5137 where an OOM passed
though this unexpected copy.
> Move function in invoke_on_all

- src/testing/test_runner.cc
We've seen cases like
https://github.com/scylladb/scylla/issues/10830#issuecomment-1158899187
where the "random-seed=" message was missing from test logs
after an early-stage error.
I suspect ths happened since stdout wasn't flushed on
UndefinedBehaviorSanitizer termination.
This change converts '\n' printed to the logs
(std::cout or std::cerr) with std::endl, that
behaves as follows: (see https://en.cppreference.com/w/cpp/io/manip/endl)
> Inserts a newline character into the output sequence os and flushes it
> test_runner: use std::endl to ensure messages are flushed

- include/seastar/core/posix.hh
- src/core/reactor.cc
`recv` has a slight performance advantage over the more generic `read`. Seastar is already using `send` instead of `write` on the transmit side. 
N.B. I had to change the return type from `ssize_t` to `size_t` in posix.hh to get it working.
> Use RECV syscall instead of READ in do_read_some()

- src/net/tls.cc
Otherwise, we overwrite an exceptional future as seen in
https://github.com/scylladb/scylla/issues/10127
Not handling the _output_pending failure is an
internal error, as confirmed by Carl Wilund <calle@scylladb.com>
so call on_internal_error to throw / abort if configured so.
> net/tls: vec_push: call on_internal_error if _output_pending already failed

- include/seastar/core/metrics.hh
- include/seastar/core/metrics_api.hh
- src/core/metrics.cc
- src/core/prometheus.cc
Motivation:
Histograms are the Prometheus killer. They are big to send over the
network and are big to store in Prometheus.
Histograms' size is always an issue, but with Seastar, it becomes even trickier.
Typically, each shard would collect its histograms, so the overall data
is multiplied by the number of shards.
This series addresses the need to report quantile information like latency
without generating massive metrics reports.
A summary is a Prometheus metric type that holds a quantile summary (i.e.
p95, p99).
The downside of summaries is that they cannot be aggregated, which is 
needed for a distributed system (i.e., calculate the p99 latency of a cluster).
The series adds four tools for Prometheus performance:
1. Add summaries.
2. Optionally, remove empty metrics. It's common to …
> Prometheus enhancement

- src/core/on_internal_error.cc
We don't know if the exception thrown by `on_internal_error` (if we're
not aborting) will propagate to the top-level and/or will be logged.
It's still valuable to log the error immediately when
`on_internal_error` is called.
> core: log in on_internal_error even when throwing

- include/seastar/coroutine/exception.hh
- tests/unit/coroutines_test.cc
Currently, make_exception/return_exception call
std::make_exception_ptr unconditionally.
When called over a std::exception_ptr, std::make_exception_ptr
loses the arg's exception type and creates an untyped
exception_ptr.
Instead, use a templated constructor for struct exception
that just moves the given exception_ptr into its member
to retain its type.  It's also a bit more efficient
since it save the construction of a new exception ptr
and one move of it (into the constructor's parameter).
Added a respective unit test.
> coroutine: exception: retain exception_ptr type

- src/net/tls.cc
- src/util/short_streams.cc
I failed to build seastar with the option `Seastar_SSTRING=OFF`
> sstring: restore compatibility with std::string

- include/seastar/core/future.hh
- include/seastar/core/sstring.hh
Gcc 12.1.1 discovers what it thinks are two bugs in Seastar and warns about them  - breaking the build.
But in fact both cases are deliberate choices which we made in our implementation, and are correct. 
So we need to use "pragma"s to tell Gcc that these are in fact correct.
After these two patches, Seastar can be built with Gcc on Fedora 36 (with clang, it already worked).
Fixes #1116
> Avoid false-positive warnings in Gcc 12.1.1

- include/seastar/coroutine/exception.hh
Following up on 1b07c80c978d21660179d911c68bd338337a59cb,
it is still possible to silently call coroutine::return_exception
with an exception_ptr, rather than calling
coroutine::return_exception_ptr.
This will cause the passed exception_ptr to be wrapped
in yet another exception_ptr so it effectively loses its type
(i.e. it won't be caught properly with:
try {
std::rethrow_exception(ex);
} catch (some_exception& e)
since the rethrown exception type is no std::exception_ptr.
To encourage the proper use of coroutine::return_exception_ptr,
deprecate coroutine::return_exception(std::exception_ptr)
and instruct the caller to use coroutine::return_exception_ptr
instead.
> coroutine: exception: deprecate return_exception(exception_ptr)

- include/seastar/core/task.hh
- tests/unit/coroutines_test.cc
When seastar::internal::coroutine_traits_base\<T\> was instantiated, a compiler
error occured because coroutine_traits_base\<T\>::promise_type::set_scheduling_group
method accessed private member _sg of promise_type's base class seastar::task.
Variable member _sg of type scheduling_group in seastar::task accessed
in derived class has its access specifier changed to protected.
Fixes: #1142
> coroutine: change access specifier of seastar::task member

- include/seastar/core/io_intent.hh
neither of these headers is used in this header file. and neither
is `bi` namespace alias used.
so in this change, the unused headers and unused namespace alias
are removed.
> intent: drop unused headers

- cmake/FindValgrind.cmake
we should attach INTERFACE_INCLUDE_DIRECTORIES to Valgrind::valgrind
not to hwloc::hwloc.
> cmake: attach property to Valgrind not to hwloc

- include/seastar/util/program-options.hh
before this change, we have to pass a valid candidate value for
selection_value, otherwise `find_candidate()` would throw as it
cannot find a matched `_selected_candidate` if none of the name
of candidates is empty.
but this restriction leaves us no option, if we want to have an
optional selection_value.
in this change, the constructor of
`selection_value(option_group&, std::string name, candidates, std::string description)`
does not delegate to
`selection_value(option_group&, std::string name, candidates,
std::string default_candidate, std::string description)` with
an empty `default_candiate` anymore. instead, it leave
`_selected_candidate` to its in-class initializer. so it is
`no_selected_candidate` in that case. and we can just tell if
the `selection_value` is set or not as we do to …
> program_options: enable optional selection_value

- src/net/tls.cc
This series deals with handling of async errors in vec_push _output_pending.
First, `handle_output_error` is called in `do_handshake` before calling `send_alert`, fixing #1180
and on top, the "unhandled error" internal error in vec_push was demoted and is just reported and returned back, since it was determined that it can be hit by normal circumstances when _output_pending fails in background and gnutls is calling vec_push a number of times in a row. This fixes #1181.
debug logging and and error injection test that reproduces the above issue without the fix were also added.
Refs https://github.com/scylladb/scylladb/issues/11252
> tls: vec_push: handle async errors rather than throwing on_internal_error

- include/seastar/core/on_internal_error.hh
- include/seastar/core/shared_ptr_debug_helper.hh
- src/core/on_internal_error.cc
Add `on_internal_error_abort` that prints the internal error log message and aborts unconditionally.
It allows the caller to log more information than what would have been printed just from the failed assert.
In addition, use it in the `shared_ptr_debug_helper` to replace the assert call, that is not useful in debug runs since the address sanitizer obfuscates the assert backtrace.
Fixes #1095
> shared_ptr_debug_helper: turn assert into on_internal_error_abort

- include/seastar/core/smp_options.hh
- src/core/reactor.cc
This option is targeted at small utility/tool applications, which don't want to use the seastar allocator, as they don't want to commit to a fixed amount of memory to be used. Any amount they might commit to would be both too small and too large at the same time: we want to let them consume as much as they need and only as much instead. This option is not exposed on the command line, it can only be set from code. This is intentional: the application code has to be well prepared for the choice of allocator, this is not something a user can select at whim on the command line, this is a decision that only developers can make (with care).
> memory: allow user to select allocator to be used at runtime

- include/seastar/net/inet_address.hh
- src/net/inet_address.cc
- tests/unit/network_interface_test.cc
IPv4 loopback address is 127.0.0.0/8
IPv4 any address is 0.0.0.0
IPv6 loopback address is ::1
IPv6 any address is ::
Sanity unit test included.
> inet_address: Add helper to check for address being lo/any

- include/seastar/util/program-options.hh
before this change, a `program_options::value<>` cannot be configured programmatically. if we configure a switch option and then mutate an `program_options::option_group` with this option, the switch option is always reset if the mutator does not contain that option even we set that option with a default value beforehand.
after this change, `program_options::value<>` tracks its value with an `optional<bool>` like the other specialization `program_options::value<T>`. so its value is overriden only if it is not preset. this allows us to configure switch-style options programmatically. so its behavior is more consistent with other `program_options::value<T>`.
> program_options: allow configure switch-stytle option programmatically

- include/seastar/util/closeable.hh
- tests/unit/closeable_test.cc
before this change, if we move from a deferred_stop, when the original
instance is destructed, the obj referenced by it is always stopped if
the deferred_stop is not canceled. and the new instance of deferred_stop
also stops the referenced object when it is destroyed. but developer
would expect the obj is stopped only once, and should be stopped by the
new deferred_stop instance. this behavior is surprising when developer
intentially capture the deferred_stop instance by move and store it in
a local variable.
in this change,
* a move ctor is added for deferred_stop, so that the original
instance is always canceled.
* a test is added accordingly.
please note, as a side effect, the default copy ctor is deleted. this is
expected. as deferred_stop should not be copiable. this might break …
> util/closeable: add move ctor for deferred_stop

- src/core/reactor_backend.cc
there is no need to have an array of `io_uring_cqe*` on the stack. as the output parameter of `sqe` will simply point to the start address of the shared ringbuffer of sq if the `io_uring_wait_cqes()` completes. we could use it to construct a `std::span<io_uring_cqe>` though.
> reactor: pass a plain pointer to io_uring_wait_cqes()

- include/seastar/core/reactor.hh
- src/core/reactor.cc
When called with an invalid sg (e.g. a previously destroyed one) with_scheduling_group segfaults when dereferencing _task_queues[sg._id] which is nullified by destroy_scheduling_group.
To prevent that, verify first the the sg is valid, and abort after calling on_internal_error_noexcept otherwise. return an exceptional future in debug mode to enable a unit test.
While at it, also mark the method noexcept.
Added a debug unit tests to verify the returned exception when re-destorying a scheduling_group or when destroying an invalid scheduling_group.
This PR is companion to https://github.com/scylladb/seastar/pull/1229
v1 was sent to the mailing list.
In v2 (978d46eeb4e4d29173d35be27299a967a2349441):
- call on_internal_error_noexcept and abort …
> reactor: destroy_scheduling_group: make sure scheduling_group is valid

- include/seastar/core/future.hh
fix the commented-out concept and enable it. for better developer experience, and also serves as a document for the `Func` type.
> future: add concept constraints to handle_exception()

- include/seastar/core/io_queue.hh
- include/seastar/core/smp_options.hh
- src/core/reactor.cc
The concept of limiting only the number of requests was replaced more than two years ago, the CLI option was deprecated 1+ year ago. It should be safe to eliminate it altogether now
> Remove deprecated --max-io-requests

- src/core/reactor_backend.cc
* drop `protected` from `reactor_backend_uring` class
* implement read_some(fd, buffer, len) in io_uring
> reactor: implement read_some(fd, buffer, len) in io_uring and a cleanup

- include/seastar/core/future.hh
otherwise this function would be considered as not declared.
> future: s/make_exception_ptr/std::make_exception_ptr/

- src/net/dns.cc
- tests/unit/dns_test.cc
Fixes #1244
Iff a TCP mode ARES socket connection fails, we don't get a socket in the socket struct for the virtual fd. As the connect function cannot fail at this point (engine::connect completion), we can only set all poll flags and wake up the select emulation we are running.
Here we expect to detect the error in the upcoming sendv call, we however do not check this field being fully initialized -> crash.
Simple fix,. just verify field, if not inited, return ENOTCONN.
> dns: Handle TCP mode connect failure

- HACKING.md
This adds an instruction to pull git submodules before invoking `cmake-cooking` to avoid the footgun described in #541.
> Add git submodule instructions to HACKING.md, resolves #541

- src/core/reactor_backend.cc
before this change, we advance the head pointer of cq by 1 after process each cqe.
after this change, we advance the head pointer after done with all cqes.
because `io_uring_cqe_seen()` is implemented using `io_uring_cq_advance()` which in turn effectively calls `atomic::store(new_head, std::memory_order::release)`. so less calls of `io_uring_cqe_seen()` would incurs less write memory barriers put on in the execution path. so this change should help improve the performance a little bit.
> reactor: advance the head pointer in batch

- include/seastar/rpc/rpc.hh
Nested classes have access to private and protected fields of the enclosing class, no need in explicit friendship
> rpc: Remove nested class friend declaration from connection

- include/seastar/core/internal/pollable_fd.hh
- src/core/reactor_backend.cc
* internal/pollable_fd.hh: add `friend class reactor_backend_uring` to `pollable_fd_state`, so `reactor_backend_uring::accept()` is able to call `pollable_fd_state::maybe_no_more_recv()`.
* core/reactor_backend.cc: implement `reactor_backend_uring::accept()` and `reactor_backend_uring::connect()` with io_uring ops.
so we can accept and connect connections with io_uring. hopefully, this would help us get better performance on newer kernels.
`reactor_backend_uring::accept()` follows the model of `reactor::do_accept()` -- it has the same speculation on the possible use cases and reasoning.
> reactor: add accept and connect to io_uring backend

- include/seastar/testing/seastar_test.hh
- include/seastar/testing/test_case.hh
- include/seastar/testing/thread_test_case.hh
- tests/unit/thread_test.cc
The global (namespace scope) objects created by SEASTAR_TEST_CASE and related macros are stateless objects: their only purpose is to hold a vtable for overridden methods from seastar_test.
This means the base class methods and the object itself can be const.
This allows it to be allocated in .rodata (very minor benefit) and silences (valid?) clang-tidy warnings about non-const global objects.
> Use const test objects

- src/core/file.cc
There are 3 layers "around" the file API:
- public calls
- ..._impl private calls
- file_impl pointer
Few calls from the ..._impl one call back the public calls because this is what they really wnat to do. This violates the layering (theory) and makes deprecation of public io_priority_class harder (practice). The fix is in making ..._impl calls call the other ..._impl calls.
tests: unit(dev), scylla.unit(dev)
> file: Dont violate API layering

- include/seastar/testing/test_case.hh
- include/seastar/testing/thread_test_case.hh
Disable clang-tidy check cert-err58-cpp in SEASTAR_TEST_CASE and related macros. This check complains about a possibly-throwing (i.e., not noexcept) constructor for global objects. We create such an object for each test case. Since the constructor can throw (in the unlikely event of a memory allocation failure) we simply disbale the warning for these global objects using NOLINT.
In any case, if these objects throw, the process will be terminated which is an appropriate action for a memory allocation failure at startup.
> Add NOLINT for cert-err58-cpp

- include/seastar/core/smp.hh
- src/core/smp.cc
Verify that the smp_service_group id to be destroyed
is valid, otherwise we end up with clearing a vector
in an arbitrary position in memory.
call on_internal_error_noexcept if the ssg id is invalid.
Also, added a unit test for that.
v2 of this patch was sent to the mailing list.
In v3 (430916ad4ba2394eed9ff85c151d544300d35f56):
- added "smp: add validate_smp_service_group"
> smp: destroy_smp_service_group: verify smp_service_group id

- include/seastar/core/iostream.hh
`output_stream::possibly_available()` is not used since long ago. let's just ditch it.
> iostream: remove unused function

- cooking_recipe.cmake
before this change, liburing.pc is not installed if we configure the building system using `./configure ... --cooking liburing` and expect that CMake will find liburing. but in fact, CMake will reject the found liburing and continue without liburing enabled, as the found liburing package is missing version string.
after this change, we install liburing in its top source directory, so liburing.pc is also installed in addition to its header files and compiled library.
> build: install liburing.pc using stow

- README-DPDK.md
it is required to build dpdk with cooking.sh
Fixes #1216
> README-DPDK.md: document --cflags option

- include/seastar/core/shared_mutex.hh
- tests/unit/locking_test.cc
Currently, exceptions in templates for functions that may
throw on move are handled in a generic way using
current_exception_as_future().
But if the passed functor returns a value, we need
to use current_exception_as_future<value_type> instead
so the error-free and error case returned future type
will match.
This change fixes that and adds unit test reproducers.
Fixes https://github.com/scylladb/seastar/issues/1295
> shared_mutex: return typed exceptional future in with_* error handlers

- CMakeLists.txt
- include/seastar/core/reactor.hh
- include/seastar/core/seastar.hh
- include/seastar/util/process.hh
- src/core/reactor.cc
- src/util/process.cc
- tests/unit/CMakeLists.txt
- tests/unit/spawn_test.cc
So we can spawn a subprocess with Seastar.
In our use case, Seastar is used to implement a distributed service.
Before the daemon boots and joins the cluster, it calls an external
script to determine the host's location in the network topology and
failure domain settings, and attaches these information in its RPC
request for joining the cluster sent to the cluster management nodes.
The script can be customized by user so he/she can define their own
deployment policy, as long as the script is an executable and outputs
in the format that can be parsed by the daemon calling the script.
This is a convenient way allowing user to customize the daemon's
behavior without introducing yet another RPC service or a plugin
system.
> util, core: add spawn_process() helper

- cmake/FindLibUring.cmake
* use URING_PC as the prefix passed to pkg_search_module()
* use LibUring_FOUND when checking if LibUring is found. as this is the
"FOUND_VAR" used by `find_package_handle_standard_args()`, and hence
should be used as the authentic indicator.
without this change, if `pkg_search_module(URING liburing)` finds a
liburing with lower version than specified version, it is still accepted
as long as `pkg_search_module()` is able to find any liburing.pc. as
`URING_FOUND` is used as the indicator of the existence of the qualified
liburing library.
after this change, the `URING_PC` is used instead of `URING`. so
`find_package(LibUring...)` can do its job and find liburing if its
.pc file is found and its version is greater than 2.0. and
`LibUring_FOUND` is used so we don't accept liburing with …
> build: use correct version when finding liburing

- src/net/dns.cc
- tests/unit/dns_test.cc
Fixes #1285
Running N UDP queries at the same time (to same server) will cause multiple UDP packets being sent on the
associated UDP channel, but we don't enforce the pending send has actually completed (as in been written to wire),
and since seastar sockets cannot handle overlapping sends, this will break the mechanism.
This is because C-ares does not check for non-blocking EAGAIN state for UDP (long standing fixme in C-ares).
Need to serialize UDP sends internally. 
Test included
v2: 
* Simplified solution to an always-future-chain for UDP.
* Added use/release for all send calls across either immediate or continuation to be extra paranoid of a dropped socket (from c-ares call).
> dns: serialize UDP sends.

- cmake/FindSourceLocation.cmake
- cmake/code_tests/Source_location_default_argument.cc
CWG 2631 (https://cplusplus.github.io/CWG/issues/2631.html) reports an issue on how the default argument is evaluated. this problem is more obvious when it comes to how `std::source_location::current()` is evaluated as a default argument. but not all compilers have the same behavior, see https://godbolt.org/z/PK865KdG4.
notebaly, clang-15 evaluates the default argument at the callee site. so we need to check the capability of compiler and fall back to the one defined by util/source_location-compat.hh if the compiler suffers from CWG 2631.
in this change, FindSourceLocation.cmake is reused for checking the behavior of compiler by adding a new test which fails if the expected line number is different from the one returned by `std::source_location::current()`.
Signed-off-by: Kefu Chai …
> build: check for fix of CWG2631

- .circleci/config.yml
- docker/dev/Dockerfile
since we only support the latest two major releases of compilers. at the moment of writing, Clang just released v15, and the latest major release of GCC is v12.
so we should install them respectively.
because ubuntu jammy does not ship clang-15. we need to bump up the base image from ubuntu:jammy to ubuntu:kinetic despite that kinetic is not an LTS release. we should use ubuntu 24.04 once it's out.
[avi: squash related circleci change, regenerate toolchain,
and use versioned image tag instead of :latest]
> docker: bump up to clang {14,15} and gcc {11,12}

- include/seastar/coroutine/parallel_for_each.hh
* s/in paralell/in parallel/
* in general, "one or more of the function invocations" should be considered as a plurial, and hence should be followed with a plural verb.
> coroutine: correct syntax error in doxygen comment

- include/seastar/core/abort_source.hh
- tests/unit/abort_source_test.cc
calling `node_algorithms::unlink(this_ptr())` with an engaged subscription results in use-after-free that is reproduced by the added unit test.
Fixes #1336
> abort_source: move-assign operator: call base class unlink

- scripts/addr2line.py
- scripts/seastar-addr2line
Since clang 14
(llvm/llvm-project@edd2b99a57c127dc3d99fe7550d69a113de53eb0), the BuildID information is printed on each line.
Let the respective regular expression
match that too and add a test case for it.
> addr2line: extend asan regex

- CMakeLists.txt
- cmake/FindGnuTLS.cmake
- bump up required cmake version to 3.13
- using `pkg_search_module(.. IMPORTED_TARGET ..)` to find GnuTLS
> build: find library using pkg_search_module(.. IMPORTED_TARGET ..) 

- include/seastar/core/internal/pollable_fd.hh
- include/seastar/core/reactor.hh
- include/seastar/net/api.hh
- include/seastar/net/stack.hh
- include/seastar/net/tcp.hh
- src/core/reactor.cc
- src/core/reactor_backend.cc
- src/core/reactor_backend.hh
- src/net/native-stack-impl.hh
- src/net/posix-stack.cc
- src/net/stack.cc
- src/net/tls.cc
- tests/unit/loopback_socket.hh
- tests/unit/socket_test.cc
This patch adds the connected_socket::wait_closed() call that returns a future that resolves when the connection is terminated by the peer or when the local socket is shutdown for reading. This event can be waited on even if a client doesn't read from (or write to) its end while server SUDDENLY closes it.
This can be useful for keep-alive HTTP sockets. When a client session is created and a request is served, client may want to cache the connected socket without sending new requrests right at once, but still needs to know if the server recycles the connection on his side.
Implementation depends on the socket type (and reactor backend)
- Posix socket
There's a useful polling event in the Linux called POLLRDHUP which is reported when socket is shutdown(SHUT_RD) or peer of the connection …
> sockets: Wait on socket peer closing the connection

- include/seastar/http/reply.hh
- src/http/client.cc
- src/http/reply.cc
- tests/unit/httpd_test.cc
When receiving and parsing a reply from server it's good to have the content length as integer, not as header string.
> http: Carry integer content_length on reply

- include/seastar/http/reply.hh
- src/http/reply.cc
S3 GET with Range header results in 206 status code. This one is absent in seastar enum class, but it's good to have it.
> http: Add 206 Partial Content response code

- cmake/Findc-ares.cmake
otherwise the linker would not be able to find the library using ${c-ares_LIBRARY} reported by pkgconfig. the former is just "cares". so the command line would look like:
clang++ ... cares ...
and it fails to link like:
clang-15: error: no such file or directory: 'cares'
if a target links against ${c-ares_LIBRARY}, it would fail to link after 27c2d888e682ecb1d312fa123a88dd2f55745510. the offending change does not impact the target which links against c-ares::cares.
> build: get the full path of c-ares

- include/seastar/core/chunked_fifo.hh
- tests/unit/chunked_fifo_test.cc
Need to be using `basic_iterator<const T>` rather than `basic_iterator<T>`
Otherwise, we get the following compilation error:
```
/home/bhalevy/dev/seastar/include/seastar/core/chunked_fifo.hh:164:15: error: using declaration refers into 'basic_iterator<int>::', which is not a base class of 'const_iterator'
using basic_iterator<T>::basic_iterator;
^~~~~~~~~~~~~~~~~~~
```
Added a unit test that doesn't build without the fix.
> chunked_fifo: const_iterator: use the base class ctor

- include/seastar/core/shared_ptr.hh
so we are able to format, for instance, seastar::shared_ptr<T>, with
seastar::shared_ptr<int> p;
auto s = fmt::format("{}", fmt::ptr(p));
> shared_ptr: add specializations for fmt::ptr()

- cooking_recipe.cmake
- build: bump fmtlib to 9.1.0 in cooking_recipe
- build: bump boost to 1.81.0 in cooking_recipe
- build: bump cryptopp to 8.7.0 in cooking_recipe
> build: bump up fmtlib, boost and cryptopp in cooking_recipe

- cooking_recipe.cmake
before this change,
* only the headers and the executable for testing are installed.
* CMAKE_CXX_FLAGS are not used when building cryptopp
these have two sequences:
* the static library are not installed, so the cooked library cannot be picked up by find_package(..)
* if we want to pass, for instance, '-stdlib=libc++' as the CXXFLAGS, when building Seastar, it won't be used, and libstdc++ is used. this would cause link failure, as libstdc++ and libc++ are not ABI compatible.
after this change,
* the "static" target is built before "install-lib" is built.
* the CMAKE_CXX_FLAGS are used,as GNUmake uses CXXFLAGS variable implicitly when building targets.
> build: build static library of cryptopp

- include/seastar/util/noncopyable_function.hh
In its current form it looks as if it could construct n.c.f. from pretty much anything, but in reality it's more strict.
> noncopyable_function: Add concept for (Func func) constructor

- include/seastar/core/shared_ptr.hh
- tests/unit/shared_ptr_test.cc
Otherwise compiling lw_shared_ptr<T> == nullptr_t fails:
error: use of overloaded operator '==' is ambiguous (with operand types 'const seastar::lw_shared_ptr<int>' and 'const std::nullptr_t')
return left == right;
~~~~ ^  ~~~~~
note: candidate function
bool operator==(const lw_shared_ptr<const T>& x) const {
^
note: candidate function
bool operator==(const lw_shared_ptr<std::remove_const_t<T>>& x) const {
^
Same for operator!=, c++17 doesn't generate it from == one. Compilation test included (and for shared_ptr too, it already works).
> lw_shared_ptr: Add nullptr_t comparing operators

- tests/unit/httpd_test.cc
- tests/unit/loopback_socket.hh
The factory generates connections between all shards in round-robin manner. However, http tests all start httpd server on shard-0 only. So any attempt to create and use (use is important, connect would be non-blocking in this case) more than one connection under test.py run would get stuck, because test.py launches tests on two shards.
Fix in advance.
> tests, httpd: Limit loopback connection factory sharding

- tests/unit/CMakeLists.txt
by default, openssl outputs "status dots" while generating keys. this is just distracting when building tests. so let's just run `openssl genpkey` in its quiet mode.
> build: silence the output when generating private keys

- CMakeLists.txt
this new option was introduced in CMake 3.24. and CMake 3.24 complains like:
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
if `cmake_policy(SET CMP0135 NEW)` is not specified explicitly, or `DOWNLOAD_EXTRACT_TIMESTAMP` is not specified when calling …
> build: specify CMake policy CMP0135 to new

- cooking_recipe.cmake
also, build the "static" target in the BUILD_COMMAND instead in INSTALL_COMMAND of cryptopp, for better readability, and more importantly, to ensure that "static" target is built *before* "install-lib", so that "install-lib" can find the built static library.
> build: use BUILD_IN_SOURCE instead chdir <SOURCE_DIR>

- CMakeLists.txt
we use seastar_generate_ragel() to generate the header files using ragel. and ragel outputs the generated header files under `${Seastar_GEN_BINARY_DIR}/include`. so we never write any source or header files into `${Seastar_GEN_BINARY_DIR}/src`.
in this change, the unused include directory is removed.
> build: drop unused target_include_directories()

- include/seastar/util/process.hh
file_desc is declared in core/posix.hh, so we need to include core/posix.hh explicitly in process.hh which references file_desc.
> util/process: include used header

- src/core/reactor_backend.cc
before this change, the io_uring backend fails to trim the returned buffer to the number of bytes actually received. so reactor_backend_uring::recv_some() could return a buffer with trailing garbage bits.
after this change, reactor_backend_uring::recv_some() always trims the trailing bits off the returned buffer, so the returned buffer is the bytes read from wire without uninitialized bits at its end.
Fixes: #1258
> reactor: trim returned buffer to received number of bytes

- src/core/reactor_backend.cc
> reactor: fix a typo in comment

- src/core/reactor_backend.cc
from functionality perspective, resize(0) is identical to clear(). but static_vector::resize(0) could use more CPU cycles than the latter. for instance, it compares the new size with the old size to determine if it should value-initialize the new elements if any. while clear() just nukes all the elements and set the new size to 0. it should be faster than resize(0). and more importantly, it has better readability.
> reactor: s/resize(0)/clear()/

- include/seastar/core/loop.hh
The concept requires iterators support postfix increment, but prefix increment is used in the implementation.
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
> parallel utils: align concept with implementation

- include/seastar/core/metrics.hh
to be more consistent on the coding style.
> metrics: add spaces around '='

- include/seastar/core/ragel.hh
- src/http/chunk_parsers.rl
- src/http/request_parser.rl
- src/http/response_parser.rl
`field_vchars` is intended to catch all graphical characters until the next space. But due to an ambiguity in the grammar, after each `(graph | obs_text)`, instead of following to the next character, the parser can instead choose to exit `field_vchars`, move to `sp_ht*`, consume 0 times sp_ht, and loop back to `field_vchars`. And in fact, this is what happens.
As a result, `checkpoint` is called after every character in a field value. This does not change the correctness of parsing, but is a serious performance problem, because it invokes the expensive `sstring::operator+` for each parsed character.
See https://github.com/scylladb/scylladb/pull/12445 for a discussion.
To break the ambiguity, we use ragel's state transition priority features.
> http: request_parser: fix grammar ambiguity in field_content

- CMakeLists.txt
before this change, the non-library targets are always disabled even if Seastar is embedded using `add_subdirectory()` and these targets are enabled with commands like:
set(Seastar_TESTING ON CACHE BOOL "" FORCE)
in the parent project. the value of `Seastar_TESTING` is overridden by Seastar.
but there are chances that the parent project still want to enable one or more of these targets. in this case, it'd be desirable to keep the value(s) set by the parent project.
after this change, instead of overriding the cached values, we provide the default value for them depending on if Seastar is a top-level project. So the parent project can now set the value of options like `Seastar_APPS`. and these values are preseved.
Fixes #1380
> build: enable non-library targets using default option value

- src/http/httpd.cc
This is a workaround for issue https://github.com/scylladb/seastar/issues/906 when using TLS connections to an httpd service.
Previously, https:// servers would fail to send a response whenever a client sent a "Connection: Close" HTTP/1.1 response.
This was hidden mostly by the case-sensitive parse of "Close", where typical clients send "close".  Commit c14f9315 fized the parsing to be case insensitive, which makes the underlying issue manifest. Previously we were mostly ignoring `Connection` headers.
> http: delay input stream close until responses sent

- include/seastar/core/reactor.hh
reactor::handle_aio_error() was dropped back in 12138b32ed387311cb01074e84e72fb9fecbe520
> reactor: drop unused member function declaration

- cmake/Findc-ares.cmake
before this change, we use "c-ares" as the prefix passed to `pkg_check_modules()` when checking c-ares package configurations. this sets c-ares_FOUND variable with PARENT_SCOPE, while we still add the `c-ares::cares` library target with the scope in the directory where the find_package(c-ares ..) is called and below. the scope follows the convention of Find<Package>.cmake modules provided by CMake project.
it is found that grpc project uses c-ares_FOUND before calling find_package(c-ares REQUIRED) for resolving its dependency, and skip the find_package() call if c-ares_FOUND is TRUE.
the discrepancy between the scopes of c-ares_FOUND and c-ares::cares can break the build of projects using both Seastar and the projects like grpc. as the parent project would fail to link against grpc …
> build: do not set c-ares_FOUND with PARENT_SCOPE

- apps/memcached/tests/CMakeLists.txt
this change is a follow-up of 338ba970d01973c0a7ab1bc03c050c55f37e39f7.
before this change, `${CMAKE_CURRENT_BINARY_DIR}` is used for Seastar_BINARY_DIR. if Seastar is a top-level project, the values of `${CMAKE_CURRENT_BINARY_DIR}` and `${CMAKE_BINARY_DIR}` are identical. but if Seastar is embedded in a parent project, `${CMAKE_BINARY_DIR}` would be somewhere like "bulid/seastar" where "build" is the build directory of the parent project. but we are still referencing the build directory with ${Seastar_BINARY_DIR} and issuing commands like
```
cmake --build ${Seastar_BINARY_DIR} --target ${target}
```
if this would fail as the build directory is not ${Seastar_BINARY_DIR} anymore. if the cmake generator is make, the failure would look like:
```
> gmake: *** No rule to make target …
```
> build: use ${CMAKE_BINARY_DIR} when running 'cmake --build ..'

- apps/io_tester/io_tester.cc
- demos/file_demo.cc
- tests/perf/rpc_perf.cc
- tests/unit/allocator_test.cc
- tests/unit/fstream_test.cc
- tests/unit/rpc_test.cc
`char` is not a supported type, and in particular is rejected by libc++-15. Change it to int and explicitly set the bounds where necessary.
This is a re-submission of https://github.com/scylladb/seastar/pull/1317 to see if this fixes the Circle CI issue.
cc @BenPope
> Use an integral type for uniform_int_distribution

- cmake/FindGnuTLS.cmake
- cmake/FindLibUring.cmake
- cmake/FindValgrind.cmake
- cmake/Findc-ares.cmake
- cmake/Findhwloc.cmake
- cmake/Findlz4.cmake
- cmake/Findyaml-cpp.cmake
* revert use pkg_search_module(.. IMPORTED_TARGET ..) changes
* pass QUIET to pkg_check_modules(). as FPHSA also prints out message when checking the required variables. and pkg_check_modules() only provides hints to `find_*()` functions.
* use `pkg_check_module()` instead of `pkg_search_module()`, as we don't "search" for a module in some candidates, we just want to check for a single one. `pkg_check_module()` reflects our intention here better.
before the change, `pkg_check_modules(..., IMPORTED_TARGET)` is used in find modules. but per the discussion at
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8037,
quote from CMake maintainer Brad King's comment:
> Actually, using `pkg_check_modules` with `IMPORTED_TARGET` is not
> a good pattern for find modules.  Instead, the …
> build: revert use pkg_search_module(.. IMPORTED_TARGET ..) changes

- src/core/reactor.cc
The help for dump_memory_diagnostics_on_alloc_failure_kind listed the options as:
never, critical (default), always
but the correct options (based on the enum name) are:
none, critical (default), all
Change the doc to match the enum.
> Fix CLI help for memory diagnostics dump

- include/seastar/core/sstring.hh
Currently, unordered maps are printed as: `{{ K0 -> V0}, { K1 -> V1}}`.
Instead, they should look like: `{{K0 -> V0}, {K1 -> V1}}`
> sstring: operator<< std::unordered_map: delete stray space char

- include/seastar/core/future.hh
- tests/unit/futures_test.cc
Currently, in future::schedule(), only _state
is moved to the continuation under SEASTAR_DEBUG
and this future might still be attached to a promise.
This trips an assert when the promise is destroyed,
calling promise::clear, where it observes _future
as engaged, while the promise._state was moved
into the contiuation, and the one that the promise
points to goes under move_it() which sets its state
to state::invalid, therefore it is considered as
`!_state->available()` in `promise_base::clear()`
and `set_to_broken_promise(*_state)` is called.
Next, state.set_exception is called, tripping:
`assert(_u.st == state::future);`
See following backtrace:
```
futures_test: /home/bhalevy/dev/seastar/include/seastar/core/future.hh:543: void seastar::future_state_base::set_exception(std::exception_ptr …
```
> future: schedule: get_available_state_ref under SEASTAR_DEBUG

- src/core/reactor_backend.cc
this change reverts https://github.com/tchaikov/seastar/commit/64480988a3dd531603e46010693f9a87baa9437c. per
our tests on linux 5.11.0, read op returns -EAGAIN even after
poll(EPOLLIN) with io_uring backend returns with an fd created using
`file_desc::inotify_init()`. this practically fails all tests in
fsnotifier_test.cc, and also some tests in tls_test.cc exercising
`reloadable_credentials`. as `reloadable_credentials` uses inotify
to watch the changes of the credential files.
but on newer kernel like linux 6.0, the io_uring backend works fine
with inotify. since inotify is not used in critical paths, we can
tolerate this hybrid implementation at this moment. and we can use
io_uring backend once the CircleCI is able to offer newer image with
newer linux kernel, and we need to bump up …
> reactor: use aio to implement reactor_backend_uring::read()

- tests/unit/connect_test.cc
before this change, 172.16.0.1:0 is used as a peer which is shutdown, this works fine when using aio as the backend. but unfortunately, when it comes to io_uring, if the fd in question is opened in blocking mode. the connect call is blocked forever. this behavior can be verified using liburing/test/connect.c after manually changing the IP address in this test from "127.0.0.1" to "172.16.0.1". if the fd is opened in non-blocking mode. 0 is returned in the cqe. hence the test of tests/unit/connect_test fails.
after this change, "172.16.0.1" is changed to "127.0.0.1", since 0 is not a valid TCP port for connection. we always have ECONNREFUSED.
this should help io_uring backend pass the tests/unit/connect_test test.
> tests: connect_test: use 127.0.0.1 for connect refused test

- apps/iotune/iotune.cc
simpler this way, and for better readability.
> apps/iotune: s/condition == false/!condition/

- include/seastar/core/bitops.hh
for better readability and better developer experience
> core/bitops.hh: add type constraits to templates

- CMakeLists.txt
before this change, we always populate the package registry by writing to CMake registry file in $HOME, like:
```
$HOME/.cmake/packages/Seastar/fa3ead70757accdda096b789d64bb1e0
```
as instructed by the command of `export (PACKAGE Seastar)`.
this behavior is enabled by default. but we perform the gating test in a docker container, where `$HOME` is `/` by default, and we don't override `$HOME` in `docker/dev/Dockerfile`, so CMake always fails to populate the Seastart package registry when performing tests, like
```
CMake Warning at CMakeLists.txt:1305 (export):
Cannot create package registry file:
//.cmake/packages/Seastar/fa3ead70757accdda096b789d64bb1e0
No such file or directory
```
this warning is distracting and is not relevant. as we don't build an application which finds Seastar using …
> build: do not populate package registry by default

- src/core/memory.cc
`obj_cpu` is only used in `assert()`, so it does not deserve a name in this simple use case, and a static analyzer might warn at seeing a defined-but-not-used variable when building a release build where `assert()` calls are optimized out.
> memory: do not define variable only for assert

- src/core/prometheus.cc
There's a common practice with Prometheus to use labels that starts with a double underscore (i.e., __) for internal label manipulation.  This patch follows the same idea for seastar.
Labels that start with __ will not be reported. This makes it easier to add labels for metrics manipulation without the cost of sending those labels on the wire.  Those labels can be used for filtering (like we already support __name __)
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
> prometheus: Don't report labels that starts with __

- include/seastar/rpc/rpc.hh
- src/rpc/rpc.cc
- tests/unit/loopback_socket.hh
- tests/unit/rpc_test.cc
The outgoing queue of an RPC connection cannot cancel its front request. Before the queue was converted into continuation chain, this "property" was relaxed during connect+negotiate phase, but now it's not such, i.e. -- a regression. This PR makes the queue fully uncancellable while the socket is connecting and negotiating.
> Keep outgoing queue all cancellable while negotiating

- CMakeLists.txt
- include/seastar/core/smp.hh
- src/core/smp.cc
`this_shard_id_ptr()` references a static thread_local variable defined in the function. if Seastar library is built as a static library, the linker will guarantee that there will be only a single definition of `g_this_shard_id`, and all translation unit will use this very instance.
but if Seastar is compiled and linked as a shared library. the shared library would have its own copy of this variable, while the executable would have another one, because this function is defined in the header. a symptom of this problem is that `this_shard_id()` is always 0 if any of the translation unit in the executable calls this function directly.
in this change, `this_shard_id_ptr()` is only declared in the header, and defined in .cc, if Seastar is built as shared library. so we have a single definition …
> smp: do not inline function when BUILD_SHARED_LIBS

- CMakeLists.txt
the "On one hard" line should be followed with "on the other hand" or something alike, but it seems the author moved to something else. So the explanation is rewritten to be more reader friendly.
> build: correct the comment

- include/seastar/core/smp_options.hh
- src/core/reactor.cc
It was deprecated ~2 years ago by 014711fd (cli: Ignore the --num-io-queues option). Can be safely removed already
fixes: #864
> reactor: Remove --num-io-queues option

- include/seastar/core/lowres_clock.hh
- include/seastar/core/preempt.hh
- include/seastar/core/scheduling.hh
- include/seastar/core/scheduling_specific.hh
- include/seastar/util/log.hh
- src/core/reactor.cc
- src/util/log.cc
this change is a follow-up of 97cd37098004194ff82612c792dd8fd8fe171ed0 for the same reason, we cannot include the tls variables in the header files.
in this change, all inline static variables are defined in .cc files when building shared library.
> treewide: do not inline tls variables in shared library

- include/seastar/net/packet.hh
- src/net/dpdk.cc
- src/net/virtio.cc
this change address a build failure with GCC 13. without it, we'd have following build failure:
```
/home/kefu/dev/seastar/include/seastar/net/packet.hh:318:25: error: declaration of ‘seastar::net::offload_info seastar::net::packet::offload_info() const’ changes meaning of ‘offload_info’ [-fpermissive]
318 |     struct offload_info offload_info() const noexcept { return _impl->_offload_info; }
|                         ^~~~~~~~~~~~
/home/kefu/dev/seastar/include/seastar/net/packet.hh:103:9: note: used here to mean ‘struct seastar::net::offload_info’
103 |         offload_info _offload_info;
|         ^~~~~~~~~~~~
/home/kefu/dev/seastar/include/seastar/net/packet.hh:46:8: note: declared here
46 | struct offload_info {
|        ^~~~~~~~~~~~
```
Fixes #1273
Signed-off-by: Kefu Chai …
> net: s/offload_info()/get_offload_info()/

- tests/unit/spawn_test.cc
pidfd_open(2) can fail on old kernels due to several reasons (e.g.
syscall not supported, O_NONBLOCK flags not supported), in which
case process:wait() falls back to waitpid(2) with backoff (at least
20ms), which may make it longer than 10ms.
Here we add the minimal backoff to 10ms so that the test can pass
on old kernels.
> spawn_test: prolong termination time to be more tolerant.

- include/seastar/core/sstring.hh
in scylla, we are using <=> in `data_dictionary::storage_options::s3`, but without the operator<=> defined for sstring, compiler is not able to implicitly define one for us.
so in this change, an operator<=> is added for sstring.
with this change, Clang-17 should be appeased and to define the <=> operator for `data_dictionary::storage_options::s3` in Scylla.
> core/sstring: define <=> operator for sstring

- src/core/prometheus.cc
neither of these two scollectd related headers is used by prometheus.cc, so let's remove them.
> prometheus: remove unused headers

- include/seastar/core/reactor.hh
- include/seastar/core/scheduling.hh
- src/core/reactor.cc
- tests/unit/scheduling_group_test.cc
Per-scheduling-group values might want to know the name of their scheduling group, e.g. if they hold some metrics for the group. But scheduling groups can be renamed, and currently there is no way to propagate that info to the values.
This patch allows the user of per-scheduling-group values to pass a callback called when the scheduling group is renamed. As with its sibling callbacks (`constructor` and `destructor`) it is called in the relevant scheduling group, so the value can learn the new name of its group using `current_scheduling_group()`.
> scheduling: add a `rename` callback to scheduling_group_key_config

- CMakeLists.txt
`Cooking.cmake` is included by Seastar's CMakeLists.txt for cooking ingredients. and `Cooking.cmake` uses `ExternalProject` CMake module for building ingredients as external projects. this module in turn downloads the source tarball and builds it. since CMake 3.24, a new policy named CMP0135 was introduced, which updates the timestamp of the extracted content of the downloaded tarball with the time when the tarball is extracted. this ensures artifacts are always rebuilt when the URL specified in `ExternalProject_add()` command is changed. in general, it's desirable to use this new policy. but before this change, we only set it *after* including `Cooking.cmake`. so `Cooking.cmake` is not affected by the new policy. it uses the old one.
since `Cooking.cmake` is an optional part integrated …
> build: set CMP0135 for Cooking.cmake

- CMakeLists.txt
- cmake/FindPthreadSetName.cmake
- cmake/Findlz4.cmake
- include/seastar/rpc/lz4_compressor.hh
- src/rpc/lz4_compressor.cc
- rpc: do not include lz4.h in header
- build: include CheckSymbolExists
- build: set the correct version when finding lz4
- build, rpc: do not support lz4 < 1.7.3
> build, rpc: lz4 related cleanups

- cooking.sh
- build: cooking.sh: use the same generator when building ingredients
- build: cooking.sh: use the same BUILD_SHARED_LIBS when building ingredients
> build: cooking.sh: use the same settings when building ingredients

- cooking_recipe.cmake
we should built the dependencies with -fPIC if Seastar is built as
a shared library.
before this change, dpdk is built without -fPIC, if it is built
with `cooking.sh`. and if user configures the building system with
debug or dev mode, seastar is compiled as a shared library. hence
the linker would fail to link libseastar with dpdk.
after this change, dpdk is compiled with `-fPIC`, so its symbols
are compiled as position-independent code, see
https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#index-fPIC .
so linker is able to link against it to build a shared library.
Fixes #1504
> build: build dpdk with `-fPIC` if BUILD_SHARED_LIBS

- include/seastar/rpc/rpc.hh
- src/rpc/rpc.cc
- tests/unit/loopback_socket.hh
- tests/unit/rpc_test.cc
The outgoing queue of an RPC connection cannot cancel its front request. Before the queue was converted into continuation chain, this "property" was relaxed during connect+negotiate phase, but now it's not such, i.e. -- a regression. This PR makes the queue fully uncancellable while the socket is connecting and negotiating.
refs: #1449 (it was reverted, this PR is the replacement)
closes: #1487
> Keep outgoing queue all cancellable while negotiating (again)

- tests/unit/futures_test.cc
GCC supports `-Wself-move` now, see
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html. so we should disable this warning when testing self-move.
this should silence the warning from GCC 13:
```
/home/kefu/dev/scylladb/seastar/tests/unit/futures_test.cc: In member function ‘virtual seastar::future<> test_self_move::run_test_case() const’:
/home/kefu/dev/scylladb/seastar/tests/unit/futures_test.cc:78:8: error: moving ‘s1’ of type ‘seastar::future_state<std::tuple<std::unique_ptr<int, std::default_delete<int> > > >’ to itself [-Werror=self-move]
78 |     s1 = std::move(s1); // no crash, but the value of s1 is not defined.
|     ~~~^~~~~~~~~~~~~~~
```
> test: futures: disable -Wself-move for GCC>=13

- src/core/reactor.cc
- tests/unit/spawn_test.cc
It turns out tools like "cat" expect fd opened blocking mode,
while the pipe fds are always created in non-blocking mode.
So in order to appease these tools, let's set the fds passed
to the spawned process to blocking mode.
Fixes #1320
Signed-off-by: Kefu Chai kefu.chai@scylladb.com
> reactor: pass fd opened in blocking mode to spawned process

- src/util/backtrace.cc
Summing only the sizes of executable segments is a mistake. Since we use it only to find .text symbol offsets, it would still work if executable segments were always the first segments in the image. However, that's not true -- in fact, they are usually second.
For example, here's a fragment of debug mode Scylla /proc/PID/maps:
7ffff1600000-7ffff54b3000 r--p 00000000 fd:03 1280976814 /home/user/scylla/build/debug/seastar/libseastar.so 7ffff54b3000-7ffff6d0a000 r-xp 03eb2000 fd:03 1280976814 /home/user/scylla/build/debug/seastar/libseastar.so 7ffff6d0a000-7ffff6def000 r--p 05708000 fd:03 1280976814 /home/user/scylla/build/debug/seastar/libseastar.so 7ffff6def000-7ffff7ef5000 rw-p 057ec000 fd:03 1280976814 /home/user/scylla/build/debug/seastar/libseastar.so
Due to the bug, backtrace.cc badly …
> backtrace: fix size calculation in dl_iterate_phdr

- include/seastar/core/metrics.hh
before this change, we use `boost::lexical_cast<std::string>()` to convert a given value to a string when creating a `label_instance`. but since we are migrating to fmtlib based formatting, it'd be desirable to format things using fmtlib.
this change has been tested by compiling scylla with the seastar submodule with the change.
Refs #1544
> metrics: use fmt::to_string when creating a label

- tests/unit/alien_test.cc
would be nice if we have more coverage of alien::* helpers. so,
in this change, the test exercising alien::run_on() is added.
please note, noexcept specifier is added to the lambda passed to
alien::run_on() to explain that this function does not throw, also,
this paves the road to the type constraint to be added to
alien::run_on() in a coming commit.
> test: alien_test: test alien::run_on() also

- include/seastar/core/reactor.hh
- include/seastar/core/sharded.hh
- src/core/reactor.cc
- tests/unit/foreign_ptr_test.cc
- tests/unit/futures_test.cc
* reactor: add run_in_backround and close
- run_in_background allows running background tasks safely, coupled with close() that wait on them using a gate.
* manual_clock: advance: use run_in_background to expire_timers
- Fixes #1514
> reactor: add background gate to wait on background tasks

- src/core/reactor.cc
std::unordered_map::empalce() inserts a new element into the container constructed in-place with the given args only if there is no element with the key in the container, which means we can only register handler for a specific signal only once and that's not reasonable.
We often use the stop_signal(which should have been a standard component of seastar but not yet) to manage SIGINT/SIGTERM for gracefully stopping application. It waits until receiving SIGINT or SIGTERM and then register a no-op handler on destruction to unregister the handler registered on construction, which however cannot work properly since the handler can be registered only once for a signal before this patch.
> reactor: allow registering handler multiple times for a signal.

- include/seastar/core/condition-variable.hh
condition_variable::awaiter implements the coroutine resumption after signal() by scheduling itself as a task which resumes the coroutine. The awaiter itself is (usually) allocated inside the coroutine frame, and dies after its containing co_await expression is resumed.
This is a problem, because the reactor expects tasks to stay alive while they are running — it saves a pointer to the current task in reactor::_current_task, which is used to find the parent task when printing the tasktrace. Because the awaiter task dies immediately after returning control to its parent, reactor::_current_task is left pointing to some garbage in the coroutine frame and current_tasktrace() will segfault when used before the next task switch.
This patch replaces this wakeup logic with a promise-future pair. …
> condition-variable: replace the coroutine wakeup task with a promise

- apps/iotune/iotune.cc
Calling test_file::close() may happen before create_data_file() managed to assign the _file field (e.g. -- test directory creation failed for whatever reason). In that case closing nullptr file-impl would crash.
refs: scylladb/scylladb#13439
> iotune: Don't close file that wasn't opened

- include/seastar/core/file.hh
- src/core/file-impl.hh
- src/core/file.cc
according to the C++ standard draft $9.3.4.6 [dcl.fct], see https://eel.is/c++draft/dcl.fct#4 .
> A parameter list consisting of a single unnamed parameter of
> non-dependent type void is equivalent to an empty parameter list.
and the symbol of a C++ function of `int foo(void)` is indeed identical to that of `int foo()`: both of them are `_Z3foov`. so, there is no need to keep the void parameter in the parameter list. this is a good practice in the C language though, the `void` in the parameter sends the message explicitly that: there is no parameters here.
> file: s/(void)/()/ in function's parameter list

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/CMakeLists.txt
- tests/unit/cert.cfg.in
- tests/unit/tls_test.cc
Fixes #1628
Subject alt name info can contain more extensive and detailed info on a connecting client. Add interface to allow querying this from a connected socket.
Initially we don't include this in accept-sequence auth verification, though we maybe should include it as an option.
> TLS: support for extracting certificate subject alt names from client certs

- include/seastar/core/sstring.hh
- tests/unit/sstring_test.cc
before this change, we only implemented the <=> operator with
`auto` as its template parameter as a member of sstring class.
and the == and != operator with basic_sstring as members of
sstring class. but this is not enough for some of our use cases,
where we also want to compare sstring with, for instance,
std::string and plain C strings, just like how we compare
an instance of std::string with std::string and plain C strings.
these are legitimate use cases, as we expect sstring as
a drop-in replacement of std::string under most circumstances.
because, even in C++20, the existing operator==(const basic_sstring&)
fails to be selected as a rewrite candidate when compiler tries to
compile a comparison expression like: "a" == sstring("a"), where
the LHS is a plain C string, because the …
> sstring: add == comparison operators

- src/util/program-options.cc
`#include <regex>` in util/program-options.cc was added back in 735dc123f0d86822fdc8562bb3561152c3f11748, where we were using std::regex for parsing map associations, but the function of
`parse_map_associations()` which uses std::regex was moved into util/log.cc.
so let's remove this include from the .cc file.
> util: remove unused #include

- include/seastar/core/condition-variable.hh
- include/seastar/core/future.hh
- include/seastar/core/loop.hh
The std:: one is available since C++17, which is now minimal for
seastar, so the seastar:: one can be replaced
> code: Use std::is_invocable_r_v instead of InvokeReturns

- src/core/reactor_backend.cc
use ::io_uring_free_probe() instead of ::free() to free the memory chunk pointed by `probe`. io_uring allocates the memory chunk by itself. so there are chances that the precompiled liburing is using the vanilla malloc from the libc, while we free the memory chunk using the overridden version which works with the customized allocator.
in other words, we cannot assume which malloc() was used. in this change, ::io_uring_free_probe() is used, as this function is provided by liburing, so we can ensure that the free() used by it always matches with the malloc() called by io_uring_get_probe_ring().
this should address the issue reported by ASan when the tree is compiled with liburing 2.4, like:
AddressSanitizer: attempting free on address which was not malloc()-ed
Fixes #1692
> reactor: use s/::free()/::io_uring_free_probe()/

- src/core/file.cc
file: call close() without the syscall thread
the close() system call
1. flushes the data if any
2. reclaims the fd
so far, most popular local filesystems do not implement
the "flush" op, but quite a few network filesystems
and layered filesystems implement it. for instance, cifs,
f2fs, fuse, nfs implement the "flush" op. so to be on the
safe side, let's call close() in reactor only when the
file is opened read-only. presumably, the fs implementation
mutate the its state only if the file is opened in writeable
flag enabled. this behavior is confirmed after auditing
all filesystems with flush op in linux v6.3.
Fixes #1689
> file: call close() without the syscall thread

- include/seastar/core/deleter.hh
It looks like this small helper object has them defaulted which likely leads to double ::free() of memory. It doesn't happen yet, but it's better to be on the safer side.
> deleter: Delete move and copy constructors

- include/seastar/core/gate.hh
Keep a (boost intrusive) list of holders in debug mode
so in case `gate.close()` doesn't finish in timely manner on shutdown, we can follow this list and track the continuation chain that holding the `gate::holder` and blocking `close()`
Closes #1676
> gate: track holders

- include/seastar/util/print_safe.hh
print_zero_padded_hex_safe was never supposed to be for signed integers. The concept was accidentally changed from std::integral to std::signed_integral instead of std::unsigned_integral in a recent refactor in 274f22a8c53c472feb1d110409a80d66df15b101. Fix that.
convert_zero_padded_hex_safe is using a non-existent one-argument variant of convert_hex_safe. Fix that.
> util: print_safe: fix hex print functions

- include/seastar/core/shared_ptr.hh
unlike std::shared_ptr, seastar::shared_ptr allows us to move a
value into a shared_ptr with operator=(). the corresponding change in
seastar was introduced by
https://github.com/scylladb/seastar/commit/319ae0b530107dce510c27f45d21b4ad696ef07d. despite that this helper is convenient, it is confusing. as the behavior of a shared_ptr should look like a pointer instead the value pointed by  it. and this could be error-prune, because a developer could by accident write something like:
```c++
p = std::string();
```
and expect that the value pointed by `p` is cleared. and all copies of this shared_ptr are updated accordingly. what he/she really wants is:
```c++
*p = std::string();
```
but the code compiles. while the outcome of the statement is that the destructor `p` is called, and `p` now …
> shared_ptr: deprecate lw_shared_ptr operator=(T&&)

- include/seastar/core/memory.hh
- include/seastar/core/posix.hh
- include/seastar/core/resource.hh
- include/seastar/core/smp.hh
- src/core/memory.cc
- src/core/posix.cc
- src/core/prefault.hh
- src/core/reactor.cc
- src/core/resource.cc
- src/core/smp.cc
To avoid latency spikes due to page faults on anonymous memory,
we mlockall() all memory. This prevents memory from being swapped out,
but we can still see a latency spike when faulting in the memory the first time
it is touched.
It's rare for this to be a problem, as faulting in an anonymous memory page
on first use is cheap - the kernel just has to zero it. However, things are complicated
by transparent hugepages as the kernel first has to defragment memory. This can
take quite a while, as was observed in [1].
The solution is to launch background threads that will attempt to fault-in the
memory ahead of the application. We need to be careful so that these threads
themselves don't compete with the application and cause latency spikes themselves,
so we take the following steps:
1. We …
> Prefault memory when --lock-memory 1 is specified

- include/seastar/net/tls.hh
- src/net/tls.cc
To allow applications to be more selective about how to treat certain exceptions.
Note: set of exported error codes is not exhaustive. Just enough to cover the more obvious cases
required by third parties. 
Note: naming is directly matching gnutls. By choice.
> tls: Export error_category instance used by tls + some common error codes

- include/seastar/core/alien.hh
as per the standard
> The generation of the implicitly-defined copy assignment operator is
> deprecated if T has a user-declared destructor or user-declared copy
> constructor.
and GCC rightfully warns us, if `-Wextra` is passed to the compiler:
```
In file included from /home/kefu/dev/seastar/src/core/reactor.cc:118:
/home/kefu/dev/seastar/include/seastar/core/alien.hh:110:5: error: definition of implicit copy assignment operator for 'qs_deleter' is deprecated because it has a user-provided copy constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy]
110 |     qs_deleter(const qs_deleter& d) : count(d.count) {}
|     ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/unique_ptr.h:192:15: note: in implicit copy assignment operator for …
```
> alien: do not define customized copy ctor

- src/core/prometheus.cc
functions return prvalue, so one cannot mutate them. and GCC rightfully points this out:
```
/home/kefu/dev/seastar/src/core/prometheus.cc:256:5: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
256 |     const uint32_t size() const {
|     ^~~~~
/home/kefu/dev/seastar/src/core/prometheus.cc:369:5: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]
369 |     const uint32_t size() const {
|     ^~~~~
```
in this change, the unnecessary `const` specifiers are removed.
> prometheus: do not qualify return type with const.

- tests/unit/CMakeLists.txt
in 18f43a0c7b148765853f47d3f5d562f53efe832e, a job definition is added for serialization the calls to openssl commands. it sets the global property named "JOB_POOL". assuming we have a parent project which uses Seastar. if:
- it is also using CMake and include Seastar as a subdirectory in its CMake building system, and
- it is also using "JOB_POOL", and
- it sets this variable before Seastar does. this variable's value will be overwritten by Seastar. and all of the targets using the pool(s) defined by it won't be able to find the defined pool(s) anymore.
the typical error message would look like
```
CMake Error:
Running
'/home/kefu/.local/bin/ninja' '-C' '/home/kefu/dev/scylladb/build/cmake-test' '-t' 'recompact'
failed with:
ninja: error: build.ninja:1360: unknown pool name 'link_pool' …
```
> build: append JOB_POOLS definition instead of setting it

- src/core/file.cc
- src/core/reactor.cc
With package xfsprogs-devel >= 5.14.1, `fallthrough` has defined to fix compilation warning in header <xfs/linux.h>,
(see: https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/commit/?id=df9c7d8d8f3ed0785ed83e7fd0c7ddc92cbfbe15) There is a confliction with c++ keyword `fallthrough`, hence compilation error occurs like:
```
FAILED: CMakeFiles/seastar.dir/src/core/file.cc.o
/usr/bin/g++ -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BROKEN_SOURCE_LOCATION -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I/home/seastar/include -I/home/seastar/build/release/gen/include -I/home/seastar/src -O2 -g -DNDEBUG -U_FORTIFY_SOURCE -Wno-maybe-uninitialized …
```
> core: undefine fallthrough to fix compilation error

- include/seastar/rpc/rpc.hh
- src/rpc/rpc.cc
Now it's a pointer, but it's non-nullptr all the time and never changes
> rpc: Make server._proto a reference

- include/seastar/coroutine/maybe_yield.hh
maybe_yield_awaiter resumes the coroutine (after it decided to suspend it) by scheduling *itself* as a task, which -- when executed -- resumes the coroutine.
The awaiter itself is (usually) allocated inside the coroutine frame, and dies after its containing co_await expression is resumed. This is a problem, because the reactor expects tasks to stay alive while they are running. To facilitate current_tasktrace(), a global pointer to the currently running task is needed. Thus, when the reactor starts executing a task, it saves a pointer to it in reactor::_current_task.
Since the awaiter task dies immediately after returning control to its parent, reactor::_current_task is left pointing to some garbage in the coroutine frame and current_tasktrace() will (most likely) segfault when used …
> coroutine: fix a use-after-free in maybe_yield

- cmake/SeastarDependencies.cmake
std::unary_function was deprecated in C++11, and was removed in C++17. but Boost::container is still using it. libstdc++ keeps it around even compiles with C++20 standard, while libc++ just keeps us away from it when compiling with C++20, and we would have following compiling error:
```
FAILED: CMakeFiles/seastar.dir/src/core/memory.cc.o
/usr/lib64/ccache/clang -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_URING -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I/home/kefu/dev/seastar/include -I/home/kefu/dev/seastar/build/clang-libcxx/gen/include -I/home/kefu/dev/seastar/src -stdlib=libc++ -O3 -DNDEBUG -std=gnu++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING …
```
> build: pass -DBOOST_NO_CXX98_FUNCTION_BASE to C++ compiler

- CMakeLists.txt
the CMake policy of CMP0127 defines the behavior
of `cmake_dependent_option()`. this policy was introduced by CMake 3.22, and our minimal required CMake version is 3.13, so we need to conditionalize it.
the new behavior allows us to use nested paren groups, while the old behavior does not. but our use cases is very simple and works with the new behavior and old one. so, to silence the warnings emitted by CMake v3.22 and up, let's explicitly set the policy. to simplify the code, let's use a loop and always use the NEW behavior.
```
CMake Warning (dev) at /usr/share/cmake-3.24/Modules/CMakeDependentOption.cmake:89 (message):
Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
cmake_policy command …
```
> build: use new behavior defined by CMP0127

- include/seastar/core/internal/estimated_histogram.hh
- include/seastar/core/reactor.hh
- src/core/reactor.cc
- tests/unit/metrics_test.cc
Seastar reports stalls above some threshold. It is helpful to follow the  distribution of the stalls. 
This series adds a time_estimated_histogram to the stall detector.
The series takes the estimated_histogram definition from the ScyllaDB project.
Whenever a stall is found, it is added to the histogram.
The stall histogram is reported once per node.
Fixes #1674
> Add a stall detector histogram

- install-dependencies.sh
gcc-toolset-11 is not available in centos9.
> install-dependencies: add centos9 dependencies

- include/seastar/rpc/rpc.hh
It exists on client and server connecitons, but the value it returns sits on their common ancestor -- the rpc::connection class. So the method can exist in the same place
> rpc: Generalize get_stats_internal() method

- include/seastar/util/shared_token_bucket.hh
This helper calculates the duration that it takes to replenish the specified amount of tokens. When the number of provided tokens is less than than the configured rate the integer division gives zero result which immediatelly converts to empty duration. That's not correct, the duration type is double and can be calculated with more precision.
Typically users of token bucket call this method when they see a deficiency after grabbing a token. In that case they sleep or arm a timer for the provided duration and then call replenish() on the bucket. If the deficiency is small and the calculated duration is zero so the caller doesn't sleep. This leads to unneeded busy-looping around the token bucket.
Another consequence of not sleeping on small deficiency is that replenish() converts time delta …
> shared_token_bucket: Fix duration_for() underflow

- src/core/linux-aio.cc
- src/core/reactor.cc
To help debug cases where aio-max-nr is not enough.
> reactor, linux-aio: print value of aio-max-nr on error

- include/seastar/core/fair_queue.hh
- src/core/fair_queue.cc
The methods that export queued- and executing- requests counts had been deprecated several years ago. It's time to drop both -- the methods and the counters themselves
> fair_queue: Remove individual requests counting

- include/seastar/util/shared_token_bucket.hh
- tests/perf/CMakeLists.txt
- tests/perf/shared_token_bucket.cc
The test checks if the token-bucket "rate" is held under various circumstances:
- when shards sleep between grabbing tokens
- when shards poll the t.b. frequently
- when shards are disturbed with CPU hogs
So far the test shows four problems:
- With few shards tokens deficiency produces zero sleep time, so the "good" user that sleeps between grabs effectively converts into a polling ("bad") user (fixed by #1722)
- Sometimes replenishing rounding errors accumulate and render lower resulting rate than configured (fixed by #1723)
- When run with CPU hogs the individual shard's rates may differ too much (see #1083). E.g. the bucket configured with the rate of 100k tokens/sec, 48 shards, run 4 seconds.
"Slowest" shard vs "fastest" shards get this amount of tokens:
no hog:   6931 ... 9631
with …
> tests: Add perf test for shard_token_bucket

- src/core/fair_queue.cc
On dispatch the request capacity is calculated into req_cap variable, so it can be reused everywhere below
> fair_queue: Do not re-evaluate request capacity twice

- include/seastar/rpc/rpc.hh
Client-side stream socket is made by client::make_stream_sink() call. The stream creation consists of
- wait for "this" to finish negotiation
- make new client (this issues connect() and negotiation in the background)
- wait for the new socket negotiation to finish
- .then([] { register new socket to "this" socket })
The last step is racy. After the new socket negotiation succeeds the parent socket (called "this" above) may receive "peer closed" from the kernel and start demolishing the client. The latter means aborting all streams, that happens in one non-preemptive and non-waiting loop. So in case the new stream wasn't _yet_ registered, it won't be aborted and will wait for the server-side stream to terminate (which also may never happen, see #1732)
> rpc: Fix client-side stream registration race

- apps/io_tester/ioinfo.cc
- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
On start reactor and io-queue do some math calculating IO-queue's configuration. For the ease of debugging all this math was printed into log with info level. Now it's more-or-less stable and predictable, so the printing can be dropped not to make too many noise into logs. To still have the ability to get the math results there's ioinfo app out there that's extended by this PR to print all internal IO scheduler configuration
fixes: #1428
> Print more IO info with ioinfo app

- tests/unit/tls_test.cc
before this change, we get the `accept_result` after calling `abort_accept()`, but there is chance that the event from the fd which is registered for accept event is not fired yet, and the fd is closed, so what we get is an errno of EINVAL because `shutdown(fd, SHUT_RD)` is called. so `sa.get0()` throws a `system_error` instead of the `accept_result`.
this does not happen if the backend is `linux-aio`. but it surfaces occasionally when the io_uring backend is used.
Fixes #1532
> tls_test: abort_accept() after getting server socket

- src/core/smp.cc
This PR is in support of running multiple instances of Seastar in a process. The smp service group management semaphore is only used on core 0. However, in a multi-instance scenario core 0 corresponds to different threads, one in each instance of seastar.
> smp: make service management semaphore thread local

- apps/io_tester/ioinfo.cc
- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
- tests/perf/fair_queue_perf.cc
- tests/unit/fair_queue_test.cc
Current implementation of fair-queue uses two distinct data types to "measure" a request -- tickets and capacities. The former is a 2d value that represents request weight and size and the latter is a fixed-point number that represents the request cost that's used by cross-classes balancing and capacity throttling. The capacity is calculated from the ticket each time f.q. needs to know the entry's capacity, which is not very efficient.
Other than generating extra CPU waste, this detail makes it hard to auto-adjust the dispatch rate. This is because the entry's (and a entry represents an IO request) capacity is its ticket normalized by the capacity "cost" ticket. If the queue needs to lower or increase the dispatch rate, it has two options: re-configure the token bucket, or change the …
> Keep capacity on fair_queue_entry

- include/seastar/core/chunked_fifo.hh
- tests/unit/chunked_fifo_test.cc
a proper iterator's operator++(int) should return an instance of this iterator, and  operator++() should return a reference of this iterator. but chunked_fifo::iterator and chunked_fifo::const_iterator's incremental operator returns basic_iterator<U>. this is not quite right in the sense of the behavior of a proper iterator's interface.
so, in this change, instead of inheriting from the `basic_iterator`, we just define the `iterator` and `const_iterator` as the instantiation of this template.
Fixes #1793
> chunked_fifo: let incremetal operator return iterator not basic_iterator

- include/seastar/core/sstring.hh
since fmt v10.1.1, it disabled implicitly conversion in quite a few use cases. to be more specific, in fmtlib 10.1.0, it stops converting the first argument passed to
formatter<std::string_view>::format(const std::string_view& s, FormatContext&) to `std::string_view`, even if the parameter can be implicitly converted to `std::string_view`. as the formatter of `std::string_view` is implemented by subclassing its formatter from the builtin basic_string_view's formatter.
so, the existing formatter does not compile any more with fmt v10.1.1 and up.
in this change,
* convert the sstring instance to std::string_view explicitly before formatting it.
* private inherit from fmt::formatter<string_view>. as strictly, speaking, fmt::formatter<sstring> is not a fmt::formatter<std::string_view>
* …
> sstring: format sstring without implicit conversion

- include/seastar/net/arp.hh
- include/seastar/net/ethernet.hh
- include/seastar/net/ip.hh
unused params in net::ethernet_address::adjust_endianess,
net::arp_protocol::forward and net::ip_protocol::forward trigger -Wunused-parameter 
This PR fixes this by either removing the name of the parameter or by void-casting
> Fix -Wunused-variable warnings

- CMakeLists.txt
- cmake/code_tests/stdout_test.cc
- include/seastar/util/log.hh
- include/seastar/util/process.hh
- src/core/program_options.cc
- src/util/log.cc
- src/util/process.cc
- tests/unit/spawn_test.cc
- tests/unit/tls_test.cc
musl libc defines `stdout` like
```c++
#define stdout (stdout)
```
while glibc defines `stdout` like
```c++
#define stdout stdout
```
the same applies to `stderr`. both these definitions comply to the the C++ standard, but we reuse `stdout` and `stderr` when defining an `enum class` or when defining a member function . so, for instance, after preprocessing, the definition from musl libc is expanded into
```c++
enum class logger_ostream_type {
none,
(stdout),
(stderr),
};
```
which does not compile. so, in order to be more standard compliant, and does not rely on a specific libc implementation, while preserve the backward compatibility. let's check if `stdout` and `stderr` can be used as an identifier. also, since `stdout` and `stderr` are required to be defined as macros by the standard …
> build, process: avoid using stdout or stderr as C++ identifiers

- src/core/smp.cc
we are supposed to call `p1->fetch_or()` but ended up using `p->fetch_or()`, where `p` is a plain pointer. this issue has not been reported until we started to build Seastar on architecture not amd64 or aarch64.
Fixes #1815
> smp: reference correct variable when fetch_or()

- CMakeLists.txt
- cmake/Finducontext.cmake
musl libc does not offer the symbols of getcontext() and friends. it merely provides the header file of `ucontext.h` with the declarations of these functions so that "gcc with dwarf2 unwinding" can be built without errors. these functions were removed from POSIX. fortunately, libucontext provides a portable implementation.
in this change, if the function of `getcontext()` can not be compiled or linked, we fall back to check libucontext, and use it as a fallback.
this should improve portability of Seastar, so it can compile on platforms where glibc is not available.
> build: check if libucontext is necessary for using ucontext functions

- CMakeLists.txt
- cmake/FindSystemTap-SDT.cmake
- src/core/reactor.cc
systemtap is not available in musl libc. and we should detect at the configure time.
in this change, we check for the existence of `sys/sdt.h`, and define a placeholder for `STAP_PROBE()` macro if the header is not available.
Fixes #557
> build: enable systemtap only if it is available

- CMakeLists.txt
-Warray-bound was disabled in bdbce89e, by then we had false alarms from GCC 9, but now that the fix of the false alarm was merged in GCC 10, and GCC 13 was already released. since Seastar supports up to two major releases of GCC, we can safely drop this workaround.
> build: reenable -Warray-bound compiling option

- src/core/linux-aio.cc
we can raise exception with more accurate error message according to `errno`. so in this series, let's fill `std::runtime_error` with the more specific error message.
> linux-aio: better error handling when io_setup() fails

- pkgconfig/seastar.pc.in
this addresses the regression introduced by
843131281b21bb1273caec3f04c1a8e27dd53812
> build: s/{dpdk_libs}/${dpdk_libs}/

- include/seastar/http/client.hh
- src/http/client.cc
Some (spoiler: AWS S3) http servers may send back the `Connection: close` header indicating that its going to close the connection after sending back the response. Not handling it is problematic for http client due to batch-flushes being explicitly used.
After client handles such a response, it will put back the connection into the pool. In case there's another request to be served, the same connection will be taken back and the request will be sent. However, write()-ing the request into the connection and even flush()-ing it won't report back _any_ exception because the batch-flush is turned on on socket by default. So the fact that the server had already closed the connection will only be found out at the attempt to read back and parse the response. Although in this case the client must …
> Proactively close non-keepalive http connections

- include/seastar/util/backtrace.hh
- src/core/file.cc
- src/util/backtrace.cc
- tests/unit/exception_logging_test.cc
- tests/unit/unwind_test.cc
musl lacks execinfo.h
lfs64 definitions are now deprecated and will be removed in the next release of musl
Fixes #1743
> fix compilation for musl

- scripts/seastar-addr2line
it is kind of overkill to define a class to implement an iterator. less just use `yield` here. simpler this way, and less indent.
as we expect the resolver prints all decoded backtrace in a bulk, we still materialize the input backtrace using `list()`, so the input and output are not interleaved.
> scripts: addr2line: use yield instead defining a class

- scripts/seastar-addr2line
this addresses the regression introduced by 394010d6, which missed a change mistakenly included by another pull request.
> scripts: addr2line: change StdinBacktraceIterator to a function

- scripts/addr2line.py
this is the default behavior in Python3.
> script: do not inherit from object

- src/core/linux-aio.cc
- src/core/memory.cc
- src/core/posix.cc
- src/core/reactor.cc
- src/core/reactor_backend.cc
- tests/unit/thread_test.cc
Currently seastar fails to compile on non glibc platforms like ones using musl libc due to the use of some internal glibc macros and glibc extensions of functions, so change to portable ones or perform checks to make sure the correct one is used for the target platform.
These changes include:
Changing includes of sys/poll.h and sys/signal.h to the posix location without sys
Replacing the internal __mode_t with mode_t
Fix strerror_r usage which was a glibc specific extension
Use pthread_setaffinity_np instead of pthread_attr_setaffinity_np
Access sigevent.sigev_notify_thread_id with a macro
> Fix compilation for non glibc platforms like alpine using musl libc

- CMakeLists.txt
- cmake/CheckLibc.cmake
- src/core/linux-aio.cc
- src/core/memory.cc
in this series, instead of checking `__GLIBC__` macro for some glibc specific behavior, we check the behavior directly using CMake. this should improve the maintainability.
> build: detect glibc features using CMake 

- .circleci/config.yml
see https://circleci.com/developer/images?imageType=machine, and update the tag to the latest tag. see
https://circleci.com/developer/machine/image/ubuntu-2204 . despite that we only use the circleci's image for running docker container, it'd always be desirable to use the "standard" image which is armed with a more recent docker runtime and linux kernel.
> circleci: update the image to CircleCI "standard" image

- include/seastar/rpc/rpc.hh
- src/rpc/rpc.cc
- tests/unit/rpc_test.cc
RPC connections already collect some stats about themselves, but these stats are not registered in metrics layer. There main question here is the granularity of reporting -- per-connection, ~~node~~shard-wide or in groups. The grouping seems the most appropriate way, but RPC layer itself has little glues to how group the sockets, so the groups configuration is up to the application and this PR provides the facilities for such grouping.
refs: #323
> RPC metrics

- include/seastar/core/reactor.hh
There's a bunch of templatized calls to manage sched group specific data. Fortunately, none needs to access reactor private members
> reactor: Unfriend a bunch of sched group template calls

- include/seastar/core/iostream-impl.hh
- include/seastar/core/reactor.hh
- src/core/reactor.cc
Not the part of public API at all
> reactor: Move add_to_flush_poller() to internal namespace

- include/seastar/core/reactor.hh
- src/core/reactor.cc
The params struct just needs the constexpr unsigned max_queues value from reactor. Declaring it as friend is pretty huge hammer for that nail. It's better to construct the params with the needed limit and make it self-contained.
> reactor: Unfriend disk_config_params

- include/seastar/util/backtrace.hh
Currently only tasktrace is formattable, add a formatter for simple_backtrace too.
> utils/backtrace.hh: make simple_backtrace formattable

- include/seastar/http/client.hh
- include/seastar/http/request.hh
- src/http/client.cc
- src/http/request.cc
The confidence comes from marking the request reference const throughout the sending methods. There are only two places that are allowed to change the request, and after this patch they become explicit and, thus, controllable.
refs: #1847 (this pr is prerequisite for that one)
fixes: scylladb/scylladb#15509
> Make sure http client doesn't change request while sending

- CMakeLists.txt
- cmake/CheckHeaders.cmake
instead of hard-wiring the target for "checkheaders" to "checkheaders", pass the target name as a parameter. also, this change does not add a header check helper target if the specified library target does not contain any headers.
this allows us to reuse the `seastar_check_self_contained()` function in the parent project.
> build: pass target name to seastar_check_self_contained

- include/seastar/core/internal/io_desc.hh
in 8295335c, in order to silence a warning from compiler, the user-provided dtor of kernel_completion was removed. but the removal exposes the implicitly default-generated dtor as a public member function. this is not intended, as `kernel_completion` should not be deleted directly, as the dtor is not marked virtual, we must always delete it via its derived classes.
to correct this and to address the compile warning previously addressed by 8295335c,
* the dtor is brought back. this addresses the concern of exposing the dtor public.
* the copy ctor is added, so that it is defined explicitly. this addresses the compile warning.
* the default ctor is added, otherwise it is deleted, as we have a user-provided copy ctor now.
> reactor: mark kernel_completion's dtor protected

- CMakeLists.txt
so that for instance, we are aware that which pieces of code are
* using deprecated stuff with "deprecated" attribute attached to it
* using deprecated C++ feature
please note, this will enable a bunch of "-Wdeprecated-*" compiler
warning options, which are previously disabled. and these warning
will be taken as errors with the exception of "deprecated-declarations".
These warnings are from the `[[deprecated]]` attribute.
So this change requires us to address all of the other "-Wdeprecated-*"
warnings in Seastar. but this does not force the applications using
Seastar to do the same, as the "-Wdeprecated" option is a private CXX
flag which is only used when compiling Seastar itself.
Fixes #1863
> build: enable -Wdeprecated compiler option

- src/core/memory.cc
in the same spirit of 11898c17.
this change should address the warnings like:
```
src/core/memory.cc:1930:24: error: dynamic exception specifications are deprecated [-Werror,-Wdeprecated-dynamic-exception-spec]
void* malloc(size_t n) throw () {
^~~~~~~~
```
Refs #1868
> memory: s/throw()/noexcept/

- cmake/CheckLibc.cmake
- src/core/posix.cc
if it is present
as noted in the review of: https://github.com/scylladb/seastar/pull/1803/
and the commit
https://github.com/scylladb/seastar/commit/982690e8ead7d8cf30a71746ea0d55ee74f582a5#r1315429863
using the portable version could lead to a performance hit of some instructions running on the wrong core while the affinity was set after creation
> core/posix return old behaviour using pthread_attr_setaffinity_np

- include/seastar/core/loop.hh
- tests/unit/futures_test.cc
The implementation uses tag dispatch to call out to `std::distance` for
forward iterators and below.
However this doesn't work as expected for random iterators. They will
actually get dispatched to the default template version.
Hence, functions that use `iterator_range_estimate_vector_capacity`
don't pre-reserve anything for `std::vector` or similar classes.
This causes lots of reallocations when using `seastar::when_all` or
similar.
Change the implementation to also call out to std::distance for derived
types.
> loop: Fix iterator_range_estimate_vector_capacity for random iters

- src/core/memory.cc
in cf0c3ee0df1d64bb6e162d5b47edbba53c62215d, we detected for the GNU variant of `strerror_r()` and falled back to the XSI variant if the GNU version was not available. but we failed to handle the case where `strerror_r()` succeeds in the XSI branch -- we should use the buffer passed to `strerror_r()` for the returned `msg`. and `buf` is not defined there. it was a copy-pasta error.
in this change, the error is corrected by s/err/buf/
> memory: use `err` for the error string

- doc/io-scheduler.md
- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- include/seastar/core/reactor_config.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
- src/core/reactor.cc
There are three places where IO dispatch loop is throttled
* self-throttling with token bucket according to math model
* per-shard one-tick threshold
* 2-bucket approach when tokens are replenished only after they are released from disk
This PR removes the last one, because it leads to self-slowdown in case of reactor stalls. This back-link was introduced to catch the case when the disk suddenly slows down to stop dispatched to over-load it with requests, but effectively this back-link measures not the real disk dispatch rate, but the disk+kernel+reactor dispatch rate. Despite the "kernel" part is tiny, the reactor part can grow large triggering the self slow-down effect.
Here's some math.
Let's assume that a some point scheduler dispatched N_d requests. It means that it was able to grab …
> Slowdown IO scheduler based on dispatched/completed ratio

- include/seastar/core/when_all.hh
- tests/unit/futures_test.cc
In cases where the caller of `when_all_succeed` has already allocated a vector for the futures this overload avoids having to make an extra allocation internally for another vector of futures.
> Add a vector overload to `when_all_succeed`

- cmake/CheckHeaders.cmake
these warning does not help when checking the self-contain'ness of these headers. actually they are always false alarms, as the way how we check the self-contain'ness of headers is to rename the headers to .cc files and compile them. but the symbols defined by the header are not always used by the header itself. hence there are good chances that the compiler would complain with these -Wunused-* warnings.
in this change, to silence these warnings,
- replace, for instance `-Wno-error=unused-variable` with `-Wno-unused-variable`, to completely disable these warnings.
- pass the options disabling these warning after the ones specified for the target being built. the options for building the target are likely to contain the option to enable these -Wunused-* warnings. if multiple options …
> build: disable the -Wunused-* warnings for checkheaders

- include/seastar/core/metrics_api.hh
- src/core/metrics.cc
- src/core/prometheus.cc
- src/core/scollectd.cc
Upon resizing, a std::vector will allocate a large piece of contiguous memory which may become fragmented over time. This can lead to oversized allocations on the metadata vector occurring at the call to vector.emplace_back():
```cpp
void impl::update_metrics_if_needed() {
if (_dirty) {
_metadata = ::seastar::make_shared<metric_metadata>();
auto mt_ref = ::seastar::make_shared<metric_metadata>();
auto &mt = *(mt_ref.get());
mt.reserve(_value_map.size());
_current_metrics.resize(_value_map.size());
size_t i = 0;
for (auto&& mf : _value_map) {
metric_metadata_vector metrics;
_current_metrics[i].clear();
for (auto&& m : mf.second) {
if (m.second && m.second->is_enabled()) {
metrics.emplace_back(m.second->info()); // Backtrace shows overalloc occurs here …
```
> metrics: change metadata vector to chunked_fifo

- include/seastar/core/posix.hh
- include/seastar/http/httpd.hh
- include/seastar/http/request.hh
- include/seastar/net/api.hh
- include/seastar/net/stack.hh
- src/http/httpd.cc
- src/net/native-stack-impl.hh
- src/net/posix-stack.cc
- src/net/stack.cc
- src/net/tls.cc
- tests/unit/loopback_socket.hh
Adds the client and servers network address information to the `seastar::http::request` structure and populates it when it is created.
Fixes: #1850
> httpd: Added server and client addresses to request structure

- src/core/reactor.cc
- src/core/thread_pool.cc
- src/core/thread_pool.hh
The reactor* is non-null all the time, better make it a reactor&
> thread_pool: Reference reactor, not point to

- include/seastar/core/reactor.hh
- include/seastar/coroutine/parallel_for_each.hh
After coroutine::parallel_for_each resumes its caller coroutine and dies, reactor::_current_task might be left dangling.
To fix this without allocations, we have to set _current_task to the coroutine before resuming it.
Fixes #1902
> coroutine: fix use-after-free in parallel_for_each

- include/seastar/core/file-types.hh
- include/seastar/core/file.hh
- include/seastar/core/reactor.hh
- src/core/file-impl.hh
- src/core/file.cc
- src/core/reactor.cc
- tests/unit/directory_test.cc
Current implementation of list_directory() requires a callback function that's called with entries. That's not very convenient for coroutines-enabled code. E.g. Scylla has the convenience emulation of this approach, see scylladb/scylladb@207174c6927
> Add file::list_directory() that co_yields entries

- apps/memcached/memcache.cc
- demos/udp_client_demo.cc
- demos/udp_server_demo.cc
- demos/udp_zero_copy_demo.cc
- include/seastar/core/seastar.hh
- include/seastar/net/api.hh
- include/seastar/net/posix-stack.hh
- include/seastar/net/stack.hh
- include/seastar/net/udp.hh
- src/core/reactor.cc
- src/core/scollectd-impl.hh
- src/core/scollectd.cc
- src/net/dns.cc
- src/net/native-stack.cc
- src/net/posix-stack.cc
- src/net/stack.cc
- src/net/udp.cc
- tests/unit/ipv6_test.cc
- tests/unit/unix_domain_test.cc
This is a successor of: https://github.com/scylladb/seastar/pull/1804
@avikivity written in the previous PR:
> We could rename udp_channel to datagram_channel and deprecate the old name.
At first I wanted to do a basic rename, but forcing unbound&bound channel creation into the `make_udp_channel` signature turned out to be messy. 
This series:
- does a rename of udp related things
- introduces a new datagram channel creation API
- adapts `posix_udp_channel` to protocol stacks other than UDP over IP
- deprecates `udp_channel` creation methods
Fixes: #1894
> Generalize `net::udp_channel` into `net::datagram_channel`

- apps/rpc_tester/rpc_tester.cc
The same fix was applied to io_tester some time ago -- #1893. Now its rpc_tester turn as it includes the very same set of headers.
> rpc_tester: Disable -Wuninitialized when including boost.accumulator

- include/seastar/core/execution_stage.hh
- include/seastar/net/ethernet.hh
- include/seastar/net/socket_defs.hh
- include/seastar/rpc/rpc_types.hh
When SEASTAR_MODULE isn't used and FMT_VERSION >= 90000 some headers define specialized fmt::formatter templates, so #include <fmt/ostream.h> to statisfy their requirements.
> include fmt/ostream.h to make headers self-sufficient

- include/seastar/core/shared_future.hh
- tests/unit/futures_test.cc
A shared future takes a regular future on construction and resolves after the original future resolves. This is implemented by attaching a `then_wrapped` continuation on the original future which, when run, forwards the result of the original future to the currently registered waiters.
The original future is kept in the `_original_future` field. The continuation is attached on the first `shared_future::get_future()` call - which causes the `_original_future` to become invalid - and it is reassigned again at the end of the continuation.
This implementation detail has an effect on `shared_future::available()`, which is implemented via `_original_future.available()`. When the promise associated with the original future is set, the continuation is scheduled for execution but does not run …
> shared_future: make available() immediate after set_value()

- scripts/perftune.py
Currently, when we use iSCSI disk for the data volume, we get following error while running "--tune disks":
ERROR: [Errno 2] No such file or directory: '/sys/devices/platform/modalias'. Your system can't be tuned until the issue is fixed.
This is because iSCSI is virtual device, it does not pointed to /sys/devices/pciXXX, and does not have IRQs informations.
We should just skip discovering IRQs for such devices, instead of calling learn_all_irqs_one().
Fixes scylladb/scylladb#10367
> perftune.py: skip discovering IRQs for iSCSI disks

- include/seastar/util/closeable.hh
- include/seastar/util/defer.hh
`[[nodiscard]]` does not accept an argument until C++20, but we still support C++17, so let's avoid using the C++20 feature before dropping the support of C++17.
Fixes #1932
> defer, closeable: do not use [[nodiscard(str)]]

- src/net/ip.cc
In dpdk.cc:1515 when running program utilizing Seastar with smp::count == 1, rss hashing is NOT enabled, but when a fragmented packet is reassembled in ip.cc:195, no check is done if smp::count == 1, so the following line is called to identify cpu to forward packet to:
cpu_id = _netif->hash2cpu(toeplitz_hash(_netif->rss_key(), hash_data));
Since running with only a single cpu and hashing not enabled, the call to toeplitz_hash faults. 
Issue resolved by checking to see if smp::count == 1 after defragmentation and if so, bypassing hash calls and just calling l4->received() directly
> Address issue where Seastar faults in toeplitz hash when reassembling fragment

- src/core/memory.cc
- tests/perf/fstream_perf.cc
vla (variable length array) is an extension in GCC and Clang. and it is not part of the C++ standard.
so let's avoid using it if possible, for better standard compliant and to silence the warning from Clang 18:
```
/home/kefu/.local/bin/clang++ -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_DEPRECATED_OSTREAM -DFMT_SHARED -DSCYLLA_BUILD_MODE=release -DSEASTAR_API_LEVEL=7 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_PTHREAD_ATTR_SETAFFINITY_NP -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -DSEASTAR_STRERROR_R_CHAR_P -DCMAKE_INTDIR=\"Release\" -I/home/kefu/dev/scylladb/seastar/include …
```
> memory: do not use variable length array

- include/seastar/core/scheduling.hh
- include/seastar/core/task.hh
- include/seastar/core/with_scheduling_group.hh
- src/core/reactor.cc
- tests/unit/scheduling_group_test.cc
Fixes #1511
`init_new_scheduling_group_key` iterates all task queues and calls `with_scheduling_group` calls to each.
This in turn will, for all but the active group, call `internal::schedule_in_group`. This will weirdly enough _work_ even for the _at_destroy group IFF the queue is empty at call, in which case the queue is added to queues to process. This is of course wrong on oh so many planes.
Now, if the at_destroy queue is _not_ empty, we will instead deadlock here, waiting for a task queue that will not be scheduled.
This patch
* Special treats the at_destroy queue in init_new_scheduling_group_key
* Changes with_scheduling_group to schedule tasks "checked", which in turn ensures we don't try to run things in at_destroy queue ahead of time (fatal error, because noexcept) * Adds a test …
> reactor/scheduling_group: Handle at_destroy queue special in init_new_scheduling_group_key etc

- include/seastar/core/future.hh
- include/seastar/core/reactor.hh
- src/core/future.cc
- src/core/reactor.cc
- tests/unit/futures_test.cc
- tests/unit/stall_detector_test.cc
There are several calls that are declared as a part of reactor API, while they are only for testing purposes. This PR wraps them into test sub-class (which makes them reactor friends automatically) to emphasize the intent and shrink the overloaded reactor API a bit
> Sanitize test-only reactor facilities

- include/seastar/core/file.hh
- include/seastar/coroutine/generator.hh
- src/core/file-impl.hh
- src/core/file.cc
because the buggy buffered generator, as a workaround, let's use the unbuffered generator as an intermediate workaround of #1913 .
the downside of this change is that buffered generator allows the generator coroutine to yield the elements without being suspended, if it is able to generate the produced elements in batch, thus can have better performance. this design is a good fit of use cases like readdir. we will revert this change once #1913 is fixed.
Refs #1913
> file: use unbuffered generator in experimental_list_directory()

- include/seastar/net/tls.hh
- src/net/tls.cc
this change addresses the formatting with fmtlib v10, which stopped creating the default-generated formatter even if FMT_DEPRECATED_OSTREAM preprocess macro is defined. but it allows us to format by providing a format_as() overload. please note this does not work with fmtlib v9, in which, we still need either define FMT_DEPRECATED_OSTREAM or define a proper fmt::formatter<> for this type.
Refs https://github.com/scylladb/scylladb/issues/13245
> tls: add format_as(subject_alt_name_type) overload

- CMakeLists.txt
- cmake/CheckGcc107852.cmake
if the compiler impacted by
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107852 is used to compile Seastar with fmtlib v10, the tree would fail to compile, because we consider `-Warray-bounds` warnings as error.
to build with compiler (typically GCC 13.1) which suffers from this bug. let's stop considering these false alarms as error. a minimal reproducer is introduced for testing this compiler bug.
Fixes #1716
> build: do not error when run into GCC BZ-1017852

- src/core/reactor.cc
in reactor's constructor, `_cpu_stall_detector` is initialized before `_task_queues` as they are declared in this order. normally, this arrangement works just fine. but there is cases where `make_cpu_stall_detector()` fails, then we would have following sequence:
1. in `make_cpu_stall_detector()`, it tries to to set up the performance monitoring using `perf_event_open()`,
2. if `perf_event_open()` fails, `make_cpu_stall_detector()` writes a logging message, which ends up calling `logger::do_log()`
3. in `logger::do_log()`, it formats the logging message with the output of `scheduling_group::short_name()` if `local_engine` is set
4. `scheduling_group::short_name()` checks if `_task_queues` of local reactor engine is empty, and indexes it with the scheduling group's id
but at that moment, …
> reactor: set local_engine after it is fully initialized

- include/seastar/core/reactor.hh
- src/core/reactor.cc
- src/core/reactor_backend.cc
- src/core/reactor_backend.hh
this change consolidates the 3 pollfn classes into a single one.
this allows the backend to customize the way how the requests
are submitted, and how responses events are collected. for instance,
io_uring backend can submit and wait for events with a single syscall,
so a single place to do polling would make this possible.
in a follow-up change, we will move the part in the poller closer to
backend into backend.
> reactor: merge pollfn on I/O paths into a single one

- include/seastar/core/internal/poll.hh
- include/seastar/core/reactor.hh
- src/net/net.cc
- src/net/virtio.cc
The pollers concept is indeed internal, but is kept in reactor.hh which is (still) a public header. Fortunately, the class poller and make_pollfn<>() helper can be both moved to internal/poll.hh and the latter header can be removed from reactor.hh without pain at all.
> Keep pollers in internal/poll.hh

- CMakeLists.txt
- include/seastar/core/future.hh
- include/seastar/core/shard_id.hh
- include/seastar/core/smp.hh
- src/core/future.cc
- tests/unit/futures_test.cc
Assert that the future state is accessed only
on the shard on which it was created as the future
and promise objects are not designed to be accessed
across shards.
For example, currenty, if promise.set_value() (or
set_exception) is called on a promise from a foreign
shard the promise.get_future() continuation would
run on the foreign shard.
Fixes scylladb/seastar#1563
> future: future_state_base: assert owner shard in debug mode

- include/seastar/core/file.hh
> file: Remove reactor class friendship

- .circleci/config.yml
- docker/dev/Dockerfile
since we only support the latest two major releases of compilers. at the moment of writing, Clang just released v16, and the latest major release of GCC is v13.
so we should install them respectively.
because ubuntu kinetic does not ship clang-16. we need to bump up the base image from ubuntu:kinetic to ubuntu:lunar despite that lunar is not an LTS release. we should use ubuntu 24.04 once it's out.
see also 80969ef9ffc10bb219bd3ef83ab76c2c536de7ec, which bumped the compilers also.
Closes scylladb/seastar#1630
[avi: update toolchain]
> docker: bump up to clang {15,16} and gcc {12,13}

- configure.py
so that we can configure CMake to enable C++20 modules support with `configure.py`.
this enables us to build and test with C++20 modules support in our CI, which utilizes configure.py to drive cmake.
> build: add "--enable-cxx-modules" option to configure.py

- .circleci/config.yml
add one more build with the combination of "clang++16", C++20, release with DPDK enabled. so that we can at least test with DPDK build without doubling the size of the test matrix.
> circleci: build with dpdk enabled

- configure.py
to make `configure.py` more readable, clean it up a little bit.
> build: cleanups configure.py to be more PEP8 compatible

- cmake/CxxModulesRules.cmake
since p1689r5 support was included in GCC master. this feature will be available in GCC-14. see
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=024f135a1e9b8f8e102960357cae6e99e1dbe6eb
so let's prepare for it.
> build: enable build C++20 modules with GCC 14

- src/seastar.cc
core/prefault.hh should be added to the global module fragment. otherwise we would have:
```
/home/kefu/dev/seastar/src/core/smp.cc:169:11: error: incomplete type 'seastar::internal::memory_prefaulter' named in nested name specifier
169 | internal::memory_prefaulter::memory_prefaulter(const resource::resources& res, memory::internal::numa_layout layout) {
| ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```
> seastar.cc: include "core/prefault.hh"

- src/CMakeLists.txt
- src/seastar.cc
before this change, SEASTAR_COROUTINES_ENABLED is defined in seastar.cc so all the headers includes in it are aware that coroutine should be enabled. but we now have a .cc file which conditionalize on this macro as well: src/core/file.cc check SEASTAR_COROUTINES_ENABLED for enabling the
make_list_directory_generator() function.
in non-modules build, this macro is defined by util/std-compat.h, we could include this header file in file.cc in its global purview, but unfortunately, std-compat.h also exposes symbols like `seastar::compat::source_location` as a part of the seastar module, which cannot be included by global purview. so, to enable the build with C++20 module enabled, and to avoid redefinition of this macro, let's define it in the building system, as we assume that C++20 module …
> build: define SEASTAR_COROUTINES_ENABLED for Seastar module

- CMakeLists.txt
- cmake/SeastarDependencies.cmake
in 6d2b0a72, Finducontext.cmake was introduced to find libucontext if necessary. and ucontext::ucontext was added as yet another linkage of Seastar::seastar if Seastar is built in Release mode as one of its INTERFACE_LINK_LIBRARIES. but we failed to install Finducontext.cmake along with the Seastar's module config file. so, if user configure the building system for an application with a Seastar installed into the system, cmake would fail like:
```
CMake Warning (dev) at /home/ubuntu/.local/lib/cmake/Seastar/SeastarTargets.cmake:61 (set_target_properties):
Policy CMP0028 is not set: Double colon in target name means ALIAS or
IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
Use the cmake_policy command to set the policy and suppress this warning.
The link interface of …
```
> build: install Finducontext.cmake and FindSystem-SDT.cmake

- .circleci/config.yml
the job's with_dpdk is off by default, so no need to specify it explicitly.
> circleci: do not set disable dpdk explicitly

- src/core/memory.cc
- tests/unit/CMakeLists.txt
- tests/unit/app-template_test.cc
in the release build, we use Seastar allocator, but the Seastar application
can still configure `smp_opts.memory_allocator` with `memory_allocator::standard`.
in that case, the `memory::configure()` is not called, hence `cpu_mem_ptr` is not
set.
but in the constructor of `reactor`, it is supposed to setup per-reactor
facilities, notably the ones backed by TLS variables, including the
memory subsystem. but we are not able to access the `smp_opts` anymore
in `reactor::reactor()`. because the memory subsystem is configured in
`smp::configure()`, where is `smp_opts` passed in.
so, in this change
* instead of conditionally calling
`memory::set_reclaim_hook()` in `reactor::reactor()` based on the
value of `smp_opts.memory_allocator`, we check for null in
`memory::set_reclaim_hook()`. …
> memory: do not set_reclaim_hook if cpu_mem_ptr is not set

- include/seastar/rpc/rpc_types.hh
{fmt} v10 is less tolerant than {fmt} v9, so let's add a proper formatter for rpc::optional<T>
> rpc/rpc_types: add formatter for rpc::optional<T>

- src/core/exception_hacks.cc
- src/core/reactor.cc
- tests/unit/CMakeLists.txt
- tests/unit/app-template_test.cc
this series enables us to run multiple `seastar::app_template` instances sequentially in a single process. this is a false requirement in production, as we don't launch seastar app multiple times in a single process. but this is handy if we want to test, for instance, app_template in a single test process, where we need to start multiple app_template instances one after another.
> core: enable seastar to run multiple times in a single process

- include/seastar/http/exception.hh
- src/http/routes.cc
- tests/unit/httpd_test.cc
- The redirect_exception is hard coded for permanent move status. In Redpanda we also have cases where we need to use temporary redirect, which has the same Location header but different http status. This PR allows the status code to be customized for the redirect_exception.
- Additionally, this PR handles redirect for thrown from future returned from handler. Previous the redirect was only handled when returned from the synchronous code inside handler.
- Adds test for redirect_exception
> httpd: support temporary redirect from inside async reply

- CMakeLists.txt
- cmake/SeastarDependencies.cmake
- cooking_recipe.cmake
- include/seastar/core/prometheus.hh
- install-dependencies.sh
- pkgconfig/seastar.pc.in
- src/core/prometheus.cc
- src/http/mime_types.cc
This PR is based on PR #1518 and includes an additional commit that adds a flag to the Prometheus configuration object disabling protobuf by default.
The original PR #1518  resurrected the protobuf support that was removed in 8ed9771ae98130d5adbccdaea4ecbac738170939.
The motivation is the experimental Prometheus protobuf with native histogram support. After this series, it will be possible to adopt Prometheus protobuf support to the newer feature of the text representation and add Prometheus native histogram support.
> Bringing back Prometheus protobuf support

- src/core/reactor.cc
instead of printing to std::cerr, let's be more consistent and use `seastar_logger.error(...)` when printing fatal errors.
> reactor: print fatal error using logger as well

- README-DPDK.md
DPDK has renamed `setup.sh` to `dpdk-setup.sh`, and later dropped it in v20.11. while in latest Seastar we point the dpdk submodule to a fork based on v23.07 .
also, the igb_uio kernel module was moved out of dpdk. and vfio-pci is the recommended kernel driver to work with the userspace PMD drivers. see https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html
and DPDK's quick start guide also covers the step to configure hugepage.
so, let's update the document and point user to DPDK's document, which is more updated.
> README-DPDK.md: point user to DPDK's quick start guide

- src/CMakeLists.txt
- src/seastar.cc
in 6bdef1e4319fcc3af078844c2c2ed57f7a6debf3, Crypto++ was dropped, and later the updated build image removed it as well. but it still exists in seastar.cc and src/CMakeLists.txt, let's drop them as well.
> seastar.cc: replace cryptopp with gnutls when building seastar modules

- .circleci/config.yml
- src/CMakeLists.txt
- src/core/alien.cc
- src/seastar.cc
add one more build with the combination of "clang++17", C++20, debug with C++20 modules enabled. so that we can at least test with C++20 modules build without doubling the size of the test matrix.
> circleci: build with C++20 modules enabled

- CMakeLists.txt
use the new behavior defined by CMP0155, so that when creating the building system with CMake 3.28 and up, the rules are generated to scan the targets for imports when C++20 standard is used.
without this change, when compiling C++20 modules with CMake 3.28, the modmap and related targets are not generated, hence when building the compilation units for the implementation of the "seastar" module, they cannot find the "seastar" module.
after this change, the corresponding rules are generated.
please note, unlike other policies, the new behavior adds a step to can the imported modules when building a compilation unit. but quite a few Seastar application do not use C++ modules yet. so unlike other CMake policies, we only enable CMP0155 when C++20 modules is enabled to avoid the build-time …
> build: use new behavior defined by CMP0155 when building C++ modules

- CMakeLists.txt
- include/seastar/rpc/rpc.hh
- include/seastar/util/log.hh
- src/core/reactor.cc
- src/util/log.cc
- tests/unit/exception_logging_test.cc
[util/log, rpc, core: use compile-time formatting with fmtlib >= 8.0](https://github.com/scylladb/seastar/pull/1196/commits/6020f4e64388cbb9aeb9e5dbc3d5aeb7e0036dbe)
fmtlib v8.0.0 comes with compile-time formatting and more importantly,
compile-time format string checking.
see https://github.com/fmtlib/fmt/releases/tag/8.0.0 .
in order to take advantage of this feature, and keep the backward
compatiblity with following use cases::
1. Seastar applications which still need to compile with {fmt} < 8.0.0
2. Seastar applications which compile with {fmt} > 8.0.0, but still
want to use runtime format strings without constructing the format
string with `fmt::runtime()` explicitly.
a new option named `Seastar_LOGGER_COMPILE_TIME_FMT` is introduced. this
option is enabled by default if {fmt} >= …
> core, util, rpc: enable compile time format checking

- include/seastar/util/log.hh
despite that it is a public function, the removed function is an internal function as per its comment suggest. since it's not used anywhere, let's drop it.
> util/log: drop unused function

- NOTICE
- include/seastar/core/memory.hh
- include/seastar/core/reactor_config.hh
- include/seastar/util/backtrace.hh
- include/seastar/util/sampler.hh
- src/core/memory.cc
- src/core/reactor.cc
- tests/perf/CMakeLists.txt
- tests/perf/allocator_perf.cc
- tests/unit/CMakeLists.txt
- tests/unit/alloc_test.cc
This series changes the existing heap profiling to support a sampling mode, added
by @StephanDollberg and includes also some optimizations of the allocation fast paths.
The following description of the sampling profiler comes from Stephan:
Instead of tracking every allocation, it will track a sampled subset of allocations. This
is useful for profiling in production systems where the overhead of tracking every
allocation is too high.
A sample is taken at a set sample rate which feeds into an exponential
distribution. Hence we avoid falling into patterns that would potentially make
the profile biased otherwise. This approach is inspired by the android heapprofd
memory profiler.
By adjusting the sample rate it's possible to tune the overhead of the memory
profiler. The idea is to make this …
> Add sampling memory profiler mode

- src/core/memory.cc
in 477827b841, we started using `SEASTAR_CONCEPT` in core/memory.cc. but we failed to include the header providing this macro. this breaks the build of seastar C++ module, which requires the .cc file to be self-contained. the failure looks like:
```
FAILED: src/CMakeFiles/seastar-module.dir/core/memory.cc.o
/usr/bin/clang++-17 -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_COROUTINES_ENABLED -DSEASTAR_MODULE -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -Dseastar_module_EXPORTS -I/home/circleci/project/include -I/home/circleci/project/build/debug/gen/include -I/home/circleci/project/src -g -std=c++20 -fPIC -U_FORTIFY_SOURCE -MD -MT src/CMakeFiles/seastar-module.dir/core/memory.cc.o -MF src/CMakeFiles/seastar-module.dir/core/memory.cc.o.d …
```
> memory: include used header

- src/CMakeLists.txt
-Winclude-angled-in-module-purview was introduced in clang 18 to complain if the compiler spot something like `"#include <filename>"` in the module purview. as it is a signal that the purview is exposing something which does not belong to it.
but in Seastar, we include the public Seastar headers using angled bracket also, so this warning does not apply to us. as an exception, we _could_ include headers using quotes instead of angled brackets in seastar.cc, as we don't redistribute this source file as a header, so `#include "seastar/foobar.hh"` does not give user an impression that we are including an in-project file. but this does not address the whole problem, because we have other headers including headers using angled bracket in their module purview.
so, let's silence this warning at …
> build: silence the waring of -Winclude-angled-in-module-purview

- src/core/reactor.cc
- src/json/json_elements.cc
- src/net/inet_address.cc
- src/net/ip.cc
- tests/unit/exception_logging_test.cc
this change replace some `format()` calls with `fmt::format()`.
before this change, we use `format()` when formatting to an sstring and when formatting to an std::string.
the upside of this design is that we don't need to differentiate the calls where an sstring is expected from those where an std::string is expected.
but the downside is that we create an `std::string` by deep copy the content of sstring after formatting the parameters and then drop the `sstring` on the floor in the second use case, where only an std::string is expected.
another potential problem is that there are actually three `format()` functions. they are from three different namespaces: `seastar`, `std` and `fmt` in C++20. currently, the `seastar::format()` one wins in the function loopup. because the other two are …
> treewide: s/format/fmt::format/ when appropriate

- include/seastar/core/print.hh
- src/core/reactor.cc
`fmt::join()` is a better alternative than `format_separated()`. because Seastar should focus on what it is good at instead of trying to help resolving all the problems.
in this changeset, we replace the only caller site of this function with `fmt::join()`, and mark `format_separated()` deprecated.
> print: deprecate format_separated() 

- src/json/json_elements.cc
- src/net/ip.cc
4654cab8 broke the C++ modules build, as it failed to include the used header of fmt/core.h. and the build fails like:
```
seastar/src/json/json_elements.cc:84:60: error: missing '#include <fmt/core.h>'; 'format' must be declared before it is used
84 |             std::throw_with_nested(std::runtime_error(fmt::format("Json generation failed for field: {}",element->_name)));
|                                                            ^
/usr/include/fmt/core.h:2815:31: note: declaration here is not visible
2815 | FMT_NODISCARD FMT_INLINE auto format(format_string<T...> fmt, T&&... args)
|                               ^
1 error generated.
```
in this change, fmt/core.h is included when necessary.
> src: include used headers for C++ modules build

- CMakeLists.txt
- pkgconfig/seastar.pc.in
before this change, we don't expose compiling option like `-std=c++20` if Seastar is configured with `-DCMAKE_CXX_STANDARD=20`, and the Seastar application which consumes Seastar via seastar.pc should specify its compiling option by itself. while the CMake config file of Seastar exposes the C++ standard using
```
target_compile_features(seastar
PUBLIC
cxx_std_${CMAKE_CXX_STANDARD})
```
this allows the Seastar application consuming Seastar via its CMake config file to use the compile flags exposed by this setting.
after this change, users of seastar.pc will be able to have the `-std=c++20` included the cflags exposed by
`pkgconfig --cflags seastar`.
> build: expose flag like -std=c++20 via seastar.pc

- CMakeLists.txt
263cd37d introduced a regression which tried to install a non-existant file -- cmake/FindProtobuf.cmake.
since this FindProtobuf.cmake is shipped by CMake since 3.13, and our minimal required version of CMake 3.13, there is no need to vendor this file.
so, in this change, we don't install this file.
Fixes #2041
> build: do not install FindProtobuf.cmake

- include/seastar/net/posix-stack.hh
in 8b9ae36b, we started to use `std::unordered_set` in `include/seastar/net/posix-stack.hh`, but we failed to include the used header. this breaks the `checkheaders` check.
so, in this change, let's include the userd header.
> net/posix: include used header

- include/seastar/core/future.hh
- tests/unit/futures_test.cc
in `uninitialized_wrapper_base::uninitialized_set()`, we initialize
the value of a future using
```c++
new (&_v.value) maybe_wrap_ref<T>{T(std::forward<U>(vs)...)};
```
this has been working fine even if `T` provides a constructor
accepting a C++20 range -- the move constructor is picked as
expected.
but the lastest clang (920bb5430a96c346f7afcbe288e3546513b58012)
starts trying to match the constructor of `maybe_wrap_ref<T>`
which accepts a C++20 range, and fails like:
```
/home/kefu/dev/scylladb/utils/chunked_vector.hh:110:38: note: in instantiation of function template specialization 'utils::chunked_vector<int>::chunked_vector<__gnu_cxx::__normal_iterator<const utils::chunked_vector<int> *, std::vector<utils::chunked_vector<int>>>>' requested here
110 |     chunked_vector(const Range& …
```
> future: use "(T(...))" instead of "{T(...)}" in uninitialized_set()

- apps/io_tester/io_tester.cc
This PR contains pre-work for request_type::unlink.
In case of the new operation a given number of files will
be created during startup. To avoid code duplication some
common parts of the code have been extracted into separate
free functions.
Refs: scylladb#1299
> io_tester: prework for request_type::unlink

- CMakeLists.txt
- pkgconfig/seastar.pc.in
the option of `-Wno-error=#warnings` is added to address the FTBFS when the compiler runs into `#warning` preprocessor, and fails because it takes warning as errors. but we only use `#warning` in the internal header/source files. we even filter out `-Wno-error=#warnings` in 83339edb. this is another proof that this compile option is not necessary to be a public of the public interface of Seastar.
but we still expose this option when the Seastar application is still consuming Seastar via CMake. this causes discrepancies between the public compiling options of Seastar applications.
so, in this change, we
* mark `-Wno-error=#warnings` one of the private compile option instead.
* revert 83339edb
with this change, we
* reduce the differences between the compiling options exposed by seastar.pc …
> build: do not expose -Wno-error=#warnings

- include/seastar/core/future.hh
seastar::make_ready_future requires a template parameter when
constructing being used due to the default of `void` and supporting
in place construction. Common usage (at least in Redpanda) is
to create a fully formed future from an already constructed struct.
Example with `seastar::make_ready_future`:
```
seastar::future<ss::sstring> foo() {
ss::sstring str = compute_foo();
return seastar::make_ready_future<ss::sstring>(std::move(str));
}
```
Using `seastar::as_ready_future`:
```
seastar::future<ss::sstring> foo() {
ss::sstring str = compute_foo();
return seastar::as_ready_future(std::move(str));
}
```
> core/future: add as_ready_future utility

- include/seastar/net/api.hh
- src/core/reactor.cc
Currently, Unix domain sockets are created with default permissions 755.
Add a new attribute to the listen_options struct to enable changing these permissions.
> net/posix: add a way to change file permissions of unix domain socket

- include/seastar/core/circular_buffer.hh
- tests/unit/circular_buffer_test.cc
this pr makes circular_buffer::iterator default constructible, 
It is needed to make circular_buffer a regular range.
this check is added to circular_buffer_test.cc as a compile-time test:
```cpp
static_assert(std::ranges::range<circular_buffer<int>>);
```
> circular_buffer: make the iterator default constructible

- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
- src/core/reactor.cc
Here's the sched throttling math:
bw/bw_max + iops/iops_max <= C
The "rate_factor" is the C and it's usually set to be 1.0, but there was a reservation for convex/concave io profiles where the C would be set to lower or higher values to adjust the limit.
The same goal can be achieved by scaling ..._max values on the right side of the equation, like this
bw/(bw_max*C) + iops/(iopx_max*C) <= 1.0
This makes the fair-queue code a bit simpler and, as a nice side effect, adds sanity check for the rate-factor not been too low.
> io: Apply rate-factor early

- apps/io_tester/io_tester.cc
Currently io-tester just exits in this case, but it's a testing app, it doesn't need to be smarter than whoever uses it, so a WARNING should be enough.
> io_tester: Allow running on non-XFS fs

- doc/lambda-coroutine-fiasco.md
"This document" is a singular subject, so let's use singular verb by adding "s" to the base form of the verb.
> doc/lambda-coroutine-fiasco: fix a syntax error

- include/seastar/coroutine/exception.hh
before this change, the doxygen comment above `return_exception_ptr()` is for `return_exception()`, which was marked deprecated. so the document does not apply anymore. so, in this change:
* move the comment for `return_exception()` down to where it belongs
* add the comment for `return_exception_ptr()`, and add a real-life example for it.
* replace the references to "return_exception" with "return_exception_ptr". as the former has been deprecated in favor of the latter.
> coroutine/exception: document return_exception_ptr()

- .circleci/config.yml
- docker/dev/Dockerfile
to address the build failure caused by
https://github.com/llvm/llvm-project/issues/59827, and to test the build with C++23, we need to use clang-18. which will be released in March 2023.
> docker: install clang-tools-18

- .circleci/config.yml
- CMakeLists.txt
- configure.py
C++23 has passed all the ballots [1]. We can therefore support it now formally. This means that C++17 is no longer supported, and C++20 is supported until C++26 is released.
The primary benefit of C++23 support is that we can now use coroutines in core Seastar code, as all supported C++ versions have them.
[1] https://lists.isocpp.org/std-proposals/2024/01/8880.php
> Update supported C++ standards to C++23 and C++20 (dropping C++17)

- src/core/file.cc
It's an argument lost by 95a7ff9989 from one of its draft implementations
> file: Remove unused thread-pool arg from directory lister

- src/core/reactor.cc
Preprocessor conditionals (#if, #ifdef) in the middle of a function body make code harder to read and logic harder to follow. This patch re-ifdefs some of them to produce specific or stub implementations for different if/else cases. The compiler is good at not generating any code for stub calls.
> Avoid some in-code ifdefs in reactor.cc

- apps/io_tester/io_tester.cc
- include/seastar/core/abort_source.hh
- include/seastar/core/checked_ptr.hh
- include/seastar/core/execution_stage.hh
- include/seastar/core/fair_queue.hh
- include/seastar/core/io_priority_class.hh
- include/seastar/core/reactor_config.hh
- include/seastar/core/sstring.hh
- include/seastar/core/timer-set.hh
- include/seastar/core/with_scheduling_group.hh
these unused includes were identified by clangd. see https://clangd.llvm.org/guides/include-cleaner#unused-include-warning for more details on the "Unused include" warning.
> include: do not include unuser headers

- include/seastar/core/alien.hh
- include/seastar/core/file.hh
- include/seastar/core/future.hh
- include/seastar/core/shared_mutex.hh
- include/seastar/coroutine/parallel_for_each.hh
- include/seastar/http/client.hh
- include/seastar/util/closeable.hh
- src/http/client.cc
so that the template definition is more compact.
> treewide: put std::invocable<> constraints in template param list

- include/seastar/core/iostream-impl.hh
- include/seastar/core/iostream.hh
Currently `read_exactly_part` (found in the iostream-impl.hh header) uses recursion, which can lead to stack overflow. This commit rewrites `read_exactly_part` into a coroutine that does not use recursion. Fixes https://github.com/scylladb/seastar/issues/202
> Replace recursion by iteration in input_stream::read_exactly_part

- tests/unit/sstring_test.cc
now that we've dropped C++17 support in 01257e6058, there is no need to check `__cplusplus > 201703L`, as it's always true now.
> test/unit: do not check if __cplusplus > 201703L

- HACKING.md
unfortunately, tests/dist was removed in d8b73851c2. so the document referencing it is now outdated. so let's drop it.
> HACKING.md: remove doc related to test_dist

- scripts/seastar-json2code.py
this change refactors `seastar-json2code.py` by splitting `create_h_file()` into smaller pieces, and also reformats the rendered code with better formatting.
Refs #2082
> seastar-json2code: reformat the rendered code and cleanups 

- include/seastar/core/metrics_api.hh
- src/core/metrics.cc
We've run into an oversized allocation (over 1MB) coming from the metrics subsystem. A snippet of the backtrace is seen below:
```
(inlined by) std::__1::__split_buffer<seastar::metrics::impl::metric_value, std::__1::allocator<seastar::metrics::impl::metric_value>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<seastar::metrics::impl::metric_value>&) at /vectorized/llvm/bin/../include/c++/v1/__split_buffer:323
(inlined by) std::__1::vector<seastar::metrics::impl::metric_value, std::__1::allocator<seastar::metrics::impl::metric_value>>::reserve(unsigned long) at /vectorized/llvm/bin/../include/c++/v1/vector:1503
(inlined by) seastar::metrics::impl::get_values(int) at /v/build/v_deps_build/seastar-prefix/src/seastar/src/core/metrics.cc:422
auto …
```
> metrics: change value_vector type to std::deque

- doc/rpc.md
- include/seastar/rpc/multi_algo_compressor_factory.hh
- include/seastar/rpc/rpc_types.hh
- src/rpc/rpc.cc
- tests/unit/rpc_test.cc
In some situations, we might want to re-negotiate some parameters of RPC compression. For example, a fancy streaming compressor might want to shrink the compression context of the connection to reclaim some memory for other, more important connection that just came up.
But for that, there needs to be some way for the two compressors to communicate with each other, in finite time. Currently, there is no such way. Compressors can send messages to each other by simply prepending them to the actual RPC frames, but there never is a guarantee that an actual RPC frame will be sent anytime soon.
This patch adds a mechanism which allows compressors to communicate. For each RPC connection, it spawns a worker fiber which listens on a condition_variable (passed to the compressor's constructor), and …
> rpc: add a way for compressors to send something to their peer

- src/core/prometheus.cc
in newer C++ language binding of protobuf, `ArenaStringPtr::Set()` accepts both `std::string` and `std::string_view`, while the C++ lanaguage binding genereated by protoc just fowrard the type of the parameter, so if the parameter is a `sstring`, we would run into FTBFS like
```
seastar/build/release/gen/src/proto/metrics2.pb.h:2891:20: error: call of overloaded ‘Set(const seastar::basic_sstring<char, unsigned int, 15>&, google::protobuf::Arena*)’ is ambiguous
2891 |   _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
|   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/arenastring.h:478:22: note: candidate: ‘void google::protobuf::internal::ArenaStringPtr::Set(const std::string&, google::protobuf::Arena*) [with …
```
> prometheus: avoid ambiguity when calling MetricFamily.set_name()

- include/seastar/core/shard_id.hh
The seastar/core/shard_id.hh header does not import other headers, but it requires SEASTAR_MODULE_EXPORT_BEGIN and SEASTAR_MODULE_EXPORT_END macros which are defined in seastar/util/modules.hh.
Make the header self-contained by adding the missing import.
> include: add missing modules.hh import to shard_id.hh

- include/seastar/util/log.hh
- src/util/log.cc
before this change, we rely on the default-generated fmt::formatter
created from operator<<, but fmt v10 dropped the default-generated
formatter.
in this change, we define formatters for `seastar::log_level`, its
operator<< is preserved for backward compatibility.
Refs https://github.com/scylladb/scylladb/issues/13245
> util/log: add formatter for log_level

- src/core/reactor_backend.cc
When encountering an `io_submit` error in the `storage_context` we call
`handle_aio_error` to handle said error.
First we check for `EAGAIN` and `EBADF` and handle those separately.
For other errors we would call `throw_system_error_on` to throw an
exception.
This was bugged because `throw_system_error_on` reads errno directly
which means it might potentially print the wrong error code as errno
might have changed from the error code that we passed to
`handle_aio_error`. This can happen in the aio systemcall fallback
thread where the io_submit error is handled only later after possibly
suspending.
To fix this we just throw an exception in `handle_aio_error` directly
and pass the correct error code.
`throw_system_error_on` checks for a condition but we pass `true`
unconditionally. Further …
> reactor: Print correct errno on io_submit failure

- tests/unit/rpc_test.cc
This change fixes compilation issue that was
visible on Linux Ubuntu 22.04 in release mode.
The code uses types and functions defined in
span header.
> Add missing include in tests/unit/rpc_test.cc

- apps/io_tester/conf.yaml
- apps/io_tester/io_tester.cc
- doc/io-tester.md
This change introduces request_type::unlink as well
as unlink_class_data to io_tester. It also extends
the creation of operations to be executed to recognize
the new request type.
The purpose of this change is to enable io_tester to
analyze the impact of unlink operations on read and
write operations.
unlink_class_data creates a given number of files
during startup. When requests are issued it calls
unlink on the created files.
Refs: scylladb#1299
> io_tester: implement request_type::unlink

- include/seastar/core/reactor.hh
- src/core/reactor.cc
It's set when reactor start running tasksk from that queue and unset when reactor stops doing it. The bit is unly used by scylla-gdb script, but active/inactive status of the queue can be found out with the help of current_scheduling_group_ptr
> reactor: Remove write-only task_queue._current

- src/core/reactor.cc
- src/core/scollectd.cc
The scollectd_impl global and get_impl() method somehow happened in reactor.cc while there's a dedicated scollectd.cc file for that stuff
> reactor: Move pieces of scollectd to scollectd

- include/seastar/net/tls.hh
- src/net/tls.cc
this change addresses the formatting with fmtlib v10, which stopped creating the default-generated formatter even if FMT_DEPRECATED_OSTREAM preprocess macro is defined. so to enable Seastar applications to print tls::subject_alt_name using {fmt} without defining the formatter by themselves, we provide the formatter for this class in Seastar.
Refs https://github.com/scylladb/scylladb/issues/13245
> tls: add fmt::formatter for tls::subject_alt_name

- CMakeLists.txt
- cmake/SeastarDependencies.cmake
as higher versions of Protobuf does not claim to be compatible with
v2.5.0, so we should not specify a version number which is acceptable
by Seastar as a parameter of `find_package()`. and instead, we just
check the version number after calling `find_package()` in config mode.
if we find the package using config mode, we search it again, for
printing out the version number to the stdout, otherwise we search
using its C++ API version.
Refs ##2113
> build: relax the version constraint for Protobuf

- include/seastar/core/metrics_api.hh
- include/seastar/core/relabel_config.hh
- src/core/metrics.cc
- tests/unit/metrics_test.cc
This series adds metrics family config.
Family config is a configuration that relates to all metrics with the same name but with different labels.
set_metrics_family_configs allows changing that configuration during run time. Specifically, change the label aggregation based on a metric name.
Using multiple independent labels on the same metric is a common practice. A known drawback is that this cartesian product makes it easy to discover in real-time that the number of metrics explodes.
While metrics relabel config allows dropping some of those metrics, it could be useful to report an aggregated metric.
The following is an example for setting the aggregate labels for the metric test_gauge_1 and all metrics matching the regex test_gauge1.*
```
std::vector<sm::metrics_family_config> fc(2); …
```
> Adding Metrics family config

- include/seastar/core/memory.hh
- src/core/memory.cc
- src/core/reactor.cc
- src/core/smp.cc
- tests/unit/app-template_test.cc
Fixes #2148
When using the seastar allocator, there are numerous implicit reliances on cpu_mem_ptr having been set up. Previously, this just happened to be true, due to #2137.
Fixed by adding a minimal memory setup call to smp::configure, even if using non-seastar allocator reactor options (not compile flags).
Fixed the test for the feature (allocator options) so that it 
* Actually runs. regardlerss of dpdk
* Actually catches the issue
> memory: Ensure thread locals etc are minimally initialized even with non-seastar reactor options for alloc

- include/seastar/core/abort_source.hh
this change addresses the formatting with fmtlib < 10, and without `FMT_DEPRECATED_OSTREAM` defined. please note, in {fmt} v10 and up, it defines formatter for classes derived from `std::exception`, so our formatter is only added when compiled with {fmt} < 10.
Refs https://github.com/scylladb/scylladb/issues/13245wip
> abort_source: add fmt::formatter for abort_requested_exception

- scripts/perftune.py
we use, for instance '\s' and '\S' in regular expressions, in which '\s' is a two-char string, but not one of the escaped sequences defined by
https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
despite that CPython just considers "\s" as "\\s" like a two-char string. but if we run the script in developer mode using `python3 -Xdev`, it'd warn us like:
```
DeprecationWarning: invalid escape sequence '\S'
```
this change
* use `r` prefix when appropriate
* escapes the "\" manually otherwise.
> scripts: use raw string to avoid invalid escape sequences

- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
- tests/unit/io_queue_test.cc
Both, io_queue and io_group, keep vectors with fair_... counterparts. Both use different containers for that, but static_vector works and suits better for both. More details are in individual patches.
> Use staic_vector-s to keep fair_queue-s and fair_group-s

- include/seastar/core/metrics_api.hh
- src/core/metrics.cc
This PR reverts d2929c2ade5bd0125a73d53280c82ae5da86218e.
The optimization added in that patch broke the independence between the currently registered metrics and the reported metrics.
The metric layer takes a snapshot of the registered metrics before start reporting and will report that snapshot even if metrics are added or removed during that reporting time.
This is the expected behavior, making all the metrics values to be reported automatically.
Because the two data structures are now independent (_value_map that holds the registered metrics by name and _metadata that holds the meta-data optimized for reporting), set_metric_family_configs should now change both of them.
Fixes #2184
> Revert remove duplicate of metric family

- src/core/metrics.cc
This series addresses two corner cases in the metrics layer:
1. use the addition operator on a Summary; while this does not make sense, a user may still choose to do that; it should not throw an exception and treat the summary as a histogram.
2. There could be a situation when calling set_metric_family_configs while the _metadata object does not exist, either because it was not created yet or because it was deleted and not re-created. In this situation, we should leave it to the next time the _metadata will be created.
Fixes #2191
> Add Safety to the metrics layer

- include/seastar/http/common.hh
- include/seastar/http/request.hh
- include/seastar/http/url.hh
- src/http/file_handler.cc
- src/http/request.cc
- src/http/url.cc
- tests/unit/httpd_test.cc
Some REST APIs of Redpanda were incorrectly using the `seastar::http::internal::url_decode` method to url decode path parameters, ignoring the subtle difference between the rules of query parameter decoding and path parameter decoding. This caused issues for Redpanda's clients as they were unable to delete users that had a '+' in the username.
As part of solving this decoding problem, we introduced a `path_decode` method similar to seastar's `url_decode`, and it would be most convenient if this method lived next to the existing `url_decode` utility method that seastar provides both to enable code reuse and to bring it to users' attention that they should make a conscious choice between the two decode methods.
To make this even easier, this PR also adds the `get_path_param` convenience …
> http: path parameter parsing convenience methods

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/tls_test.cc
Fixes #2154
TLS1.3 session tickets are a client-storage solution for session resume, bypassing some of the more expensive parts of a normal handshake.
Implemented by adding an optional session data parameter to tls_options, options to certificates for server keys, and query
functions for state/session data on the client side.
Note that the feature requires both client and server to handle tls1.3.
Server session keys are kept in the certificates object, and can be rotated by simply re-enabling the feature on the object.
Reloadable certificates will rotate keys on cert reload.
Simple test included.
> TLS: Add support for TLS1.3 session tickets

- tests/unit/tls_test.cc
`future::get0()` was deprecated. so let's use `future::get()` instead. this addresses following build failure:
```
FAILED: tests/unit/CMakeFiles/test_unit_tls.dir/tls_test.cc.o
/usr/bin/g++-13 -DBOOST_ALL_DYN_LINK -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEBUG -DSEASTAR_DEBUG_PROMISE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_SSTRING -DSEASTAR_TESTING_MAIN …
```
> tls: s/get0()/get()/

- src/net/tls.cc
when compiling the tree with GCC, it warns like:
```
[77/92] Building CXX object CMakeFiles/seastar.dir/src/net/tls.cc.o
/var/ssd/seastar/src/net/tls.cc:342:5: warning: definition of implicit copy assignment operator for 'gnutls_datum' is deprecated because it has a user-provided destructor [-Wdeprecated-copy-with-user-provided-dtor]
342 |     ~gnutls_datum() {
|     ^
/var/ssd/seastar/src/net/tls.cc:425:33: note: in implicit copy assignment operator for 'seastar::gnutls_datum' first required here
425 |             _session_resume_key = {};
|                                 ^
```
it rightly pointed out that we are using an implicitly defined copy assignment operator of `gnutls_datum`. since the lhs operator of the assignment operator could contain a resource which is supposed to be freed …
> tls: add assignment operator for gnutls_datum

- CMakeLists.txt
In ef941e5, we replaced the `-Wdeprecated-declarations` flag by `-Wdepracted` and` -Wno-error=deprecated`. Unfortunately, GCC and Clang interpret `-Wdeprecated` differently, compare:
* https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Warning-Options.html#index-Wno-deprecated
* https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Deprecated-Features.html
and
* https://clang.llvm.org/docs/DiagnosticsReference.html#wdeprecated
As a result, `-Wno-error=deprecated` doesn't prevent GCC from turning warnings related to using functions, variables, or types marked as deprecated into errors. Clang, however, does that.
In this commit, we conditionally enable the intended options depending on which compiler is used.
> CMakeLists.txt: Apply CXX deprecated flags conditionally

- include/seastar/core/abort_source.hh
- include/seastar/core/sstring.hh
- include/seastar/core/timed_out_error.hh
- include/seastar/net/tls.hh
- include/seastar/rpc/rpc_types.hh
- include/seastar/util/lazy.hh
- include/seastar/util/optimized_optional.hh
before {fmt} v10, it provides the specialization of `fmt::formatter<..>` for `std::string_view` as well as the specialization of `fmt::formatter<..>` for `fmt::string_view` which is an implementation builtin in {fmt} for pre-C++17 compatibility. but this type is used even if the code is compiled with C++ stadandard greater or equal to C++17. also, before {fmt} v10, `fmt::formatter<std::string_view>::format()` is defined so it accepts `std::string_view`. that's why we can define a `fmt::formatter<Type>` for a custom type by inheriting from `fmt::formatter<std::string_view>`, and call the parent class's `format()` method by passing a variable convertible to `std::string_view`.
after v10, `fmt::formatter<std::string_view>` still exists, but it is now defined using a macro named …
> treewide: inherit from formatter<string_view> not formatter<std::string_view>

- scripts/seastar-json2code.py
this change paves the road to https://github.com/scylladb/seastar/issues/2082. so that we can store more
properties in the Parameter class in this python script and then
translate them into a C++ class which is used to verify and expose
the content and schema of a parameter. so that they can be used
in `handler_base::verify_mandatory_params()` in a follow-up
change.
Refs https://github.com/scylladb/seastar/issues/2082
> seastar-json2code: extract Parameter class and cleanups

- apps/iotune/iotune.cc
When performing measurements, iotune uses IO block size that is not-less than the DMA alignment reported by file. This in turn is what XFS reports (spiced with io-properties.yaml numbers, but given it's iotune, these numbers are not making any difference).
Without knowing those values any reasoning on the produced measurements is furtune-telling :(
refs: #1698
> iotune: Print file alignments too

- scripts/seastar-json2code.py
- tests/unit/CMakeLists.txt
- tests/unit/api.json
- tests/unit/json2code_test.py
- tests/unit/rest_api_httpd.cc
this change addresses a regression introduced by
3f534c77, which failed to differentiate the path param from the non-path param, and always prefixed the param with "/".
Fixes 3f534c77d7b47398e582610e03ad08214fce32be
> seastar-json2code: fix the path param handling

- src/core/reactor.cc
lowres_clock promises task_quota resolution, but we forgot to update lowres_clock when first, there's a need to preempt *and* second, max_task_backlog is exceeded. all tasks that follow until backlog reduces below max target, will find lowres_clock with "now" time as of beginning of run_tasks() execution, despite multiple task quotas may have passed since then.
> reactor: update lowres_clock when max_task_backlog is exceeded

- include/seastar/core/weak_ptr.hh
- tests/unit/weak_ptr_test.cc
The patch introduces weak_ptr<T>(weak_ptr<Y>&&) constructor that creates
weak_ptr<T> out of convertible to T* Y's. This has two implications.
First, the main one, is that it's now possible to obtain a constant weak
pointer on an object.
Another, a nice side effect, is: given a base-class we can now create
weak_ptr<base> out of weak_ptr<inherited>.
> weak_ptr: Make it possible to produce constant pointers

- include/seastar/core/shared_mutex.hh
- tests/unit/locking_test.cc
In this PR, we introduce RAII locks for `seastar::shared_mutex`, similar to `seastar::semaphore_units` and `seastar::gate::holder`.
> shared_mutex: Add RAII locks

- CMakeLists.txt
- src/CMakeLists.txt
- src/core/reactor_backend.cc
- src/core/resource.cc
- src/seastar.cc
before this change, when building seastar-module, we don't check for
the enabled features. so, for instance io uring backend is not enabled
even `Seastar_IO_URING` is set.
in this series we
* move `add_subdirectory(src)` down
* `#include` the used header files
* check for the enabled options,
* link against the related libraries, and
* add the required macro definitions
this should enable seastar-module to build with, for instance, io_uring
backend enabled. as `SEASTAR_HAVE_URING` enables this backend when
building `src/core/reactor_backend.cc`.
Fixes https://github.com/scylladb/seastar/issues/2249
> build: support enabled options when building seastar-module

- CMakeLists.txt
quote from
https://patchwork.ozlabs.org/project/glibc/patch/8734v1ieke.fsf@oldenburg.str.redhat.com/
> On the glibc side, we should recommend that intercepting mallocs and its
> dependencies use initial-exec TLS because that kind of TLS does not use
> malloc.  If intercepting mallocs using dynamic TLS work at all, that's
> totally by accident, and was in the past helped by glibc bug 19924.
so instead of allocating TLS variables using malloc, let's allocate them using initial-exec TLS model. another approach is to single out the static TLS variables in the code path of malloc/free and apply `__attribute__ ((tls_model("initial-exec")))` to them, and optionally only do this when we are building shared library.
but this could be overkill as
1. we build static library in the release build
2. …
> build: use initial-exec TLS when building seastar as shared library

- .github/workflows/test.yaml
- .github/workflows/tests.yaml
in order to address the infra issues caused by unreliable connection to llvm's apt repo, and to bring the two missing build combinations back, in this series, we switch from `setup-cpp` action to fedora 40, and extract the test job into a reusable workflow.
> github: build with fedora 40 and add 2 build combinations back

- CMakeLists.txt
- include/seastar/core/sstring.hh
Seastar is an event-driven framework, not a collection of libraries for multiple purposes. also, when migrating to a {fmt} only formatting solution, the operator<< based printers can actually makes our lives more difficult. for instance, Boost.test expects operator<< and fall back to `boost_test_print_type()`, so even if we provide a templated `boost_test_print_type()` which accepts all types which can be formatted with {fmt}, if Boost.test is able to find the operator<<-based formatter for a std::vector, it just picks it, and then hits the brick wall, as the elements in the vector does not provide an operator<<-based formatter.
instead of enabling these operator<<:s to print the element with fmt::formatter support, let's just disable them on user's request.
in this change, a new option …
> sstring: deprecate formatters for vector and unordered_map

- .github/workflows/test.yaml
- include/seastar/testing/exchanger.hh
in 28b05551, we switched from ubuntu:jammy to fedora:40 as the building environment of our CI workflow. and we replaced the input parameter "clang++-18" in test.yml with "clang++", because in fedora:40, the clang++ executable does not have the postfix as the clang-18 installed by the setup-cpp action.
but we failed to update all of them in that change, that's why the "check header" step was not performed after that change.
in this change, we replace that last "clang++-18" in the workflow to "clang++".
> github: s/clang++-18/clang++/

- src/core/file-impl.hh
- src/core/file.cc
This number is needed in two places
- construction-time, to find the io-queue object to use
- run-time, to construct file handle
File handle uses device id to create another posix_file_impl object on another shard, so it needs device id to find io-queue for it. However, when creating handle, the deivce-id can be obtained by file from the io-queue it references.
> posix-file-impl: Do not keep device-id on board

- include/seastar/core/circular_buffer_fixed_capacity.hh
before this change, we use `*i++.~T()` to implement following sequence:
```c++
auto p = i++;
auto& v = *p;
v.~T();
```
but the associativity of `.` and `++` (suffix increment) operator is left-to-right. so from compiler's perspective, it emits:
```c++
auto p = i++;
auto v = p.~T();
*v;
```
that's why Clang-19 complains that we are dereferencing a `void`:
```
/home/kefu/.local/bin/clang -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEBUG -DSEASTAR_DEBUG_PROMISE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_DEPRECATED_OSTREAM_FORMATTERS -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING …
```
> circular_buffer_fixed_capacity: arrow operator instead of . operator

- include/seastar/core/reactor.hh
- include/seastar/core/scheduling.hh
- src/core/reactor.cc
The scheduling_group_key is assumed to be only copy-able and move-able by its users. However, reactor wants to mess with its ID for its maintenance purposes, but there's dedicated internal:: helper for that. Also rector wants to construct a temporary key object out of id, but that's just the way how internal reactor helper works, it can go with plain integral id value.
> Unfriend reactor from scheduling_group_key

- scripts/stall-analyser.py
> stall-analyser: use itertools.dropwhile when appropriate

- scripts/stall-analyser.py
`count` is never used after being assigned, so drop it.
> stall-analyser: remove unused variable

- install-dependencies.sh
in 6de08b079d, we introduced the dependency of pyyaml, but we failed to update `install-dependencies.sh` to install it.
in this change, we add this dependency to `install-dependencies.sh`.
> build: add pyyaml to install-dependencies.sh

- tests/unit/futures_test.cc
before this change, we do not verify that `stream` produces the consumed values.
after this change, we check if the subscriber of `stream` gets the value sent by the writer side.
> test: futures: verify stream yields the consumed value

- doc/tutorial.md
I was actually surprised to see that `then()` no longer does a preemption check (and this certainly leads to better code generation!).
I checked the tutorial and notice that it refers a different mechanism entirely, a 256-continuation counter but I can't find any trace of this in the code, so I assume it preceeded the time-based preemption check which has subsequently been removed. 
So:
- Rip out mention of the 256-counter
- Talk about preemption which isn't really covered in the tutorial and add that then() is not a suspension point (but co_await is, by default)
> Update tutorial.md to reflect updated preemption methods

- include/seastar/core/reactor.hh
- include/seastar/core/timer-set.hh
- include/seastar/core/timer.hh
- src/core/reactor.cc
Reactor messes with private timer fields, but it doesn't really need to. All the code that does so naturally belongs to timer_set class, not reactor itself.
> Unfriend reactor from timer

- include/seastar/core/timer-set.hh
The checkheaders target somehow stepped on recently merged #2269, while the PR itself passed CI when it was created
```
FAILED: CMakeFiles/checkheaders-seastar.dir/checkheaders/include/seastar/core/timer-set.hh.cc.o /usr/lib64/ccache/g++ -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_DEPRECATED_OSTREAM_FORMATTERS -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_PTHREAD_ATTR_SETAFFINITY_NP -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -DSEASTAR_STRERROR_R_CHAR_P …
```
> timer-set: Add missing sanity headers

- src/core/file.cc
The helper looks up in the map of fs-info-s twice and returns the chain of ready futures on the common paths. This PR makes things simpler.
> Simplify fs-info getting in make_file_impl()

- src/core/reactor.cc
The crash is caused by statistics request while scheduling_group is removed. The tasks_pending metric gathering triggers reactor::pending_task_count() call. This call causes null pointer derefence as the task queue pointer has been reset in reactor::destroy_scheduling_group()
> reactor: fix crash during metrics gathering

- scripts/stall-analyser.py
this change is a cleanup. it:
- uses a better name for the `--minimum` option, `args.minimum`
is way too general.
- uses the default value of 0 instead of `None`, simpler this way
- just references `arg.tmin`, simpler this way
> stall-analyser: use 0 for default value of --minimum

- include/seastar/core/iostream-impl.hh
in 62dd7127, we added two concept for both the old-style consumer which returns `std::optional<temporary_buffer>` consumer, and the new one which returns `consumption_result`. but somehow, we are still using the old-style in the implementation of `copy()`.
in this change, we switch to the new-style consumer. this helps developers to understand the usage of this consumer, and also enables us to drop the obsolete interface in future.
> iostream: use new-style consumer to implement copy()

- doc/rpc.md
- include/seastar/rpc/rpc.hh
- include/seastar/rpc/rpc_impl.hh
- include/seastar/rpc/rpc_types.hh
- src/rpc/rpc.cc
- tests/unit/rpc_test.cc
The new metrics is total time it takes an RPC message to travel back and forth between verb caller and server. It implicitly consists of the time request and response messages spend in seastar and kernel queues on both sides and classical network RTT.
Calculated for verbs that require response only. First, client negotiates with the server that response frame includes the "handler duration" value, which is the handler callback execution time. Then client notices duration between sending request and receiving response minus handler execution time received from server. This is called "delay sample". Total number of samples and their duration summary are exported as counters in the metrics domain.
refs: #323 
refs: #1753 (for what metrics domain is)
> RPC delay metrics

- include/seastar/core/fstream.hh
so that the these overloads of `make_file_input_stream()` can have their accompanied doxygen document.
> fstream: reformat the doxygen comment of make_file_input_stream()

- include/seastar/core/reactor.hh
- src/core/alien.cc
- src/core/reactor.cc
The alien and smp ones need _sleeping and _stopped. Both can be patched to be part of the public API.
> Unfriend reactor from message queues

- scripts/perftune.py
Commit 661367668f1e459bfd2f82450057d3944da7e20 introduced a regression by enabling ntuples by default for a configuration when the applicaiton CPUs and IRQ cpus are not the same.
Let's fix that.
> scripts/perftune.py: aRFS should be disabled by default in non-MQ mode

- tests/perf/linux_perf_event.cc
Commit 93f19d39526c68defac6860a15c77160da273606
added `exclude_idle = 1` to `linux_perf_event`.
However, as reported in
https://github.com/scylladb/scylladb/issues/19227#issuecomment-2165577271, `exclude_idle` is not supported on ARM platforms.
This change sets `exclude_idle` only on known-to-work architectures
(presently, it's only x86_64), assuming it is initialized to 0 as all
other unset bitfields in `perf_event_attr`.
Fixes scylladb/seastar#2298
> linux_perf_event: exclude_idle only on x86_64

- include/seastar/core/gate.hh
- tests/unit/closeable_test.cc
Add a method to try acquiring a gate holder
that gracefully returns nullopt if the gate
is already closed, rather than throwing an exception.
> gate: add try_hold

- coding-style.md
Avi writes,
> We promote long, explanatory names instead of acronyms. If we fold too
> much we end up taking a lot of vertical space and functions no longer
> fit on a screen.
Suggested-by: Avi Kivity <avi@scylladb.com>
> coding style: allow lines up to 160 chars in length

- include/seastar/core/sstring.hh
since fmt 11, if fmt/ranges.h is included, it tries to format a sequence-like container as a sequence. this confuses the compiler, and prevents fmt from considering sstring a formattable, as this type now has two formatters:
- one is the specialization of fmt::formatter provided by sstring.hh
- another is the one provided by fmt/ranges.h
```
/home/kefu/.local/bin/clang++ -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEBUG -DSEASTAR_DEBUG_PROMISE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEAST
AR_DEPRECATED_OSTREAM_FORMATTERS -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_COMPILE_TIME_FMT …
```
> sstring: prevent fmt from formatting sstring as a sequence

- src/core/metrics.cc
https://github.com/scylladb/seastar/commit/a57b17c8f4cba96aa8ac09741f0ca8f07a208e0a changed the way `local_engine`
gets set. It's now only being set after the reactor has been fully
constructed.
This breaks a bunch of metrics that are being registered from the
reactor constructor (main scheduling group metrics, stall detector,
possibly more) as the metrics subsystem uses `engine_is_ready` which
internally checks whether `local_engine` is set. With this not being the
case it would set the shard id to 0 for all shards.
Remove the extra check to `engine_is_ready` as the shard id is
initialized before the reactor is being constructed so this is safe to
use directly.
> metrics: Use this_shard_id unconditionally

- include/seastar/core/file.hh
`file::close()` in `src/core/file.cc` empties `_file_impl` by moving it to a local shared pointer object, effectively reverting the file object to its default-constructed state. Document this fact as a part of the public API.
[Suggested](https://github.com/scylladb/scylladb/pull/19624#discussion_r1679973548) by @bhalevy.
> file: document that close() returns the file object to uninitialized state

- include/seastar/core/internal/pollable_fd.hh
The pollable_fd_state is base class for backend-specific fd states. Those are created and destroyed via backend virtual calls. In that case, base class destructor doesn't need to be virtual, deleting an object via derived pointer would call correct destructor on its own. Also, the base class destructor is marked protected to explicitly disallow deletion via base-class.
> pollable_fd_state: Mark destructor protected and make non-virtual

- .github/workflows/test.yaml
- .github/workflows/tests.yaml
ccache does not support C++20 modules yet, see https://github.com/ccache/ccache/issues/1252.
in this change, ccache is disabled when building with C++20 module
support.
Fixes https://github.com/scylladb/seastar/issues/2362
> github: disable ccache when building with C++ modules 

- include/seastar/core/reactor.hh
- src/core/program_options.cc
- src/core/reactor.cc
- src/core/reactor_backend.cc
- src/util/log.cc
- tests/unit/futures_test.cc
- tests/unit/io_queue_test.cc
There were places in the code where 'smp.hh' was
included in spite of the fact, that it wasn't needed.
Moreover, 'reactor.hh' could have utilized only forward
declaration. It did not need to know the definitions
from 'smp.hh'.
This change adjusts the inclusion of 'smp.hh'.
> code-cleanup: remove redundant includes of 'smp hh'

- src/core/reactor.cc
Commit 3d654527 (reactor: Add .no_poll_aio to reactor_config) moved initialization of it into constructor's initializer list, but when created pollfd tries to access engine() which is not yet set. Move the pollfd initialization back to reactor::configure().
> reactor: Initialize _aio_pollfd later

- src/seastar.cc
this change address the build failure with C++20 modules and fmt 11.
this change is a follow up of b8fc54d68a, which includes fmt/ranges.hh, and references `fmt::range_format_kind` in `sstring.hh`, but we failed to include this header in `src/seastar.cc`, hence we have following FTBFS when compiling the tree with C++20 modules support on a system with fmt 11 installed:
```
FAILED: src/CMakeFiles/seastar-module.dir/seastar.cc.o src/CMakeFiles/seastar-module.dir/seastar.pcm
/home/kefu/.local/bin/clang++ -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_MODULE -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 …
```
> seastar.cc: include fmt/ranges.h

- include/seastar/core/future.hh
Since commit 73e3fbc1bc51 ("future: Use a new seastar::nested_exception in finally", 2020-06-23), `future::finally()` propagates a `seastar::nested_exception` instance rather than an `std::nested_exception` instance, in case both the original future, and the cleanup appended by `finally()`, resolve with exceptions. Update the documentation.
Fixes: 73e3fbc1bc51
> future: correctly document nested exception type emitted by `finally()`

- src/core/reactor.cc
While handling SEGV/ABRT signal yet another one (of the same kind) may pop up. In that case it will call the same handler again, dead-locking on the guard lock.
> reactor: Reset one-shot signal to DFL before handling

- include/seastar/core/reactor.hh
- src/core/reactor.cc
Add missing include of noncopyable_function.hh in reactor.hh and reactor.cc, and fix lexical order.
> reactor: add missing includes of noncopyable_function.hh

- include/seastar/core/io_queue.hh
- include/seastar/core/reactor.hh
- include/seastar/core/reactor_config.hh
- src/core/io_queue.cc
- src/core/reactor.cc
Scheduler goal is to make sure that dispatched requests complete not later than after io-latency-goal duration (which is defaulted to 1.5 times reactor CPU latency goal). In cases when disk or kernel slow down, there's flow-ratio guard that slows down the dispatch rate as well [1]. However, sometimes it may not be enough and requests delay their execution even more. Slowly executing requests are indirectly reported via toal-disk-delay metrics [2], but this metrics accumulates several requests into one counter potentially smoothing spikes by good requests. This detector is aimed at detecting individual slow requests and logging them along with some related statistics that should help to understand what's going on.
refs: #1766 [1] (eefa83771e) [2] (0238d255d8)
fixes: #1311 
closes: #1609
> Detect and report slow IO requests

- scripts/stall-analyser.py
a typical session is like:
```console
$ ./stall-analyser.py --format trace -e scylla/libexec/scylla \
reactor_stalled_231d31df_2022_2_twcs_3h.log  > out.folded
$ flamegraph.pl out.folded > /tmp/folded.svg
$ xdg-open /tmp/folded.svg
```
> stall-analyser: add output support for flamegraph

- include/seastar/core/chunked_fifo.hh
- include/seastar/core/internal/io_request.hh
- include/seastar/core/internal/io_sink.hh
- src/core/io_queue.cc
- tests/perf/CMakeLists.txt
- tests/perf/container_perf.cc
- tests/unit/chunked_fifo_test.cc
The end goal of this series is to swap out circular_buffer for chunked_fifo in the `io_sink::_pending_io` member. 
This is to avoid the large contiguous allocation done by
circular_buffer when there many pending IOs, as such allocations can
fail on a long running system due to fragmentation.
While we are in there, we also optimize the size of the io_request structure.
See https://github.com/scylladb/seastar/issues/2355 and individual changes for more context.
> Change pending_io container to chunked_fifo

- CMakeLists.txt
Seastar cmake build contains
```
target_compile_options (seastar
PUBLIC
-U_FORTIFY_SOURCE)
```
Which disables FORTIFY_SOURCE on all Seastar targets and is inherited by anything depending on Seastar.
This PR undefines this only on src/core/thread.cc which is apparently the only thing that needs it, and avoids leaking this out to dependents.
> Undefine `_FORTIFY_SOURCE` only on what's needed

- apps/io_tester/io_tester.cc
- src/core/fair_queue.cc
Activation of a class happens when it receives a request into its empty queue. When activated, class also updates its "accumulator" that's responsible for fair-selection of classes according to its shares. Each activation a class may lose some accumulator point, thus losing some portion of the disk capacity.
Knowing the activation rate is very useful, right now we only have some side ways to get an idea of this counter.
> fair_queue: Export the number of times class was activated

- apps/io_tester/io_tester.cc
- include/seastar/core/print.hh
- include/seastar/rpc/rpc.hh
- src/core/semaphore.cc
- src/json/formatter.cc
- src/net/net.cc
this series enables `seastar::format()` to use compile-time format check.
using `fmt::format_string` would allow us to perform compile-time
format checking. so in this change, we switch to `fmt::format_string`
when fmtlib's version is greater or equal to 8.0, which introduced
the compile-time checking.
also, because the `fmt::format_string` can only be instantiated with
a compile-time constexpr, the fmt string specified in test is changed
to a constexpr accordingly.
please note, this is a breaking change which might require caller to use
`seastar::format()` if the tree is compiled with libstdc++ 13 or a standard
library with `std::formt()` implemented.
> treewide: use fmtlib's fmt::format_string in format() 

- include/seastar/rpc/rpc.hh
Depending on the 'SEASTAR_LOGGER_COMPILE_TIME_FMT' the declaration of 'logger::log()'
function may use either 'fmt::format_string' or 'const char*' format parameter.
In the case of the usage of 'const char*', there is a need to call 'fmt::runtime()' function to
obtain format_string.
When the project was built on Ubuntu 22.04 using the steps described in the tutorial,
there was a compilation error related to passing argument with type 'fmt::format_string<>'
to 'fmt::runtime()' that handles characters strings.
This change introduces contexpr if statement to remove the compilation error and use
'fmt::runtime()' only when the function takes 'const char*'.
> rpc: fix compilation error caused by fmt::runtime()

- include/seastar/core/print.hh
operator<< overload for `const void*` was commented out in ceb0c942. this code has been around for more than 8 years at the time of writing. there is not point to keep it anymore.
> print: remove dead code

- cmake/FindSanitizers.cmake
we are going to add a build with ThreadSanitizer enabled, but ThreadSanitizer cannot be used along with AddressSanitizer. the existing sanitizer detection checks each sanitizer separately, so even if the sanitizers combination does not work, the detection still passes.
also, we hardwire two sanitizers in `FindSanitizers.cmake`, this is not extensible to the use case where we only need to selectively find a certain (combination) of sanitizers.
in order to address these problems, in this change
* find specified component(s) in FindSanitizers.cmake, to prepare for the change which selectively specifies a subset of sanitizers
* check if the compiler supports the combination of compile options required by all specified sanitizers
* explicitly specify the used sanitizers in …
> build: check the combination of Sanitizers

- include/seastar/http/client.hh
- src/http/client.cc
- tests/unit/httpd_test.cc
This PR adds abort_source& argument to client::make_request() method. With it, calling abort_source::request_abort() will break the request making process wherever it is and resolve the make_request() with abort_requested_exception exception.
One of the use-cases is to let client impose a timeout on the make_request(). For that, a timer should be armed that would request abort on the abort source passed to the method. In #2304 there was an attempt to put a timeout on connect() only, but this approach is more generic and allows aborting request at any stage, not only connecting.
Another scenario is stopping long operations on user request. There can be several examples of what "long" operation can be. One of them is simple connect() to the server -- TCP times out after 1 minute by default, …
> Make http::client::make_request() abortable

- scripts/addr2line.py
We feed addresses into the underlying addr2line binary one at a time, passing:
```
<address>
0x0
```
each time. The 0x0 "dummy" is there so we can tell when the decoding is finished, as it will emit a characteristic line. We need this sentinel because the address itself can emit several frames (due to inlining).
If the dummy output (associated with the 0x0 frame) is not correctly detected the symptom is that seastar-addr2line simply hangs while decoding a backtrace.
This change adjusts the regex used to detect the dummy output, since in the case where ASAN is linked in it can be different than we expected (the file will be an ASAN internal thing rather than ??).
> seastar-addr2line: adjust llvm termination regex

- include/seastar/http/reply.hh
- include/seastar/http/request.hh
- include/seastar/util/iostream.hh
- tests/unit/httpd_test.cc
When putting data into output_stream() a common pattern exists. Data is written into stream, then flushed and the end and the stream is closed. Any exception that may pop up in the middle shouldn't leave stream not closed, so in the code it looks smth like
```
try {
for (...) {
co_await out.write()
}
co_await out.flush()
} catch () {
ex = current_exception()
}
co_await out.close()
if (ex) {
throw ex
}
```
This is very typical to http client and handlers code that use request::write_bod() and response::write_body() overloads that call user-provided lambda giving it chunked or content-length output_stream. The caller then implements the paterns described above on its own.
This PR suggest a pair of helpers -- one is the util::write_to_stream() function that looks literally like above; the …
> Introduce output_stream writing shugar

- CMakeLists.txt
this change addresses a regression introduced by ed889199, which renamed the exported CMake variable of `Sanitizers_COMPILER_OPTIONS` to `Sanitizers_COMPILE_OPTIONS`, to be more consistent with the names used by CMake. but it failed to update the top-level `CMakeLists.txt`, which was still using the old name to populate this setting down to .pc. that's why some parent project fails to link with the latest seastar with sanitizers enabled.
in this change, we correct the variable name.
> build: s/Sanitizers_COMPILER_OPTIONS/Sanitizers_COMPILE_OPTIONS

- README.md
Reef is a major version of Ceph, and the URL of "Ceph - Crimson" is a page targeting Crimson developers. We should instead reference the project's homepage or its github project address like other projects.
so, in this change, let's reference Ceph's project page on GitHub.
> README.md: use the github homepage of Ceph for Crimson

- cmake/Finddpdk.cmake
Fixes #2411.
If libbsd-dev is installed during build time, DPDK will depend on it without a way to turn this off.
config/meson.build has the following:
```
libbsd = dependency('libbsd', required: false, method: 'pkg-config') if libbsd.found()
dpdk_conf.set('RTE_USE_LIBBSD', 1)
endif
```
And lib/eal/include/rte_string_fns.h contains:
```
#ifdef RTE_USE_LIBBSD
#include <bsd/string.h>
#else /* no BSD header files, create own */
#define strlcpy(dst, src, size) rte_strlcpy(dst, src, size)
#define strlcat(dst, src, size) rte_strlcat(dst, src, size)
#endif /* RTE_USE_LIBBSD */
#endif /* FREEBSD */
```
Accordingly the only way to address this inflexibility is to ensure that dpdk dependencies are appropriately transferred to INTERFACE_LINK_LIBRARIES of the dpdk library.
> cmake: Depend on libbsd if DPDK depends on it

- cmake/FindSanitizers.cmake
this change partially reverts 87a6540906, which workarounded a bug in GCC-10 and LLVM-3.8, see
https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=1842a04ce06a470b731bc9a29bfec17e6e147c3f and
https://github.com/llvm/llvm-project/commit/894d5821e7af9128398ec8153f3cb4025ae9ad50 respectively.
since scylla builds with GCC-13 and GCC-14, LLVM-17 and LLVM-18. so we don't need to keep this workaround anymore.
> build: drop the workaround for a GCC bug

- include/seastar/core/file.hh
- include/seastar/core/reactor.hh
- include/seastar/core/seastar.hh
- src/core/reactor.cc
- src/core/syscall_result.hh
- src/util/file.cc
- tests/unit/CMakeLists.txt
- tests/unit/libc_wrapper_test.cc
The scylladb codebase is bypassing seastar api to make syscalls directly, instead add seastar APIs for those syscall and use it in the transport/controller.cc in scylla
see issue: https://github.com/scylladb/scylladb/issues/17443
> API to get group information and to change file ownership

- configure.py
before this change, the output of `./configure.py --help` looks like:
```
--c++-standard CPP_STANDARD
C++ standard to build with [default: ]
```
because the default value of `--c++-standard` option is an empty string. printing out its value is not helpful, and could be confusing.
as the actual default value of this option varies depending on the used compiler, so even if we print out the deduced C++ standard, it is still confusing. not to mention that argparse does not differentiate the defaulted value in the returned namespace from `parse_args()` from the user specified one. so, a simpler approach is just do not specify the default value.
in this change, we
* do not specify the default value for `--c++-standard`, so its value would be `None` if not specified
* do not print its default …
> build: do not print the default value of --c++-standard in help output

- include/seastar/core/sharded.hh
- src/seastar.cc
- tests/unit/sharded_test.cc
Add a convenient method to invoke a function on a range of shards, to have better support for the cold control path on more complex compute models like shard groups for different tasks. A workload can benefit from such a model if inter-task cooperation is better when grouping from perf and QoS perspectives, for example. Or a computation requires a only a subset of shards due to internal concurrency limits.
> sharded.hh: add invoke_on variant for a shard range

- cmake/SeastarConfig.cmake.in
we install `SeastarConfig.cmake` so that a Seastar project can consume the Seastar libraries using `find_package(Seastar)`. this CMake config file checks for the dependencies used by CMake, and defines the Seastar libraries to be consumed by the parent project. one of the dependence is detected using FindSourceLocation.cmake, which is also shipped along with Seastar, this find module is provided so that we can detect the C++ compiler support of `std::source_location` related features. But the result of the detection depends on the C++ standard used, which is default to the one configured by the used C++ compiler if not specified. if the parent project consumes precompiled Seastar libraries, and use a differnt C++ standard, the parent project could fail to build, because Seastar and parent …
> build: add compiler and C++ standard compatibility checks

- src/http/file_handler.cc
Always close the stream in `file_interaction_handler::read`, even if there was a failure such as a short read.
> httpd/file_handler: Always close stream

- include/seastar/core/iostream.hh
- src/http/common.cc
- tests/unit/httpd_test.cc
Previously, calling the `write(temporary_buffer<char>)` overload on an `output_stream<char>` obtained from `http::reply::write_body` would cause an abort.
This commit fixes this by providing a helper function (in the `data_sink_impl` base class) named `fallback_put`, which classes that inherit from this base class can use to implement the `put(net::packet)` overload. Also, this commit lets `http_chunked_data_sink_impl` and `http_content_length_data_sink_impl` make use of this helper.
`fallback_put(net::packet)` works simply by extracting the temporary_buffers contained in the packet, and calling the `put(temporary_buffer<char>)` overload for each `temporary_buffer`.
Note that we create this `fallback_put` function instead of defining the virtual member `put(net::packet)` function in the …
> iostream/http: Fix output_stream::write(temporary_buffer) overload

- cmake/Findc-ares.cmake
- cmake/SeastarDependencies.cmake
we don't support c-ares 1.33 yet. so error out when c-ares >= 1.33 is detected.
Refs #2472
> build: do not support c-ares >= 1.33

- include/seastar/http/client.hh
- src/http/client.cc
To satisfy scylla's s3 client with future retry implementation add non-owning `make_request` to http client which is similar to the existing `make_request` but it doesn't take ownership of `request` and `reply_handler`
fixes: #2467
> http: Add non-owning `make_request` to http client

- cmake/Findc-ares.cmake
before this change, we get c-ares's version with pkg-config, but this could be wrong if we have multiple c-ares version installed into the system, and the one to be used is specified using CMake variable of `c-ares_ROOT` via the command line like:
```console
cmake -Dc-ares_ROOT=install-path/of/c-ares
```
as `pkg_check_modules()` does not respect the `c-ares_ROOT` variable, it always find the .pc file in the default paths.
in order to get the version of the c-ares library specified by the `c-ares_ROOT` variable, let's extract the version number in the header file. this should fix the build of seastar on fedora 41 with both c-ares 1.33 shipped by the fedora 41, and c-ares 1.32 installed manually.
> build: extract c-ares version from header file

- src/net/dns.cc
this changeset includes two trivial cleanups. they were inspired when auditing the c-ares code.
> dns: cleanups

- scripts/addr2line.py
- scripts/seastar-addr2line
This series has two changes:
Add additional type hints and a few other type related changes to seastar-addr2line and addr2line.py. After this these scripts type check cleanly with pyright strict.
Add a --debug arg which actives additional explicit debug logging, quite useful for diagnosing what is going on.
`./seastar-addr2line --test` passes after these two changes.
> addr2line: type checking, debugging

- CMakeLists.txt
when building the shared libraries, `-fnosematntic-interposition` option can be used to improve the performance of the shared libraries, if interposition of exported symbol is not allowed.
by default, GCC respects the symbol interposition semantics defined by the ELF specification. but if we want to have a better performance for the shared libraries, and we don't want to override the exported symbols with, for instance, `LD_PRELOAD`, we can safely disable this behavior for better performance. as the interposition semantics prevents compiler from doing further optimizations like inlining. GCC only disables this when building with `-Ofast`, see https://github.com/gcc-mirror/gcc/commit/458d2c689963d8461d84670a3d8988cd6ecbfd81.
Clang just disables this behavior by default. see …
> build: include -fno-semantic-interposition in CXXFLAGS

- CMakeLists.txt
- cmake/CheckLibc.cmake
- cmake/SeastarConfig.cmake.in
before this change, we respect the CMake variable named `BUILD_SHARED_LIBS`, and build shared libraries if it is set, build static libraries otherwise. but this model cannot fulfill the needs of a parent project which needs to build both static and shared seastar libraries with different configuration in a multi-config generator settings. as `BUILD_SHARED_LIBS` is a CMake variable which cannot be changed at build time, and hence cannot be assigned with
different values using generator expression. 
so, in this change, we add two options
- Seastar_BUILD_STATIC_LIBS
- Seastar_BUILD_SHARED_LIBS
to configure if the build should generated static libraries and shared libraries respectively. but `BUILD_SHARED_LIBS` is still supported, and the behavior is backward compatible. the only user-visible …
> build: enable Seastar to build shared and static libs in a single build

- cmake/Findc-ares.cmake
this change enhances the version extraction process to handle both literal and macro-based version definitions in c-ares.
in 5d53fb6d, we extract the c-ares version by looking for `ARES_VERSION_STR` and matching the version numbers in it. as, in c-ares 1.32, the line looks like:
```c
#define ARES_VERSION_STR "1.33.0"
```
but this method fails for c-ares 1.33+ due to non-literal `ARES_VERSION_STR` definitionin. as in c-ares 1.33+, it looks like
```c
#define ARES_VERSION_STR             \
ARES_STRINGIFY(ARES_VERSION_MAJOR) \
"." ARES_STRINGIFY(ARES_VERSION_MINOR) "." ARES_STRINGIFY(ARES_VERSION_PATCH)
```
this fails the parser. and the version number is always empty.
in this change, we match the MAJOR, MINOR and PATCH version components separately. this approach increases resilience. after …
> build: improve c-ares version extraction method

- cmake/SeastarDependencies.cmake
in c-ares 1.34.0, it addressed a regression with custom socket callbacks due to DNS cookie support. because 1.34.0's release tarball failed to include some header file. so let's claim the support to c-ares < 1.33 or >= 1.34.1.
Refs #2472
> build: support c-ares >= 1.34.1

- cooking_recipe.cmake
Seastar no longer builds with the old (1.13) version of c-ares used when cooking that component, and in any case the URL is 404 as it seems that c-ares has moved to hosting their downloads on github.
Update to 1.32.3 which is the newest version less than 1.33 as seastar does not support versions >= 1.33.
> c-ares: update cooking version to 1.32.3

- cmake/Finddpdk.cmake
If libarchive-dev is installed during build time, DPDK will depend on it without a way to turn this off.
Accordingly the only way to address this issue is to ensure that libarchive is added to the dependencies using similar logic as dpdk uses.
Fixes https://github.com/scylladb/seastar/issues/2494.
> cmake: Fix DPDK libarchive dep

- include/seastar/core/chunked_fifo.hh
`assert(...)` is being used in the `pop_front_n` method and none of the other headers in the file include assert transitively.
> Add missing `assert.h` header to `chunked_fifo`

- tests/unit/httpd_test.cc
- tests/unit/loopback_socket.hh
The class `loopback_connection_factory` used a magic number valued `10` as the capacity of the connection queue per shard. As a result, test units can badly program the device. For example, `httpd_test` would deadlock on a machine with 10 vCPUs or more, because `connect()` waits for queue space to be released, and queue space is only released after the `connect()` call. This commit adds a `pending_capacity` param to provide the needed control for test units, via factory method to disambiguate constructors. Also, it fixes the deadlock in `httpd_test.cc` using the new interface.
> loopback: add pending capacity param and fix deadlock in httpd_test

- include/seastar/http/reply.hh
- tests/unit/httpd_test.cc
Add `status_class` enum for possible http code groups (classes) and a function `classify_status` to get code's classification. Intended for general usage to prevent code like `if (http_code >= XXX && http_code < YYY)`
In general all http codes are divided into 5 main categories
1xx: Informational - Request received, continuing process
2xx: Success - The action was successfully received, understood, and accepted
3xx: Redirection - Further action must be taken in order to complete the request
4xx: Client Error - The request contains bad syntax or cannot be fulfilled
5xx: Server Error - The server failed to fulfill an apparently valid request
This implementation does not take into account unassigned ranges, for more details https://www.iana.org/assignments/http-status-codes/http-status-codes. …
> http status classification

- include/seastar/core/reactor.hh
- src/core/reactor.cc
- src/core/reactor_backend.cc
This series primarily addresses the problem that on systems with low amounts of steal, steal time appears negative (i.e., the cumulative steal time counter goes down from sample to sample).
This wrong on the face of it and also causes serious problems as a metric in prometheus since the counter contract (monotonic increase) is violated. This causes spurious "counter reset" detection in prometheus and hence bogus very large or very small steal time results in `rate` (or similar) queries.
This is addressed in two ways:
- We make the sleep time calculation more accurate, which is the underlying reason for negative steal which reduces the error (and so "negativeness") of steal by a couple orders of magnitude. After this change steal time is often 0 when rounded to the nearest ms where it …
> Address non-monotonicity of steal time and other issues

- include/seastar/core/gate.hh
`check()` doesn't modify the object so it can be marked as `const`.
> gate: check: mark as const

- tests/perf/CMakeLists.txt
- tests/perf/http_client_perf.cc
The test opens a server socket that reads socket up until double CRLF and then responds back with "HTTP/1.1 200 OK host: test" line in a loop. Then runs http client against it measuring time it takes to perform the given amount of requests. It uses in-memory loopback sockets (seastar wrapper around seastar::queue).
> test: Add perf test for http client

- include/seastar/core/sharded.hh
Seperate all invoke_on decls from defs on sharded class template for improved readability and loose coupling, maybe even as preparation for `extern template`. Also, cluster `invoke_on(unsigned id, ...)` together with the other variants.
> sharded.hh: seperate invoke_on decls from defs

- doc/signal.md
Add documentation about the default Seastar signal handlers and `app_template::config::auto_handle_sigint_sigterm` flag to `doc/signal.md`, as introducery information.
> signal.md: describe auto signal handling

- cmake/FindSanitizers.cmake
when building a project by consuming Seastar's CMake config files, if the parent project does not set the policy CMP0057, CMake warns:
```
CMake Warning (dev) at /tmp/seastar/lib64/cmake/Seastar/FindSanitizers.cmake:53 (if):
Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
--help-policy CMP0057" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
IN_LIST will be interpreted as an operator when the policy is set to NEW.
Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
/usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
/tmp/seastar/lib64/cmake/Seastar/SeastarDependencies.cmake:55 (find_dependency) …
```
> build: suppress CMake warning about CMP0057

- include/seastar/core/reactor.hh
It's only called by reactor itself on stop, no need in keeping it public
> reactor: Mark drain() private

- include/seastar/core/reactor.hh
- src/core/reactor.cc
A possible issue with how Docker Desktop v4.34+ (particulary on macOS) handles `pidfd` functionality causes an assertion failure in Seastar's `reactor::waitpid` method.
The issue:
- Seastar creates a `pidfd` using `pidfd_open`
- It polls this file descriptor until it becomes readable
- When readable, call `waitpid` with `WNOHANG`.  According to [pidfd_open](https://man7.org/linux/man-pages/man2/pidfd_open.2.html), the file descriptor becomes readable when the process terminates
- Seastar expects `waitpid` to either return a positive integer representing the child process that has ended or a negative value to indicate an error.  However if `waitpid` returns `0`, then Seastar asserts, crashing the using application.
This change adds `reactor::do_waitpid` which loops on calling `waitpid` …
> reactor: Always retry waitpid

- include/seastar/core/reactor_config.hh
- include/seastar/core/smp.hh
- src/core/reactor.cc
This new option allows reserving the configured amount of IOCBs, so they are available to a side application running in parallell to the seastar application.
The use case is ScyllaDB and its tool applications, both ScyllaDB and its tool applications need IOCBs to run, so ScyllaDB has to be able to tell seastar to reserve some IOCBs for the tools as well.
> core: reactor_config: add reserve_io_control_blocks

- src/rpc/rpc.cc
There are two places that accumulate a vector of buffer and for that they push-back the temporarily-constructed one. There's the emplace_back shortcut for such cases.
> rpc: Emplace buffers into vector, not push

- include/seastar/core/sharded.hh
Templates are distinctly defined in each translation unit, thus they dont cause multiple definitions linkage error, so inline is redundant code to compile.
> sharded.hh: remove inline from templates

- src/core/file.cc
A number of small cleanups utilizing coroutines to make code clearer.
> file: Convert file operations to use coroutines

- cmake/FindSanitizers.cmake
Unset the `compile_option` variable after it's used in the FindSanitizers module to prevent potential conflicts with other CMake build configurations. Previously, this variable persisted after `find_package(Sanitizers)`, which could lead to unexpected build behavior if the same variable name was used elsewhere.
This change follows CMake best practices where Find modules clean up temporary variables after use.
> build: Clean up `compile_option` after FindSanitizers module

- include/seastar/core/smp_options.hh
Regardless of who is using it, either the OS or other userspace processes.
> reserve-memory: document that seastar just doesnt use the reserves

- include/seastar/core/internal/stall_detector.hh
- src/core/reactor.cc
The _max_reports_per_minute is used instead.
> stall-detector: Remove unused _stall_detector_reports_per_minute

- include/seastar/core/reactor.hh
- src/core/reactor.cc
There can be at least two kinds of CPU stalls in seastar: task stall and queue stalls. The former is when a single task non-preemptively occupies a CPU for a too long period of time (configured by the option named blocked-reactor-notify-ms). The latter happens when the list of tasks to run happens to go above a certain threshold (configured by the option named max-task-backlog which is 1000 by default). In that case scheduler bites the buller and doesn't stop running tasks until the queue shrinks ignoring the need_preempt() value.
The stall of the second kind can be detected by checking the "stalls" historgram in the "reactor" group and is also implicitly reported via time-spent-in-task-quota-voilation counter. However, it's good to have more information about this stall other than …
> scheduler: Report long queue stall

- include/seastar/util/backtrace.hh
- src/util/backtrace.cc
This commit addresses a critical memory allocation issue in backtrace formatting by directly specializing fmt::formatter for backtrace types, eliminating dependency on iostream-based formatting.
Problem:
---
When Seastar applications experience high memory pressure, logging backtrace information could fail due to additional memory allocation required by iostream formatting. This resulted in errors like:
```
ERROR 2024-12-10 01:59:16,905 [shard 0:main] seastar_memory - seastar/src/core/memory.cc:2126 @void seastar::memory::maybe_dump_memory_diagnostics(size_t, bool): failed to log message: fmt='Failed to allocate {} bytes at {}': std::__ios_failure (error iostream:1, basic_ios::clear: iostream error)"
```
Solution:
---
- Implement direct fmt::formatter specialization for backtrace
- Remove …
> util/backtrace: Optimize formatter to reduce memory allocation overhead

- include/seastar/core/smp.hh
- src/core/reactor.cc
`smp::adjust_max_networking_aio_io_control_blocks` has become a bit incohesive in the process of adding IOCB reservation; clean up the function.
Triggered by #2538.
See also #2396 (commit ec5da7a606dd) and #2533 (commit c5f9e3a23449).
> reactor, linux-aio: clean up `smp::adjust_max_networking_aio_io_control_blocks`

- include/seastar/core/thread.hh
- src/core/thread.cc
thread::maybe_yield, a static method, calls into
thread_impl::maybe_yield which is a member function on the current thread context, which means we need to access the TLS etc, but this function is itself essentially static as it only calls needs_prempt().
This was probably different in the ancient past where there were thread-specific scheduling groups, etc.
This method is performance sensitive as it is often called in loops, even tight loops as it is often difficult to call it less frequently in a tight loop which may have a large trip count. Therefore it is worth optimizing.
So this change:
- Have thread::maybe_yield just call needs_prempt() directly
- Move maybe_yield and should_yield in to the header.
This latter change doesn't change needed includes, so shouldn't impact compile time. …
> thread: optimize maybe_yield

- include/seastar/core/reactor.hh
- include/seastar/core/scheduling_specific.hh
- src/core/reactor.cc
- tests/unit/scheduling_group_test.cc
The functions create_scheduling_group and scheduling_group_key_create
may have unexpected results when run concurrently.
when creating a SG key, we:
1. allocate a key
2. insert the key config
3. for all SGs, initialize data for the SG and key
with preemptions possible in between each step.
Another process could see an intermediate state where a key was created
but not fully initialized yet. This may lead to the data being
initialized twice for the new key, or functions operating on
uninitialized key data.
To solve this we introduce a shared_mutex which is locked exclusively
when creating a new key, and is held with shared access when creating a
scheduling group and when a consistent read access of all keys is required.
Fixes https://github.com/scylladb/seastar/issues/2231
> scheduling_group: fix race between scheduling group and key creation

- apps/io_tester/io_tester.cc
- include/seastar/core/metrics_api.hh
- src/core/metrics.cc
- src/core/prometheus.cc
- src/core/scollectd.cc
- tests/unit/metrics_test.cc
- tests/unit/rpc_test.cc
The major memory user in the metric subsystem is the per series label
sets.
This is for two reasons:
- The labels are stored multiple times in different places: Twice as
part of `registered_metric` (one current labels and one original one
for relabeling - these are often just the same), one copy as the
lookup key in the values map and another final copy in the metadata
copy for scraping
- Lots of the labels are actually duplicated across metric series. For
example for one io-queue class/mountpoint/iogroup combination you get
15 series all with the same labels. Similar is true for other metrics
like reactor or scheduler metrics. In Redpanda we have an even more
extreme pattern where per partition metrics create more than 60
series with the same label set.
One idea to improve this would be …
> metrics: Internalize metric label sets

- include/seastar/json/json_elements.hh
When building up json lists in memory we have only the `push` method which takes const T&, but one taking an rvalue reference and moves into the list would be useful for heavy elements.
> json: add moving push to json_list

- include/seastar/core/rwlock.hh
- tests/unit/locking_test.cc
Add synchronous try_hold_* methods so that users
can optimize contention-free paths by avoiding
extra-allocations that might be needed for waiting on the lock, if it's taken.
> rwlock: add try_hold_{read,write}_lock methods

- include/seastar/core/reactor.hh
- include/seastar/core/seastar.hh
- src/core/reactor.cc
- src/util/file.cc
- tests/unit/file_io_test.cc
Return space_info for the filesystem identified
by the given file name.
space_info provides simpler and standard space information about the filesystem, in contrast to the posix statvfs which requires knowledge about the how to convert
f_block to bytes by multiplying by f_frsize.
> file: add file_system_space

- .github/workflows/test.yaml
Ubuntu 24.04 is now available, see
https://github.com/actions/runner-images/issues/9848
so instead of building and running the tests in a fedora 40 container, let's do the CI with the shinny ubuntu runner image, which preinstalls some of the necessary building dependencies, so in theory, it should be relatively faster than installing every package on fedora 40.
and since we are now using an image with git pre-installed, there is no need to install `git` anymore. so, in this change, we drop the step to install `git`.
because we are switching to a debian derivative distro, let's use apt-get instead of dnf to install packages.
> github: s/ubuntu-latest/ubuntu-24.04/

- include/seastar/core/print.hh
these functions were marked deprecated in three years ago (a189cdc45d) in favor of fmt library. so we can safely remove these API now.
> print: remove deprecated print() functions

- CMakeLists.txt
- cmake/SeastarDependencies.cmake
Remove the "MODULE" parameter from `find_package(Boost)` call to allow using Boost's provided BoostConfig.cmake instead of CMake's FindBoost module. This aligns with CMake 3.30's policy CMP0167 which deprecates FindBoost.cmake.
Background:
- We previously dropped our vendored FindBoost.cmake in bf684aca
- CMake is deprecating its FindBoost module as Boost now provides its own package config files
- Using Boost's config files is the recommended approach going forward
This change:
- Silences [CMP0167](https://cmake.org/cmake/help/latest/policy/CMP0167.html) policy warnings like ``` CMake Warning (dev) at CMakeLists.txt:133 (find_package): Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake --help-policy CMP0167" for policy details.  Use the cmake_policy command to set …
```
> build: allow CMake to find Boost using package config

- include/seastar/core/abort_on_expiry.hh
- include/seastar/core/abortable_fifo.hh
- include/seastar/core/semaphore.hh
- tests/unit/CMakeLists.txt
- tests/unit/abort_source_test.cc
- tests/unit/abortable_fifo_test.cc
- tests/unit/closeable_test.cc
- tests/unit/expected_exception.hh
- tests/unit/file_utils_test.cc
- tests/unit/futures_test.cc
- tests/unit/semaphore_test.cc
Today, when calling `wait(abort_source&)` the caller always gets `semaphore_aborted` error when abort is requested.
However, with `abort_on_expiry`, the actual reason could be timeout expiry, which should be distinguishable from the abort error.
This series modifies `abort_on_expiry` first to request abort with a `timed_out_error` exception, and then `internal::abortable_fifo` and `semaphore` are changed to tunnel that exception to the caller.
Respective unit tests were added to test those cases.
The motivation for this change is https://github.com/scylladb/scylladb/pull/22017
which will use scylladb utils::composite_abort_source to compose an `abort_on_expiry` abort_source, used for point request timeout and a global abort_source used on shutdown.
> Tunnel requested abort exception to semaphore wait caller

- include/seastar/testing/perf_tests.hh
- tests/perf/CMakeLists.txt
- tests/perf/perf_tests_perf.cc
In this series:
- perf_tests_perf: minimal self-benches for PERF_TEST stuff
- De-duplicate perf_tests main loop, which also fixes #2587 
Example results for `perf_test_perf` after the fix:
```
test                             iterations      median         mad         min         max      allocs       tasks        inst      cycles
perf_tests.test_simple_1          774019546     1.313ns     0.019ns     1.259ns     1.333ns       0.000       0.000         7.0         5.0
perf_tests.test_simple_n         3188188100     0.330ns     0.001ns     0.308ns     0.387ns       0.000       0.000         3.1         1.3
perf_tests.test_ready_async_1    3638567766     0.280ns     0.005ns     0.271ns     0.290ns       0.000       0.000         4.0         1.1
perf_tests.test_ready_async_n    3179866200 …
```
> Fix for missing cycles column and more

- include/seastar/websocket/server.hh
- src/websocket/server.cc
- tests/unit/websocket_test.cc
According to RFC6455 section 4.1 Sec-WebSocket-Protocol is optional both on client and server side.
> websocket: Support clients that do not specify subprotocol 

- tests/perf/future_util_perf.cc
test: Add perf test to measure the "cost" of chain wakeup
The test creates a chain of future-promise-s and then wakes up the last one thus causing the cascade of resolutions. There are 2x2 tests -- resolve with value or exception vs co_await-ed or .then()-d chains.
The result is (depth of 32)
test                   iterations      median         mad         min         max      allocs       tasks        inst      cycles
chain.then_value         29944640    33.158ns     0.026ns    33.059ns    33.740ns       1.063       1.094       314.9         0.0
chain.await_value        18963648    52.668ns     0.242ns    52.426ns    54.334ns       1.094       1.125       414.3         0.0
chain.then_exception     29095808    33.633ns     0.093ns    33.541ns    35.308ns       1.094       1.094 …
> test: Add perf test to measure the "cost" of chain wakeup

- include/seastar/coroutine/exception.hh
- tests/unit/coroutines_test.cc
every user of the coroutine::exception helpers outside of seastar
namespace has to spell explicitly 'using namespace seastar' statement
to compile their code.
let's move the co_await operator into the exception type namespace to
take advantage of the ADL (argument-dependent lookup) language feature
to give the compiler a hint about the scan scope of the co_await operator.
> coroutine: ADL

- src/core/program_options.cc
With GCC 14.2.1 and Boost 1.86.0 the code failed to compile due to unknown type template `boost::type`. The include has been removed, possibly accidentally, from the non-module build in aa1c8b30fa
I tried it on Arch with GCC and Boost as above. CMake command (from repository root):
`cmake -S . -B build -DSeastar_DOCS=OFF`
```
[  1%] Building CXX object CMakeFiles/seastar.dir/src/core/program_options.cc.o /home/krzaq/code/temp/seastar/src/core/program_options.cc:82:64: error: ‘boost::type’ has not been declared
82 | memory::alloc_failure_kind from_string(const std::string& val, boost::type<memory::alloc_failure_kind>) {
|                                                                ^~~~~
/home/krzaq/code/temp/seastar/src/core/program_options.cc:82:75: error: expected ‘,’ or ‘...’ before …
```
> build: add missing include in program_options.cc

- src/core/io_queue.cc
Fix build failure with recent Clang implementations of CWG2813, which makes accessing static members through instance expressions into discarded-value expressions. This caused nodiscard warnings when accessing static member `tokens_capacity()` through `fgs[i]`.
Before:
```c++
fgs[i].tokens_capacity()  // Warns: ignoring nodiscard return value
```
After:
```c++
const auto& fg = fgs[i]); // not discarded
fg.tokens_capacity();     // access static member function
```
Additionally, this refactoring reduces repetition of `fgs[g_idx]` expressions throughout the code.
See:
- https://cplusplus.github.io/CWG/issues/2813.html
- https://eel.is/c++draft/expr.ref#2
Fixes Scylla build failure with the latest Clang, as Scylla enables Seastar_UNUSED_RESULT_ERROR.
> io_queue: fix static member access to comply with CWG2813

- include/seastar/core/fair_queue.hh
- include/seastar/util/shared_token_bucket.hh
- src/core/fair_queue.cc
- tests/manual/iosched_reproducers/one_cpu_starved_shard_can_still_saturate_io.sh
- tests/manual/iosched_reproducers/one_cpu_starved_shard_has_reasonable_fairness.sh
- tests/manual/iosched_reproducers/scylla_tablet_migration.sh
- tests/manual/iosched_reproducers/tau_nemesis.sh
- tests/unit/fair_queue_test.cc
The current design of `fair_group` isn't fair enough to shards.
During contention, the group will be -- aproximately -- taking requests
from shards one-by-one, in round robin.
This guarantees that each contender will dispatch an equal *number* of
requests. This is some kind of fairness, but it's not the kind we want,
probably ever.
A better kind of fairness is that under contention each shard should
be guaranteed `1/nr_shards` of the disk's IOPS and/or `1/nr_shards` of
byte-bandwidth, whichever dimension it pressures more.
This is needed so that each shard can be relied on to sustain a certain
rate of requests -- the lower bound of the slowest shard's throughput
usually dictates the throughput of the entire cluster.
But those two kinds of fairness are only the same if all IO requests have …
> fair_queue: make the fair_group token grabbing discipline more fair

- include/seastar/core/reactor.hh
- include/seastar/core/scheduling_specific.hh
- src/core/reactor.cc
- tests/unit/scheduling_group_test.cc
Improve handling of exceptions during scheduling group and scheduling group key creation, where a user-provided constructor for the keys may fail, for example.
We use a new struct `specific_val` and smart pointers to manage memory allocation, construction and destruction of scheduling group data in a safe manner.
We also reorder the initialization order to make it safer. For example, when creating a scheduling group, first allocate all data and then swap it into the scheduling group's data structure.
Fixes scylladb/seastar#2222
> scheduling_group: improve scheduling group creation exception safety

- src/core/resource.cc
On Fedora 41 AMI on some aarch64 instance such as m7gd.16xlarge, Seastar program such as Scylla fails to startup with following error message:
```
$ /opt/scylladb/bin/scylla --log-to-stdout 1
WARNING: debug mode. Not for benchmarking or production
hwloc/linux: failed to find sysfs cpu topology directory, aborting linux discovery.
scylla: seastar/src/core/resource.cc:683: resources seastar::resource::allocate(configuration &): Assertion `!remain' failed.
```
It seems like hwloc is failed to initialize because of /sys/devices/system/cpu/cpu0/topology/ not available on the instance.
I debugged src/core/resource.cc to find out why assert occured, and found that alloc_from_node() is failing because node->total_memory is 0. It is likely because of failure of hwloc initialize described above.
To …
> Fix seastar::resource::allocate() error on EC2 m7gd.16xlarge instance

- include/seastar/util/variant_utils.hh
Internally we only use it for lvalue references, so passing the argument to std::visit as is looks relevant. However, since seastar::visit accepts universal reference it should handle it appropriately for not to surprise callers by copying its argument implicitly.
> util/variant: make seastar::visit perfectly forward the value argument

- include/seastar/core/function_traits.hh
starting from 17th standard noexcept-specification is a part of the function type. function_traits doesn't have specializations
for noexcept function types thus cannot resolve the traits.
adding noexcept specializations allows function_traits for a larger class of function types fi noexcept future exception continuations. seastar supports 20th standard and newer thus there is no need to worry about compatibility.
> core: function_traits noexcept specializations

- src/net/ip.cc
- src/net/net.cc
boost::asio::ip::address_v4:to_ulong() was deprecated in 1.87 See https://github.com/boostorg/asio/commit/60b86035b3ff80d5fecebd8ae753becb9d9688c5
follow-up to: 11d17017fd1d135ce979e3fbff0adc4f71501bc6
> net: replace deprecated ip::address_v4::to_ulong() 

- cooking_recipe.cmake
- src/CMakeLists.txt
- src/core/memory.cc
Seastar is currently pulling in all of libnuma to just invoke a single
syscall. Additionally since libnuma being LGPL licensed, it's simpler
to not include it as a dependency. Replace the call in numaif.h with
a direct syscall.
I'm assuming that once libnuma was depended on because it was a
dependency of hwloc, however, hwloc version 2 removed the dependency
on libnuma, so Seastar can too:
https://github.com/open-mpi/hwloc/blob/263908a2c1f21c0e221a8d1f6472daf3a1fc07b9/NEWS#L291
> memory: remove libnuma dependency

- include/seastar/net/api.hh
- include/seastar/net/posix-stack.hh
- src/core/reactor.cc
- src/net/native-stack-impl.hh
- src/net/native-stack.cc
- src/net/posix-stack.cc
- src/net/stack.cc
Adds two basic metrics that track bytes sent and received from the
networking stack.
This can give a better per application insight than what host wide
metrics (for example via node exporter) can do.
Further it can serve as a comparison point with host based metrics for
possible write amplification (though this is less likely on the network
side).
The patch follows a similar pattern as to how memory and disk based
metrics work.
Note one might be inclined to introduce some grouping into the metrics
in relation to either the interface or source IP similar to how we have
mountpoints and/or groups on the disk side.
While this sounds useful at first in practice it would be less useful.
Often for the major cloud providers and similar in self hosted
environments there is only a single …
> net: Add bytes sent/received metrics

- .github/workflows/docker.yaml
- docker/dev/Dockerfile
When migrating from Ubuntu Matis to Orcular in afea41b1, the LLVM debian package repository configuration wasn't updated accordingly. This caused Docker builds to fail.
This commit updates the repository configuration to match the new Ubuntu Orcular base image.
Fixes #2656
> docker: update LLVM debian repo for Ubuntu Orcular migration

- cmake/SeastarConfig.cmake.in
- cmake/SeastarDependencies.cmake
SeastarDependencies.cmake is used in two scenarios:
- configure Seastar library, when building Seastar itself.
- configure Seastar library, when a parent project tries to
detect Seastar library. when building the Seastar application.
in the second case, we should respect the "REQUIRED" and "QUIET"
options passed to `find_package(Seastar)`. and CMake provides
`find_dependency()` macro for this purpose.
in this change, we conditionally call `find_dependency()` when
`SeastarDependencies.cmake` is used when this script is called
when finding Seastar library. this provides a better developer
experience to Seastar developers.
> build: use find_dependency() instead find_package() in config file

- src/core/reactor_backend.cc
The context schedules exit-time callback using deprecated reactor::at_exit() method. Switch to using internal non-deprecated one.
> aio_storage_context: Use reactor::do_at_exit()

- include/seastar/core/file.hh
- include/seastar/core/scheduling_specific.hh
- src/core/memory.cc
- src/core/reactor.cc
This pull request contains a series of improvements to address the build failures with musl libc.
- file: Replace `__gid_t` with standard POSIX `gid_t`
- scheduling_specific: Add `noexcept` wrapper for `free()`
- memory: guard `__GLIBC_PREREQ` usage with `__GLIBC__` check
Fixes #2667
> file, scheduling_specific, memory: fix build failures with musl libc

- include/seastar/core/fstream.hh
- src/core/fstream.cc
This is to facilitate making different sources depending on the actual file "type" and letting the caller wrap it into the input_stream().
Symmetrical make_file_data_sink was introduced by 52e0a763e87, not it's file_data_source turn.
Previous attempt to help file->source/sink conversion was #1419
> fstream: Export functions for making file_data_source

- test.py
this pr suggests adding to test.py the ability to build "offline" mode tests. i.e. exclude tests that require access to global resources. such tests always fail in a restricted environment and create a false impression of the project's performance.
also added the ability to feed ctest arbitrary parameters to gain more control over running tests.
> tests: adapt the test.py script to build project tests in offline mode and accept arbitrary arguments for ctest

- include/seastar/core/internal/stall_detector.hh
- src/core/reactor.cc
- fix `backtrace_buffer` class to print log on destruction, if the log wasn't printed before (this is what comment suggests should happen)
- `maybe_report_kernel_trace` function will be now called with `backtrace_buffer` object allocated by caller. This will "glue" kernel trace to the rest of the log, making sure the output stays together in the log file.
- `maybe_report_kernel_trace` function will no longer print empty `kernel callstack: ` messages.
> Improve log output in reactor-stalled situations

- include/seastar/core/future.hh
- include/seastar/core/reactor.hh
- src/core/future.cc
It's in fact such, there's even doxygen marking. Also, while at it, collect all the overloads in one code block.
> future: Move report_failed_future to internal namespace

- include/seastar/core/reactor.hh
Seem to be a leftover from some ancient days. There's no such variable any longer, the task_quota exists only on reactor config.
> reactor: Remove global task_quota extern declaration

- include/seastar/core/gate.hh
- tests/unit/CMakeLists.txt
- tests/unit/gate_test.cc
Allow specifying a name for the gate when created using a named exception factory,
to help debugging gate_closed_exception.
> gate: add named_gate

- src/http/mime_types.cc
It seems strange that `xml` isn't supported as a `mime` type here. 
In particular, we expect all [S3 REST error responses](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#RESTErrorResponses) to be returned with a `Content-Type` header of `application/xml`, so being able to map the extension makes life a lot easier for testing with imposter `http` S3 servers/services.
> `http`: add `xml` support to `http::mime_types::mappings`

- apps/io_tester/ioinfo.cc
- doc/io-properties-file.md
- include/seastar/core/io_intent.hh
- include/seastar/core/io_queue.hh
- include/seastar/core/reactor.hh
- include/seastar/core/resource.hh
- src/core/file-impl.hh
- src/core/file.cc
- src/core/io_queue.cc
- src/core/reactor.cc
- src/core/resource.cc
Currently, IO-queues assignment is done per-mountpoint. The mountpoint paths are read from io-properties.yaml file, for each the underlying device number is stat()-ed, then devive -> io_queue mapping is established. When opening a file, seastar stat()-s the filepath and finds the io_queue for the found device number.
It's nonetheless possible to have one physical disk be "split" into several virtual block devices, and to mount each into its own mountpoint. In order to configure io-scheduler for this setup the only option is to have two mountpoints in io_properties.yaml. With that, seastar will create two io_queues for both mountpoints, but it's not correct, since underlying physical disk is still the same.
This PR extends the io-properties.yaml configuration so that one disk entry in it …
> Share IO queues between mountpoints

- src/core/app-template.cc
We print a warning when SEASTAR_DEBUG is enabled, saying it's not for production or performance testing. This might be a suitable warning for the application itself to emit, but a framework like seastar should leave that choice up to the application. This warning cannot be supressed and does not follow the normal logging system, so it is unnecessarily noisy and interferes with anything which parses stderr.
> app-template: remove production warning

- include/seastar/core/reactor.hh
Both IDs are assign when constructing and never change. Mark both const to be explicit.
> reactor: Mark _id and task_queue::_id const

- src/core/reactor_backend.cc
- src/core/reactor_backend.hh
The field of the same name is aio_storage_context member of this very class. When reading the code these two fields of the same name mix with each other and confuse (a bit).
> aio_storage_context: Rename iocb_pool::_iocb_pool to _all_iocbs

- include/seastar/http/client.hh
- include/seastar/http/internal/content_source.hh
- include/seastar/http/reply.hh
- src/http/client.cc
- tests/unit/httpd_test.cc
If the server response includes a "Content-Length" header, keep track of the bytes read from the stream. When reading stops, the connection may be returned to the pool with leftover bytes, which could be read by the next connection user. To prevent this, reset the connection before returning it to the pool.
fixes: https://github.com/scylladb/seastar/issues/2759
> http: Track bytes read from a response

- include/seastar/http/reply.hh
- src/http/httpd.cc
- src/http/reply.cc
- tests/unit/httpd_test.cc
RFC 7231 Section 4.3.2
>  The HEAD method is identical to GET except that the server MUST NOT
>  send a message body in the response (i.e., the response terminates at
>  the end of the header section).
Seastar HTTPD doesn't respect that `MUST NOT` thing and allows body content in case handler requested for it.
Fix by explicitly skipping the body regardless of what handler put on it. Since replies are written back to connection in a separate fiber where the initial request is no longer available, add the "skip body" marking on the reply itself.
> httpd: Don't let body into the HEAD replies output

- include/seastar/core/temporary_buffer.hh
fixes compilation error:
seastar/core/temporary_buffer.hh:228:9: error: call to function 'memcpy' that is neither visible in the template definition nor found by argument-dependent lookup
228 |         memcpy(buf, view.data(), view.size());
also changed `memcpy` to `std::memcpy`
> temporary_buffer: include cstring for std::memcpy

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/tls_test.cc
This PR introduces client-side ALPN (Application-Layer Protocol Negotiation) to Seastar's TLS.
Clients can now specify a list of preferred application protocols (e.g., "h2", "http/1.1") in `tls::tls_options::alpn_protocols`. After the TLS handshake, the negotiated protocol can be retrieved using `tls::get_selected_alpn_protocol()`.
This is primarily motivated by the need to negotiate HTTP/2.
> tls: add ALPN support

- include/seastar/http/function_handlers.hh
- tests/unit/httpd_test.cc
In https://github.com/scylladb/seastar/commit/94c4c7a9e98be31ff11b07b8020ccbee7153e672 I introduced a bug where a particular overload of `function_handler` which had an arbitrary (passed-in) content type and which should simply set the body to the string-like content without encoding, would be instead treated as json. This resulted in a spurious pair of quotes added in the encoding process. 
This PR has a fix for that, courtesy of @mmaslankaprv as well as a test to avoid this in the future.
> Fix for non-json http function_handlers

- include/seastar/core/slab.hh
- tests/unit/CMakeLists.txt
- tests/unit/slab_test.cc
I was bothered that `slab_test.cc` was excluded from a `glob` in the test build rules for Seastar. An idea popped into my mind to ask Gemini 2.5 Pro if it could find a bug in the slab allocator.
It first found a bug in `can_allocate_page()` and later found the bug described in issues #520 and #105. It also proposed a fix identical to the one described by @yurai007.
It might be worth merging this fix or deleting the code altogether if it's not used anywhere.
---
Fixes two bugs in the slab allocator:
1. Crash on single-object page allocation:
When an object with a size equal to `max_object_size` was requested, a slab page capable of holding only that single object would be created. The logic incorrectly added this page's descriptor to the `_free_slab_pages` list, even though the page was …
> slab: correct allocation logic and enforce memory limits

- include/seastar/core/reactor.hh
- src/core/fstream.cc
This friendship is only needed to allow data source in question manipulate io_stats that sit on reactor. This PR does two things: replaces reference to reactor from file_data_source_impl to point to io_stats itself, and moves the friendship from reactor to io_stats too, thus making it much narrower.
> Relax reactor coupling with file_data_source_impl

- include/seastar/core/internal/pollable_fd.hh
- src/core/reactor.cc
- src/core/reactor_backend.cc
- src/core/reactor_backend.hh
The call chain nowadays is
pollable_fd::shutdown()
engine -> reactor_backend::shutdown()
pollable_fd_state -> file_desc -> file_desc::shutdown()
This patch removes reactor and its backend from this sequence.
Other pollable_fd methods are nowadays implemented likewise -- they forward the invocation to pollable_fd_state and the latter, if needed, call reactor backend. Shutdown doesn't need backend, but if it will, it's _state that will need to call backend.
> pollable_fd: Untangle shutdown()

- include/seastar/core/reactor.hh
The method is used by reactor itself to wakeup and serve seastar timers in timely manner. It's not the part of reactor public API.
> reactor: Move enable_timer() method to private section

- include/seastar/core/reactor.hh
This method doesn't exist in reactor nowadays
> reactor: Remove min_vruntime() declaration

- coding-style.md
This aligns the return types in the "Function parameters" section example.
> coding-style: Align example return types

- include/seastar/core/gate.hh
- tests/unit/gate_test.cc
With clang++ / c++23 we see the following error:
```
include/c++/15/bits/unique_ptr.h:93:2: error: delete called on non-final 'seastar::named_gate' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
```
> gate: make destructor virtual

- scripts/addr2line.py
- scripts/stall-analyser.py
As a follow-up to 4bd3d123, change the default addr2line tool to llvm-addr2line also for scripts/stall-analyser and the BacktraceResolver class.
> addr2line, scripts/stall-analyser: change the default tool to llvm-addr2line

- CMakeLists.txt
- include/seastar/core/disk_params.hh
- src/CMakeLists.txt
- src/core/disk_params.cc
- src/core/reactor.cc
- src/seastar.cc
- tests/unit/io_queue_test.cc
This PR adds two support patches that enable tests to configure an io_queue without duplicating code and calculations from within the reactor code and a unit test that calculates iops and bandwidth out of token bucket rate and costs and asserts that they are within 95% of the configured values.
Fixes #2822
> Add io_queue unit test for checking request rates

- src/core/metrics.cc
A metric must be unique. Trying to register two metrics with the same name and the same labels will throw an exception and, in many cases, terminate the process.
This patch adds the label values to the exception message to make it easier to understand which metric caused the exception.
An example
```
registering metrics twice for metrics: scylladb_current_version {"__level": "basic", "shard": "", "version": "2025.4.0~dev-0.20250709.69b5289a0e54"}
```
> Add label values to the duplicate metrics exception

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/tls_test.cc
Needed in https://github.com/scylladb/scylladb/pull/22961
2 methods have been added in order to expose more
information on the characteristics of a TLS socket connection.
> net: functions describing ssl connection

- include/seastar/core/posix.hh
The throw_kernel_error() template uses templatized error and checks that the type is signed with static_assert-ion. Using concept is more C++ish, and since this helper also implicitly assumes that the type is integral, the std::signed_integral seems to be the perfect fit.
> posix: Replace static_assert with concept

- scripts/addr2line.py
- scripts/seastar-addr2line
We sometimes parse large logfiles thorugh addr2line and noted that it can be quite slow and consume a large amount of memory. E.g., 3-15 minutes (the high end on memory constrained host) and 2.1 GB RSS in order to parse a 1.6 GB file.
The changes here improve that to 100 MB (probably almost all in the child addr2line process) and ~7s parsing time (split 6/1 in the Python code and addr2line itself).
Key perf changes are to not load the entire file into a `list` up front and to do a quick filter on each line to see if we should even bother applying the regexes. Details in individual commits.
* [`scripts/addr2line.py`](diffhunk://#diff-cd6a2af470efe68703f2ffd367c7b7e260f28ced194949fb1571a53d7d5f4ab8R356-R360): Added timing functionality to measure and log the duration of address resolution …
> addr2line timing and optimizations

- include/seastar/core/linux-aio.hh
- include/seastar/core/reactor.hh
- include/seastar/core/reactor_config.hh
- src/core/file.cc
- src/core/reactor.cc
- src/core/reactor_backend.cc
- tests/unit/file_io_test.cc
When setting up aiocb, the set_nowait() helper checks two bits:
- global aio_nowait_supported, which comes from CLI option whose default value depends on the kernel uname
- per-request nowait_works, which is inherited from file that gets it from fs_info object filled based on filesystem type and, again, kernel uname value
This patch removes the global bit, keeps the respective CLI option on reactor config and then updates the per-filesystem fs_info nowait_works with it.
"While at it" drop few unneeded forward declaration.
> aio: Squash aio_nowait_supported into fs_info::nowait_works

- include/seastar/websocket/common.hh
- src/websocket/common.cc
There's a helper that sends a simple header and a temporary_buffer payload to the output_stream. Modern output_stream-s allow mixing buffered prefixes (the header) and zero-copy payloads (temp. buffer).
This change will allow to deprecate and remove net::packet from output_stream API eventually.
> websocket: Avoid sending scattered_message to output_stream

- include/seastar/core/iostream.hh
The one with raw buffer size and trim-to-size boolean was deprecated several years ago by commit babac6de08 (iostream: Use options struct construct output_stream) and can now be removed.
> iostream: Remove deprecated constructor

- include/seastar/core/iostream-impl.hh
The method imples that the stream is not used (or at best flushed). The check is incomplete, used stream may have empty _buf, but non-empty zc buffers, which also need to be checked.
> iostream: Update "used stream" check for output_stream::detach()

- src/net/dns.cc
In order to send requests, the dns fiber calls
connected_socket::output() to get the output_stream for the socket. However, the stream itself is not really needed -- the buffer size is set to zero and the only sent message is the zero-copy packet.
For that use-case the detached data_sink fits much better.
This will allow to deprecate and eventually remove the net::packet from the output_stream API.
> dns: Use TCP connection data_sink directly

- tests/unit/fair_queue_test.cc
The fair_queue tests all look the same -- they put some amount of requests into a fair queue, then try to process some other amount of requests from it with the help of a tick(int n) method, and then check that the per-class processed counters are in expected ratio.
The tick() method used to contain two dispatch loop, since the processing code was "time-based" due to outgoing throttler code. Recently (scylladb/seastar#2820) the throttler code was moved to the io-queue and the fair-queue dispatch loop was re-implemented to be very precise in terms of amount of requests dispatched by the test. With that, the 2nd dispatch loop in the test ticker becomes dead code and can be removed.
> test: Remove no-op dispatch from fair_queue ticker

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/tls_test.cc
Fixes #2859 
If a TLS session enters into a re-handshake (such as session key refresh) at the same time as a large buffer is being sent, gnutls will bypass the normal breaking up of sent data into block-size (16k default) buffers, and cause an allocation of a intermediate buffer of <data size> + <session key size>.
(See gnutls_record_send2, case RECORD_SEND_KEY_UPDATE_1).
To prevent this, we need to explicitly break up sent buffers into block-size parts, ensuring the intermediate alloc remains small-ish.
Includes adding a white-box function for forcing re-handshake.    
Includes test using said white-box forcing of re-handshaking.
> TLS: Force buffer splitting into gnutls record block sized chunks

- apps/io_tester/io_tester.cc
- apps/io_tester/sched.yaml
The nested IO classes support is coming, so the io_tester should be patched to create nested layouts too. However, nesting of sched groups is standalone API, that's aready in, so io_tester can be patched right now (without visible effect on the IO part).
The support is to introduce the --sched-groups option that provides a YAML file with sched groups listed in it. The job config already supports assigning individual jobs to sched groups by the sched group names, so no other actions are needed.
> io_tester: Add support for scheduling supergroups

- src/core/exception_hacks.cc
We disable interception of _Unwind_RaiseException when ASAN is enabled since it can produce a large number of stack-related false positives when it is enabled and exceptions are thrown.
Some notes:
- ASAN also intercepts `_Unwind_RaiseException` and perfoms stack-related bookeeping work in there relating to the unwinding that is about to occur.
- In the reproducers I looked at, both seastar and ASAN URE functions are called, ASAN first, sesatar second. 
- The problem seems to be with the logging call we do in the seastar: if that is commented out, the problem is not observed. One could speculate the problem arises with anything that uses the stack in non-trivial ways and the rest of the stuff in there is trivial.
- The problem occurs at -O1 and -O2, but not at -O0, and one can speculate …
> disable exception interception when ASAN enabled

- include/seastar/http/client.hh
- src/http/client.cc
- src/http/request.cc
- tests/unit/httpd_test.cc
Currently, if a request passed into client::make_request() fails validation (missing version and inconsistent body content vs headers) the method throws, while it's a furure<>-returning method and should return exceptional future instead. This PR turns exception into a future.
Other than that, request validation is moved, so that it happens once per make_request(). Nowadays it happens on every retry.
And finally, placing defaults on request is moved from connection::make_request() into request::make(), so that client request making API accepts const request reference (finalizes the #1848 effort)
> Fix and tune http::request setup by client

- src/util/log.cc
We notice that assertion messages are not being printed as expected.
In these cases you simply see a message like (libc++):
```
libc++abi: terminating
Aborting on shard 0, in scheduling group main.
Backtrace:
```
libstd++ is similar:
```
terminate called without an active exception
Aborting on shard 0, in scheduling group main.
Backtrace:
```
Underlying cause is that we print to stdout, and stdout is not explicitly flushed. In cases where stdout is not line buffered, we will close the message (so e.g., when the output is piped or redirected).
We should (a) assert to stderr, not stdout, and (b) flush the stream.
This is in line with libc and the C++ standard (though it specifies that abort() is called, not std::terminate()).
> SEASTAR_ASSERT: assert to stderr and flush stream

- apps/io_tester/conf.yaml
- apps/io_tester/io_tester.cc
The PR does several things with the aforementioned workload types.
First, it fixes the way APPEND interacts with file-size parameter. Nowadays the append fills a file and then starts appending data to it, which is weird -- pre-filling data is thus pretty pointless. After this PR append will start from position of zero all the time and not fill the file beforehand. The configured file size will only be used to truncate the file to that size. Note, that append workload is _not_ O_APPEND and it will write into file from start to end regardless of its size.
Also the PR renames "seqwrite" workload into "overwrite", because strictly speaking "append" is also sequential write. So this new "overwrite" name better explains what the workload type is about.
And, while at it, coroutinizes some code …
> Improve io_tester's seqwrite and append workloads

- include/seastar/core/future.hh
- include/seastar/coroutine/exception.hh
- include/seastar/util/log-level.hh
- include/seastar/util/log.hh
- src/core/exception_hacks.cc
Log thrown exceptions with debug and propagated (via future) exceptions with trace levels. Allows seprately logging just thrown exceptions, which are the actual bad ones, hurting performance.
> exceptions: log thrown and propagated exception with distinct log levels

- include/seastar/http/reply.hh
- src/http/httpd.cc
- src/http/reply.cc
- tests/unit/httpd_test.cc
Cookies are problematic to use with existing set_header() and friends, as multiple cookies are expected to be set with multiple Set-Cookie header lines, which is a problem for the current header related infrastructure which assumes one value for one header key. Introduce separate mechanism for setting cookies, allowing for multiple cookies to be set. Set-Cookie headers are written separately after the normal headers are written.
> http/reply: introduce set_cookie()

- include/seastar/core/task.hh
Much shorter this way. All the more so the corresponding ifdef also controls the peer make_backtrace() declaration and definition.
> task: Move task::get_backtrace() definition in its class

- apps/io_tester/io_tester.cc
- apps/memcached/memcache.cc
- apps/seawreck/seawreck.cc
- demos/tcp_sctp_client_demo.cc
- demos/tcp_sctp_server_demo.cc
- include/seastar/core/distributed.hh
- include/seastar/core/prometheus.hh
- include/seastar/http/httpd.hh
- src/core/prometheus.cc
- src/http/httpd.cc
- src/seastar.cc
- tests/unit/distributed_test.cc
- tests/unit/foreign_ptr_test.cc
- tests/unit/rpc_test.cc
- tests/unit/thread_context_switch_test.cc
The distributed<T> was renamed to be sharded<T> long ago (ab7be2890) Encourage people to use the latter name more actively
> sharded: Deprecate distributed alias

- include/seastar/net/tls.hh
- src/net/tls.cc
- tests/unit/tls_test.cc
First things first, when a TLS socket is shutdown or closed, it leaves a background fiber that sends GNUTLS_BYE message, wires a timer for 10 seconds and waits until EOF appears on the socket. If the timer fires earlier, the underlying socket is closed (thus implicitly causing the EOF to appear).
Whether or not to wait for the EOF is controlled by the tls_options bit called wait_for_eof_on_shutdown, and it's "true" by default.
This patch includes several interconnected enhancements to that process.
First, the aforementioned bool value is replaced with with the timeout value in seconds (default is 10). The related change: if the configured timeout is zero, the BYE message is not sent at all, the socket is just closed. This is not compatible with existing wait_for_eof_on_shutdown which does …
> tls: Rework session termination

- include/seastar/core/fair_queue.hh
- include/seastar/core/io_queue.hh
- include/seastar/core/reactor.hh
- src/core/fair_queue.cc
- src/core/io_queue.cc
- src/core/reactor.cc
- tests/unit/fair_queue_test.cc
- tests/unit/io_queue_test.cc
Add one-level nesting support for IO priority classes. Since all shares-based scheduling of IO happens inside fair_queue code, this PR mainly updates it. The io_queue code is touched to propagate scheduling_supergroup hierarchy and changes down to the fair_queue. This change follows those made for CPU task_queues.
Currently, the scheduling_groups is backed by reactor::task_queue object for CPU scheduler and by fair_queue::priority_class_data for IO. For nesting, the scheduling_supergroup was added (see #2823) at the API level. It was then backed by the reactor::task_queue_group in the CPU scheduler, where both task_queue and task_queue_group inherit from sched_entity abstraction. On the IO side supergroup maps to fair_queue::priority_class_group_data and both, priority_class_data and …
> Nested scheduling groups (IO classes)

- src/net/posix-stack.cc
When making unique_ptr for posix_connected_socket_impl one cannot use the make_unique directory, as the _impl's constructor is private, so the ptr is created default-initialized and then reset() with the result of new invocation. Initializing the ptr with new result is simply shorter.
> posix-stack: Initialize unique_ptr-s with new result directly

- CMakeLists.txt
- include/seastar/http/client.hh
- include/seastar/http/retry_strategy.hh
- src/CMakeLists.txt
- src/http/client.cc
- src/http/retry_strategy.cc
Introduce extensible retry strategy machinery for the HTTP client to simplify adding new retry conditions. Rather than modifying seastar code to support additional error types, users can now provide their own custom implementations of the retry strategy—offering flexibility without repeated code changes.
Fixes: https://github.com/scylladb/seastar/issues/2803
Scylladb based on these changes: https://github.com/scylladb/scylladb/pull/25801
> http: Introduce retry strategy machinery for http client (take two)

- src/core/resource.cc
The vector of CPUs can be made const reference instead of value to avoid its copying (although the method is called for each IO queue and there are typically two of them)
The cpu-to-node map is a reference already, but keeping it const ref is safer.
> resource: Tune up some allocate_io_queues() arguments

- tests/unit/CMakeLists.txt
- tests/unit/timer_test.cc
It currently has several sub-test-cases, it's easier to maintain them using standard seastar test framework.
Also there's homebrew BUG and OK macros. It's better to use BOOST_REQUIRE/_CHECK instead of the former. The latter is just dropped.
> Convert timer test into seastar test (and a bit more)

- .clangd
- .gitignore
.clangd: tell the LSP about seastar's header style
Seastar includes all public using angle brackets.
Tell clangd about it so that it gets it right (available since clangd 20).
Also removes .clangd from .gitignore. This was added in:
https://github.com/scylladb/seastar/pull/1640
with the assertion that clangd stores its index there (and .cache), but
that is not correct: it uses only .cache and possibly some other
directories outside the project, but .clangd itself has always been
a configuration file (that should be checked in).
> .clangd: tell the LSP about seastar's header style

- src/core/io_queue.cc
Some messages from io_queue.cc are printed using seastar_logger, but there's io-queue own logger for that.
> io_queue: Use own logger for messages

- apps/io_tester/io_tester.cc
When performing IO sequentially, io_tester's get_pos() helper adds request size to initial value of the "current position" and then returns it, thus skipping the 0th position in a file.
Fix it, and rename the _last_pos to be _next_seq_pos to better reflect what the field is about.
> io_tester: Don't skip 0 position in sequential workflows
